### PR TITLE
report prescribed advection field timer

### PR DESCRIPTION
**Pull request by tjhei**
part of #3322, now down to 12% unaccounted.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Could also be shortened to "Prescribe temperature" "Prescribe composition", and "Prescribe Stokes solution" or "Interpolate temperature", "Interpolate composition", "Interpolate Stokes solution"

**Comment by tjhei** [comment]
I changed it to your first suggestion.

**Comment by tjhei** [comment]
I don't really like the ordering of the timing sections (done alphabetically). I have a few suggestions to improve it:
1. Rename them as "Stokes: Assembly", "Stokes: build preconditioner", etc. to have things grouped reasonably well.
2. Add a feature to deal.II to not reorder things but keep them in the order they are first executed (might not be super useful).
3. Define a custom ordering and teach deal.II about that.
4. Rename things, for example using "1. xxx" to force a good numbering.
Thoughts?

**Comment by gassmoeller** [comment]
I am not sure renaming would be a good idea, at least I have some scripts that will break (though if we decide that is the best way I am ok with it). Would it be possible to add an optional parameter to the timer class that defines the position of a section? Or to hand over a map when printing the sections that links section name to position?

**Pull request merged**
