### PR TITLE
CMake fixes

### PR DESCRIPTION
**Pull request by tjhei**
- improve output and formatting when running cmake
- be more consistent about capitalization (the cmake package is called "Aspect" not "ASPECT")
- correctly detect when ASPECT is not found
- export ASPECT version information so plugins can require a minimum version
- update all the contained plugins

### CODE REVIEW

**Comment by tjhei** [comment]
This should fix #1036. @gassmoeller you had a different issue related to ccmake, can you try to reproduce with this PR?

**Comment by gassmoeller** [comment]
For reference, the error before this PR on cmake 2.8.12.2, when switching the aspect directory in ccmake is:

`CMake Error: An attempt was made to access a variable: ASPECT_DIR that has
 not been defined. This variable is created by the FIND_PACKAGE command. CMake
 version 1.6 always converted the variable name to upper-case, but this
 behavior is no longer the case.  To fix this you might need to set the cache
 value of CMAKE_BACKWARDS_COMPATIBILITY to 1.6 or less.  If you are writing a
 CMake listfile, you should change the variable reference to use the case of
 the argument to FIND_PACKAGE.`

Next I will check if that is solved by this PR

**Comment by gassmoeller** [comment]
This does not seem to fix my problem.

With this PR (and the modified CMakeLists) I get more errors:

`CMake Error: An attempt was made to access a variable: ASPECT_DIR that has
 not been defined. This variable is created by the FIND_PACKAGE command. CMake
 version 1.6 always converted the variable name to upper-case, but this
 behavior is no longer the case.  To fix this you might need to set the cache
 value of CMAKE_BACKWARDS_COMPATIBILITY to 1.6 or less.  If you are writing a
 CMake listfile, you should change the variable reference to use the case of
 the argument to FIND_PACKAGE.

 CMake Error: An attempt was made to access a variable: ASPECT_DIR that has
 not been defined. This variable is created by the FIND_PACKAGE command. CMake
 version 1.6 always converted the variable name to upper-case, but this
 behavior is no longer the case.  To fix this you might need to set the cache
 value of CMAKE_BACKWARDS_COMPATIBILITY to 1.6 or less.  If you are writing a
 CMake listfile, you should change the variable reference to use the case of
 the argument to FIND_PACKAGE.`

**Comment by tjhei** [comment]
The newest patch works for me with cmake 2.8.12.2: I tried a couple of variants with/without ccmake. Can you take another look please?

**Comment by gassmoeller** [comment]
I still get the errors. Apparently, I need to remove the `${ASPECT_DIR}` from all  `FIND_PACKAGE(Aspect 1.5.0 QUIET HINTS ${Aspect_DIR} ${ASPECT_DIR} ../ ../../ $ENV{ASPECT_DIR}) ` commands in the CMakeLists.txt files to make them disappear.

**Comment by tjhei** [comment]
yes, oops. That is useless anyways.

**Comment by tjhei** [comment]
updated, not tested again.

**Comment by gassmoeller** [comment]
I will test.

**Comment by tjhei** [comment]
updated documentation.

**Pull request merged**
