### PR TITLE
move VoFHandler implementation into single .cc

### PR DESCRIPTION
**Pull request by tjhei**
part of #3633

### CODE REVIEW

**Comment by tjhei** [comment]
I am not a big fan of moving everything into a single .cc but I don't know of a good way around it: putting them into a header that is then ``#include``'d, doesn't seem to be the better choice.

**Comment by bangerth** [comment]
The unity tester fails, but I think that's because of a connectivity problem. If you're confident that that's spurious, then go about and merge yourself.

**Comment by tjhei** [comment]
Let's not go this way and look into #3653 instead.

**Comment by bangerth** [comment]
So just out of curiosity, why *not* combine the file? Is it getting so large that it's going to dominate build time?

**Comment by tjhei** [comment]
> So just out of curiosity, why _not_ combine the file?

I think they were split up to separate code by topic (and this is unrelated to code size). I don't think this is very important when using an IDE these days.

Do you want to combine all instances into single files (core.cc/helper_functions.cc/etc.)? If not, then we need the work-around for unity builds. Then I don't see a need to merge this PR.

**Pull request closed without merging**
