### PR TITLE
Use a constraints object of the right size.

### LINKED ISSUE #5412: How to call constraints.distribute() in solve_stokes().
While looking at #5398 (see also #5405), I came to realize that `solve_stokes()` has a design problem that I don't quite know how to work around.

At its core, this is the situation: In `solve_stokes()`, we create a `distributed_stokes_solution` vector that has only one or two blocks (and so represents a subset of the blocks and degrees of freedom of a complete solution vector), but then we call
```
  current_constraints.distribute(distributed_stokes_solution);
```
where `current_constraints` is an `AffineConstraints` object that represents constraints on *all* constraints on DoFs. (`current_constraints` is initialized in `compute_current_constraints()`, which fills it with a set of constraints for *all* variables, not just a subset, such as the Stokes variables.)

The fact that this used to work is a bit of a miracle before because one could imagine that there are constraints also for other variables and I have no idea what `AffineConstraints::distribute()` is supposed to do with constraints for DoFs that simply are not in `distributed_stokes_solution` because the latter is a truncated vector. This looks like a pre-existing bug to me, even though it wasn't caught with an assertion.

The question is how to deal with this in `solve_stokes()` now that
```
  current_constraints.distribute(distributed_stokes_solution);
```
is simply no longer legal. I can see a number of options:

- We create a constraints object that would only work on the Stokes variables. Presumably, we would extract that from the `current_constraints` object in some way,  a bit like `IndexSet::get_view()`, perhaps. The problem is that there is no function `AffineConstraints::get_view()` that would do this. Since we're only facing a problem with current deal.II master branch, however, such a function could be implemented and used to fix the issue here.
- We copy `distributed_stokes_solution` into a `distributed_solution` vector, apply the constraints on that, and then as necessary copy back. Not super efficient in terms of memory and communication, but feasible.
- Options I can't imagine yet.

Opinions on these matters? I must admit that I'm a bit stuck :-)

### PR DESCRIPTION
**Pull request by bangerth**
I *think* that this addresses the remaining two test failures in #5398, following #5405. This fixes #5412. Let's see what the tester says.

I actually quite like this solution. This thing with "views" is how this is supposed to work I believe.

### CODE REVIEW

**Comment by bangerth** [comment]
Arg, the docker image isn't up to date yet...

**Comment by gassmoeller** [comment]
I updated the docker image and it compiles this PR now, but some tests with deal.II master are not happy about the changes (https://github.com/geodynamics/aspect/actions/runs/6438520581/job/17494588507?pr=5419#step:6:469)

**Comment by bangerth** [comment]
Oh, ugh. On it.

**Comment by bangerth** [comment]
We do the same thing in a third place, in the matrix-free framework. Fixing that one as well now...

**Review by gassmoeller — APPROVED** [review]
A passing tester, yay.
Also the code changes look reasonable.

**Comment by bangerth** [comment]
Yay, this is good news. I'm glad we're back to zero failures!

**Pull request merged**
