### PR TITLE
Correct behavior of VoF interface refinement algorithm near MPI process boundaries

### PR DESCRIPTION
**Pull request by class4kayaker**
### Describe the content of this pull request, and why you did these changes:

When running a test problem, I encountered a case where the VoF advection algorithm was not encountering the maximally refined region near the fluid interface. Upon farther testing, the issue was localized to being a case where a cell that should have been marked as neighboring the interface in the first pass was not causing cells sharing vertices to be refined. This is intended to fix this case by adding a communication step that will ensure that any cell which is marked by the owning process will be marked on all processes. Because the owning process must have all neighboring ghost cells, this should make certain that any cell which would be marked on any process will be marked on all processes that need to reference it.

### Before submitting your first pull request:

* [x] I have read the guidelines in our [CONTRIBUTING.md](../CONTRIBUTING.md) document.

### For all Pull Requests:

* [x] I have followed the instructions for indenting my code according to ASPECT's code style as described in the last paragraph of the ['Making ASPECT better'](../CONTRIBUTING.md#making-aspect-better) section of CONTRIBUTING.md.

### For Feature/Benchmark Submissions or Changes of Existing Behavior:

* [x] I have tested my new feature locally to ensure it is correct.

### CODE REVIEW

**Comment by class4kayaker** [comment]
Is there an easy way to induce this state for testing? The line in question uses a function documented to refer to the global dof count, and is needed to bypass the case where only the triangulation exists, but not the state data.

**Comment by bangerth** [comment]
@class4kayaker: The way to test this is to use more processors than cells. So use a mesh with 4 cells and 5 processors, or similar. This way, at least one processor can not own a cell.

**Comment by bangerth** [comment]
In reference to #835.

**Comment by class4kayaker** [comment]
Test added.

**Comment by gassmoeller** [comment]
@tjhei: Did Jon address your concerns?

**Comment by tjhei** [comment]
> @tjhei: Did Jon address your concerns?

Yes, this is correct. I assumed that the ``n_dofs`` check at the beginning of the function could happen on some processors, but this is not true (it returns the global number of DoFs). :+1:

**Pull request merged**
