### PR TITLE
Update tester images with netcdf

### PR DESCRIPTION
**Pull request by gassmoeller**
Follow up to #5487
Adress part of #5447.

The deal.II 9.4 tester is done, I am rebuilding 9.5 right now, I will retrigger the tests for this PR tomorrow when that is done.

### CODE REVIEW

**Review by tjhei — APPROVED** [review]
Awesome, thank you.

**Review by tjhei — APPROVED** [review]

**Comment by gassmoeller** [comment]
I am open for either. However, I am confused: If candi installs netcdf, it also adds `$NETCDF_DIR` environment variable in the `enable.sh` script, which should enable ASPECT to find it. Is the root problem that `enable.sh` is not executed when we startup the container? Wouldnt that be the best solution then?

**Comment by tjhei** [comment]
> Is the root problem that `enable.sh` is not executed when we startup the container? Wouldnt that be the best solution then?

Correct. I don't know if there is an easy way to do this, though. Maybe you know better. What I did in the tjhei/candi images is something like this:
https://github.com/tjhei/candi/blob/0a06374f7b2a61920d9fa0d9ecdf1f3409707e8f/v92/Dockerfile.in#L23-L43

**Comment by gassmoeller** [comment]
Good point. Let me incorporate the variable into the image. Rebuilding right now.

**Comment by gassmoeller** [comment]
See #5495.

**Pull request merged**
