### PR TITLE
Fix manual typo

### PR DESCRIPTION
**Pull request by KiralyAgi**
I corrected earth to Earth in a few places (not everywhere) in the manual

### CODE REVIEW

**Comment by bangerth** [comment]
/rebuild

Nice!

**Comment by tjhei** [comment]
these are two unrelated edits, can you make separate PRs please?

**Comment by gassmoeller** [comment]
In general: Please leave a comment after you have addressed a review, otherwise we might not notice your changes, or think you are not done yet.

**Comment by gassmoeller** [comment]
But otherwise, ready to go. Thanks for the contribution :+1:

**Pull request merged**
