### PR TITLE
Make sure we set flags before we use them to output physical units.

### LINKED ISSUE #4128: Including units within pvtu metadata output
I'm trying to specify field units in the outputted pvtu (and other outputted file formats) metadata.  This will make reading in ASPECT output easier with the Yt-project and will prevent confusion related to future changes in units.  Any help/ direction would be awesome!

### PR DESCRIPTION
**Pull request by bangerth**
We had an ordering problem in that we first create the `.pvtu` file and only then populated fields in the `VtkFlags` structure that is used in determining metadata for the `.pvtu` file. This is easily fixed by moving the code blocks into their correct order. As a result, we now put physical units also into the `.pvtu` file:
```
<?xml version="1.0"?>
<!--
#This file was generated by the deal.II library on 2024/6/1 at 10:32:26
-->
<VTKFile type="PUnstructuredGrid" version="0.1" byte_order="LittleEndian">
  <PUnstructuredGrid GhostLevel="0">
    <PPointData Scalars="scalars">
    <PDataArray type="Float32" Name="velocity" NumberOfComponents="3" format="ascii" units="m/year"/>  *********
    <PDataArray type="Float32" Name="p" format="ascii" units="Pa"/>                                    *********
    <PDataArray type="Float32" Name="T" format="ascii" units="K"/>                                    *********
    </PPointData>
    <PPoints>
      <PDataArray type="Float32" NumberOfComponents="3"/>
    </PPoints>
    <Piece Source="solution-00000.0000.vtu"/>
  </PUnstructuredGrid>
</VTKFile>
```

Fixes #4128.

### CODE REVIEW

**Comment by tjhei** [comment]
Looks good. Did you mean to close #4128 with this PR?

**Comment by bangerth** [comment]
Yes. All of the other parts there are already addressed.

**Comment by tjhei** [comment]
```
The following tests FAILED:
	601 - parallel_output_group_0 (Failed)
	602 - parallel_output_group_1 (Failed)
	603 - parallel_output_group_2 (Failed)
```

**Comment by bangerth** [comment]
Yes, that was to be expected I suppose. Let's see what happens now!

**Review by gassmoeller — APPROVED** [review]

**Comment by gassmoeller** [comment]
Is this worth a changelog entry? So far users wouldnt have seen the units, now they do.

**Comment by bangerth** [comment]
Good idea. So done.

**Review by tjhei — APPROVED** [review]

**Pull request merged**
