### PR TITLE
Urlreader fix

### PR DESCRIPTION
**Pull request by kneumiller**
Pull Request Checklist. Please read and check each box with an X. Delete any part not applicable. Ask on the [forum](https://community.geodynamics.org/c/aspect) if you need help with any step.

Quick pull request to change how data is handled (and checked) from the requested url

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).

### CODE REVIEW

**Comment by tjhei** [comment]
@kneumiller can you explain what this fix changes please? Did something change on the server side or is this an optimization?

**Comment by kneumiller** [comment]
> @kneumiller can you explain what this fix changes please? Did something change on the server side or is this an optimization?

The fix was because we wanted to change how the csv data was stored on the server from string to floats so I modified the url reader to check for this instead. The main changes are with the data itself and how it's stored on the server but I needed to update the code in Aspect to reflect these changes.

**Comment by tjhei** [comment]
> we wanted to change how the csv data was stored on the server

When is this change on the server going to happen? Does this mean that the old code stops working at that moment or can the server serve both?

**Comment by kneumiller** [comment]
We pushed the changes up to the server. We decided to have the url reader extension look for float32 values instead of strings. The old code won't work because the old file (the one with string values) had the data mangled when it was uploaded.
I can probably modify it so that it can check for both, but we assumed just passing numeric values as floats instead of strings was better,

**Comment by tjhei** [comment]
> We pushed the changes up to the server. We decided to have the url reader extension look for float32 values instead of strings. The old code won't work because the old file (the one with string values) had the data mangled when it was uploaded.

OK. When you say "mangled", are you saying that the old client/server was not producing correct data? I thought this was tested to work?

I know backwards compatibility is difficult and not easy for online components, but I am a bit sad that the server suddenly changes and libdap in ASPECT 2.2 is now broken. There are plenty of people who use ASPECT 2.2. Anyways, I am happing to move forward with this change now, but it would be great to be more careful about these things in the future. One could keep old datasets in the old format, for example.

**Comment by tjhei** [comment]
Can you please rebase to the current ASPECT master to remove the merge commit?

**Comment by kneumiller** [comment]
> Can you please rebase to the current ASPECT master to remove the merge commit?

Yup! It should just be the two commits now, sorry for the hassle.



> > We pushed the changes up to the server. We decided to have the url reader extension look for float32 values instead of strings. The old code won't work because the old file (the one with string values) had the data mangled when it was uploaded.
> 
> OK. When you say "mangled", are you saying that the old client/server was not producing correct data? I thought this was tested to work?
> 
> I know backwards compatibility is difficult and not easy for online components, but I am a bit sad that the server suddenly changes and libdap in ASPECT 2.2 is now broken. There are plenty of people who use ASPECT 2.2. Anyways, I am happing to move forward with this change now, but it would be great to be more careful about these things in the future. One could keep old datasets in the old format, for example.

Yeah, there was some miscommunication between Opendap and the Balto team on the data being uploaded to our servers. The data itself was the issue and hopefully this fix will prevent it from happening in the future.

**Review by tjhei — APPROVED** [review]

**Comment by tjhei** [comment]
Thanks!

**Pull request merged**
