### PR TITLE
Fix some wrong index sets.

### PR DESCRIPTION
**Pull request by bangerth**
This fixes at least one of the failing tests in https://github.com/geodynamics/aspect/pull/5398. Let's see how many other tests fail, and then I can address those as well.

/rebuild

### CODE REVIEW

**Comment by bangerth** [comment]
I have it down to two failing tests. I hope to be able to debug these still today. But if anyone is antsy to get the other fixes in, feel free to merge and I'll put the remaining fixes into a separate PR.

**Comment by bangerth** [comment]
The currently failing tests with this patch are these two:
```
The following tests FAILED:
	655 - particle_periodic_boundaries_dc (Failed)
	673 - periodic_box2 (Failed)
```
I think it would be useful to merge the patch as is, given that it's an improvement over the current state.

The other issue (that causes these two failures) is more complicated, and a pre-existing issue. Basically, it boils down to the fact that in `solve_stokes()`, we create a `distributed_stokes_solution` vector that has only two blocks (and so represents a subset of the blocks and degrees of freedom of a complete solution vector), but then we call
```
  current_constraints.distribute(distributed_stokes_solution);
```
The fact that this used to work is a bit of a miracle before because one could imagine that there are constraints also for other variables and I have no idea what `AffineConstraints::distribute()` is supposed to do with constraints for DoFs that simply are not in `distributed_stokes_solution` because the latter is a truncated vector. This looks like a pre-existing bug to me, even though it wasn't caught with an assertion. I'm writing a patch for that, but that might take a day or two and it's a separate issue regardless.

**Comment by bangerth** [comment]
Yes, that other issue turns out to be quite complicated. It's not going to happen today.

**Review by tjhei — APPROVED** [review]

**Comment by tjhei** [comment]
Yes, these are correct. Thank you.

**Pull request merged**
