### PR TITLE
Add non-convex polygons to test and remove statement

### PR DESCRIPTION
**Pull request by anne-glerum**

### CODE REVIEW

**Comment by bangerth** [comment]
Changed your mind about the need for convexity? ;-)

You'll have to indent, and update the test output.

**Comment by anne-glerum** [comment]
Indeed, sorry!

**Comment by gassmoeller** [comment]
So the algorithm is already correct for concave polygons, and we were just missing a test? If so, this is ready to merge.

**Comment by anne-glerum** [comment]
Yes it's correct for concave polygons.

**Pull request merged**
