### PR TITLE
Correct the type used to indicator boundary_ids.

### PR DESCRIPTION
**Pull request by bangerth**
This addresses #310.

### CODE REVIEW

**Comment by bangerth** [comment]
Strictly speaking, this is an incompatible change: it may break user plugins because of the different type of the argument of a virtual function. I suspect that there are few who have such plugins.

The question is: do we want this change? Should I write an entry in `changes.h`?

**Comment by tjhei** [comment]
> do we want this change?

yes.

> Should I write an entry in changes.h?

yes.

and please fix the following tests:
```
	163 - tangurnis (Failed)
	166 - time-dependent-temperature-bc-2 (Failed)
	167 - time-dependent-temperature-bc (Failed)
```

**Comment by gassmoeller** [comment]
I am supporting it as well (although I have some plugins that I need to update now). But could you have a look at `boundary_temperature/ascii_data.cc:63` and `boundary_composition/ascii_data:65`? With your changes these lines can be removed.

**Comment by bangerth** [comment]
@tjhei : I fixed the tests, thanks for pointing it out. I also added a changelog entry.

@gassmoeller : Good point!

**Comment by gassmoeller** [comment]
It seems everything works. Thanks for cleaning this up.

**Pull request merged**
