### PR TITLE
Updated documentation in FK header file

### LINKED ISSUE #5730: add Frank-Kamenetski eq in manual
@Grant-Block could you please add documention (equation + link to literature) ?

### PR DESCRIPTION
**Pull request by Grant-Block**
The FK header file now has the correct formula and references a paper with the FK formulation.

Fixes #5730.

### CODE REVIEW

**Review by naliboff — APPROVED** [review]
👍

**Comment by bangerth** [comment]
@cedrict Is this what you were looking for?

**Comment by cedrict** [comment]
@bangerth yes, nice!

**Pull request merged**
