### PR TITLE
Moved several benchmark's documentation

### PR DESCRIPTION
**Pull request by sac-bsa**
*Describe what you did in this PR and why you did it.*
Moved the documentation for the Rayleigh-Taylor instability, sinking block, SolCx, SolKz, and inclusion benchmarks. I also updated the Makefile so that the .prm files in compositional_field subdirectories would not cause errors in building the manual.

### For all pull requests:

* [X] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [X] I have tested my new feature locally to ensure it is correct.

### CODE REVIEW

**Review by gassmoeller — COMMENTED** [review]
All the moved benchmarks look fine, but can you explain more why the parameter files in the `compositional_fields` directories cause a problem? I can see that they are now reachable from doc/ which they were not before, but why is that a problem?

**Comment by sac-bsa** [comment]
It became a problem as make finds the parameter files in the `compositional_fields` directories to be required to build the manual as part of `aspect-cookbook-prms` and `aspect-cookbook-prms-out`. The rules of the Makefile as currently in main tried to generate `cookbooks/benchmarks/solkz/compositional_fields/doc/solkz_compositional_fields.prm.out` while no `cookbooks/benchmarks/solkz/compositional_fields/doc` directory exists and additionally such a file would not be used for documentation. If I understand the Makefile correctly, once all the cookbooks (and benchmarks) are moved, all of the parameter files that we actually need `.prm.out`s for will be in `aspect-doc-prms`.

**Comment by gassmoeller** [comment]
Ok, thanks for the explanation. I was just worried that we will need to add lots of extra cases to the Makefile whenever we have benchmarks with different subdirectories, but let's face that when it actually happens.

**Pull request merged**
