### PR TITLE
Rename initial conditions plugins, namespaces, subsections

### PR DESCRIPTION
**Pull request by gassmoeller**
This is a follow-up and extension of #1449 to the initial condition plugins. There are two complications compared to #1449:
- The `initial_composition/interface.cc` functions use the same (wrong) doxygen groups and function names as `initial_conditions/interface.cc`, therefore the script was not able to rename them automatically. Everything within the `Interface` class and plugins is fine, I just had to change the non-member functions `register_initial_conditions` and similar by hand. Thus, the script should be fine for user plugins.
- The parameter file subsections were not named appropriately so I had to create a script to update parameter files, and update all of the bundled parameter files. Luckily the change is simple, just a renaming of the subsection `Initial conditions` and `Compositional initial conditions`.

This PR should probably be merged together with #1449. I do not care whether these two are merged first, or (#1038 and #1447), I just want to merge them pair-wise to avoid too many conflicts.

### CODE REVIEW

**Comment by bangerth** [comment]
Can you rebase after merging #1449 (to get rid of the extra commits) and squash the commits that only indent something with the commits they indent?

**Comment by gassmoeller** [comment]
Done. I just now realize that it will be probably atrocious to review the squashed commits. All changes in the .prm files are repetitive. It is likely a good idea to simply look for .cc and .h files, and the ones within doc/.

**Comment by bangerth** [comment]
Yes, not much to see here :-)

OK from my side to merge, but the 8.5 tester fails: http://www.math.clemson.edu/~heister/cib/aspect-8.5-gcc-hd/f80957d95b8bbdf311526cb28ca78aeabe337dd2/log-gcc . Do you know what is going on?

**Comment by gassmoeller** [comment]
Well the 8.5 tester is currently running with the 8.4 results, so that is not surprising. I will go ahead and merge.

**Pull request merged**
