### PR TITLE
unit_tests: convert tests/additional_output.prm

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by tjhei** [comment]
oops, broke 2 tests. Will get back to this...

**Comment by bangerth** [comment]
I guess we have a whole bunch of these kinds of tests. Is that worth anyone's time to convert them?

**Comment by tjhei** [comment]
> I guess we have a whole bunch of these kinds of tests. Is that worth anyone's time to convert them?

We have 11 of those. This is not too much work and will serve as an example for future unit tests, I think. It is also a way to learn how to write tests like this.

**Comment by tjhei** [comment]
this is ready!

**Comment by gassmoeller** [comment]
This is correct!

**Pull request merged**
