### PR TITLE
Cleanup unused variables

### PR DESCRIPTION
**Pull request by gassmoeller**
Easy part of #1275.

### CODE REVIEW

**Comment by bangerth** [comment]
OK to merge if it compiles. Did we not even initialize these variables in the `.cc` file?

**Comment by gassmoeller** [comment]
No, I think we removed them quite a while back (when we introduced `compute_material_model_input_values`), and forgot to remove them from the header.

**Comment by bangerth** [comment]
Woops :-)

**Comment by bangerth** [comment]
Hm, it doesn't compile: http://www.math.clemson.edu/~heister/cib/aspect-8.4.1/2be0445b33546ad49c03a32f4cf9e7125e295c03/log-clang

There were apparently places that still initialized these variables.

This may be more complicated to do separately from #1275. I'll leave it up to you whether you want to add the deletion of the initializations in this patch, or want to roll it all into #1275 after all.

**Comment by gassmoeller** [comment]
The lesson is: Never assume you remember what you did 2 weeks ago :smile:. Anyway, fixed, and you merged faster than I could write this comment.

**Comment by bangerth** [comment]
I hope this doesn't create undo merge conflicts with the rest of your work.

**Pull request merged**
