### PR TITLE
Require deal.II 9.3.

### PR DESCRIPTION
**Pull request by bangerth**
Might as well at this point.

There are a number of references to docker and container images in the manual and other files:
```
./contrib/docker/docker/Dockerfile:FROM tjhei/dealii:v9.2.0-full-v9.2.0-r2-gcc5
./contrib/release/release-tasklist:            tjhei/dealii:v9.2.0-full-v9.2.0-r2-gcc5 /bin/bash
./contrib/release/release-tasklist:- New: ASPECT now requires deal.II 9.2.0 or newer.
./contrib/ci/Dockerfile:FROM tjhei/dealii:v9.2.0-full-v9.2.0-r2-gcc5
./benchmarks/solkz/output/log.txt:--     . using deal.II 9.2.0-pre (master, d4815f3c75)
./.github/workflows/linux.yml:        sudo add-apt-repository ppa:ginggs/deal.ii-9.2.0-backports
./.github/workflows/linux.yml:        sudo add-apt-repository ppa:ginggs/deal.ii-9.2.0-backports
./doc/manual/manual.tex:docker pull tjhei/dealii:v9.2.0-full-v9.2.0-r2-gcc5
./doc/manual/manual.tex:  tjhei/dealii:v9.2.0-full-v9.2.0-r2-gcc5 bash
./doc/manual/manual.tex:    tjhei/dealii:v9.2.0-full-v9.2.0-r2-gcc5 \
```
We need to update these as well, but I don't know what to.

### CODE REVIEW

**Comment by tjhei** [comment]
Did you see #4093 and #4103 ?

**Comment by bangerth** [comment]
I had missed #4093. I guess this PR is a superset of #4093. I know that we need to have #4103 first, but had a couple of minutes and thought I'd give the topic a push :-)

**Comment by bangerth** [comment]
Do I need to rebase this now?

**Comment by tjhei** [comment]
Please do!

**Comment by bangerth** [comment]
OK, here we go!

**Review by tjhei — APPROVED** [review]

**Pull request merged**
