### PR TITLE
add comments, rename variables in vep-related rheologies

### PR DESCRIPTION
**Pull request by bobmyhill**
This PR adds several more comments and renames a number of variables to clarify how the VEP rheology works. There should be no change in functionality.

* [x] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.
* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).
* [x] I have tested my new feature locally to ensure it is correct.

### CODE REVIEW

**Comment by bobmyhill** [comment]
Test diffs look negligible, but should be zero if the plastic damper is inactive.

**Comment by bobmyhill** [comment]
Test diffs look negligible, but should be zero if the plastic damper is inactive.

**Review by bangerth — APPROVED** [review]
Nice job. Do you know which part of the patch caused the small changes in output?

**Comment by bobmyhill** [comment]
@bangerth, yes, the change is in the change from

`        const double strain_rate_effective_inv = 1./(2.*effective_strain_rate);`
`        double plastic_viscosity = yield_stress * strain_rate_effective_inv;`

to
`        double apparent_viscosity = yield_stress / (2. * effective_strain_rate);`

Surprising!

**Pull request merged**
