### PR TITLE
Removed Interface Compatibility.

### PR DESCRIPTION
**Pull request by alarshi**

### CODE REVIEW

**Comment by gassmoeller** [comment]
Looks good. Please run astyle. Ask somebody (e.g. me) if you need help with that.

**Comment by alarshi** [comment]
Thank you! I forgot to include the benchmarks folder when I ran astyle.

**Comment by bangerth** [comment]
@alarshi : In the build directory, you can just do `make indent` and it will indent all relevant files.

In the source directory, you can also do `./doc/indent` and it will do the same.

**Comment by alarshi** [comment]
Addresses #1538.

**Pull request merged**
