### PR TITLE
Particle benchmarks and particle interpolation schemes [WIP]

### PR DESCRIPTION
**Pull request by hlokavarapu**
Includes the following features:

- Added bilinear and biquadratic least squares method as particle property interpolation schemes
- Added overshoot and undershoot correction of particle properties using DGBP method
- Added SolCx, SolKz, and Inclusion benchmarks with particle interpolation
- Added SolCx, SolKz, and Inclusion benchmarks with compositional fields

Contributed by A. Kaloti (@aaronistheman), J. Jiang (@jonny97), Harry Levinson, Ngoc Nyguen (@ngocng05), @yinghe616, @egpuckett, and myself.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Wow that is a lot of code :smile:. Would it be possible to split this into several separate PRs (e.g. the four points you mentioned above)? This would simplify the review, and we could also merge the uncomplicated parts faster.

**Comment by hlokavarapu** [comment]
Fair enough, we will split these into independent pull requests.

**Comment by egpuckett** [comment]
Harsha, 

I'm concerned that the biquadratic interpolation algorithm is not working; i.e., it fails to converge (reduce the error) at h = 1 / 256 for SolKz and SolCx.

René: Should we 'Pull' this interpolation algorithm into ASPECT and then open an issue, which means we might have more 'eyes' examining the problem. Or should we keep working on it and not make a PR until it's working properly?

- Gerry

**Comment by gassmoeller** [comment]
I am always in favor of opening pull requests early, that allows to include comments as early as possible (it makes changing things much simpler and less painful). Just open a set of pull requests, and if there are still things to address than we can keep that one open for a while. Looking forward to having this functionality in :smile:

**Comment by bangerth** [comment]
@egpuckett -- to your question: it is always useful to open a *pull request* to get more eyes onto the problem. But it is usually not a good strategy to *merge* pull requests of which we know there are bugs because (i) people start to use things as soon as they are merged, (ii) there is a tendency to move on to other things, rather than fix stuff.

So I'd prefer not merging functionality that we don't know is entirely correct.

**Pull request closed without merging**
