### PR TITLE
Use MaterialModelInputs<dim>::reinit() where appropriate.

### PR DESCRIPTION
**Pull request by ian-r-rose**
This uses the new MaterialModelInputs<dim>::reinit() function of @pmbremner in a bunch of places.

### CODE REVIEW

**Comment by bangerth** [comment]
/run-tests

Not all of these places fill all variables, but they will do so now. This may not be what is intended. Specifically, filling the strain rate implies having to compute the viscosity -- which is often expensive. Thoughts?

**Comment by ian-r-rose** [comment]
Yes, that is a point of contention. I think that the assumption that only viscosity depends on strain rates is not necessarily a good one, and would advocate deprecating it. It would not be hard to add a `bool` flag to toggle whether to fill the strain rates, which would kick the can on that particular discussion. cc @tjhei @bobmyhill

**Comment by tjhei** [comment]
> Yes, that is a point of contention. I think that the assumption that only viscosity depends on strain rates is not necessarily a good one

We should discuss.

**Comment by bobmyhill** [comment]
I'm on @ian-r-rose's side.

**Comment by bobmyhill** [comment]
(but yes, we should discuss!)

**Comment by ian-r-rose** [comment]
I have restored the ability to select whether or not to compute strain rates, so this should be good to go.

**Comment by bangerth** [comment]
Outstanding -- thank you! Feel free to open an issue to discuss the question of not always computing the viscosity/not always passing the strain rate.

**Pull request merged**
