### PR TITLE
Make WB options private. Honor additional flags.

### PR DESCRIPTION
**Pull request by gassmoeller**
An attempt at fixing #5630. Inside the Jenkins tester we always want to disable '-g' and enable '-O3', but the rework of the CMakeLists.txt in #5621 broke that. Setting the target compile options to PRIVATE prevents the compile options for world builder to propagate to ASPECT, and adding the `ASPECT_ADDITIONAL_CXX_FLAGS` means the world builder will also use the same additional flags that ASPECT uses if they are set. Let's see if this fixes the timeout in the Jenkins tester.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Looks like this fixed the issue. At least the Jenkins tester is now beyond the build stage where it timed out before. If the testers succeed for this PR it should be good to go, and should finally bring us back to a working test system.

**Comment by tjhei** [comment]
Fascinating. Without PRIVATE everything gets the -g flag? Crazy.
Why does the test output change?

**Comment by gassmoeller** [comment]
As far as I understand with PUBLIC every target that links to the target with the PUBLIC property adds the same flags, with PRIVATE only the World Builder target adds the flags, but not targets that link to it. Since for ASPECT we want to use the same flags as deal.II, we do not want the world builder options to propagate to the ASPECT target and potentially overwrite the deal.II options.

I think the test output changes, because for the tests we add ASPECT_ADDITIONAL_CXX_FLAGS='-O3' to make the tests run faster in debug mode. However, the current setup on main does not propagate this -O3 to the world builder target. With this change it does add ASPECT_ADDITIONAL_CXX_FLAGS to the world builder target options and -O3 apparently changes the output slightly.

I am only beginning to understand this whole cmake options system myself, but at least for now this seems to work.

**Comment by tjhei** [comment]
Okay, makes sense!

**Review by tjhei — APPROVED** [review]

**Pull request merged**
