### PR TITLE
Add signaling nan unsigned int for tracers

### PR DESCRIPTION
**Pull request by gassmoeller**
This is a simple part of #411

### CODE REVIEW

**Comment by tjhei** [comment]
I can not see how there can be a signaling int. What is the purpose of this?

**Comment by gassmoeller** [comment]
Ah you are right, I did not know enough about signaling_nans, simply assumed I could use it like this, but it turns out `signaling_nan<unsigned int>` is simply 0. I am using `parallel::distributed::Triangulation::register_data_attach` and `notify_ready_to_unpack`, and need to store the data_offset return value. For notify_ready_to_unpack I need to find out, if something was stored, and if so, unpack it. However, I can not simply check `if (data_offset != 0)`, because that is a valid value for data_offset. And the condition under which I call register_data_attach has changed, when I call notify_ready_to_unpack, so I can not use that either. It seems I need to use a new bool, something like `data_was_stored`. In that case we can close this PR

**Comment by tjhei** [comment]
Just use something like ```dealii::numbers::invalid_unsigned_int```

**Comment by gassmoeller** [comment]
Works. Thanks :+1:

**Pull request closed without merging**
