### PR TITLE
Add a max temperature constraint in fixed temperature within compositional field plugin

### PR DESCRIPTION
**Pull request by danieldouglas92**
Pull Request Checklist. Please read and check each box with an X. Delete any part not applicable. Ask on the [forum](https://community.geodynamics.org/c/aspect) if you need help with any step.

*Describe what you did in this PR and why you did it.*
Added a control of the plugin which fixes the temperature within a compositional field. This control also allows the fixing of all temperatures below a user specified maximum value of temperature.

### Before your first pull request:

* [x] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [x] I have tested my new feature locally to ensure it is correct.
* [x] I have [created a testcase](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Review by gassmoeller — APPROVED** [review]
Looks good. I guess this is just a test of functionality for another model? It is still good to have as example.

**Comment by danieldouglas92** [comment]
This is an additional test for adding functionality to an existing model. The jenkins tested passed again yesterday but now it's pending once more, not sure what's going on with that!

**Comment by gassmoeller** [comment]
Sometimes it just takes a while. Ready then.

**Pull request merged**
