### PR TITLE
Adding a cookbook illustrating periodic boundaries

### PR DESCRIPTION
**Pull request by Geoniette**
Added periodic side boundaries in x and extended the model width from 1 to 5

### CODE REVIEW

**Comment by tjhei** [comment]
Did you talk to someone about this PR? I am a bit confused what you are trying to propose here. I think we already have ``./cookbooks/future/periodic_box.prm``, which is similar to this file, right?

**Comment by Geoniette** [comment]
> Added periodic side boundaries in x and extended the model width from 1 to 5



> Did you talk to someone about this PR? I am a bit confused what you are trying to propose here. What are you trying to do? I think we already have `./cookbooks/future/periodic_box.prm`, which is similar to this file, right?

No actually I hadn't spoken to anyone about this. I just saw it as one of the starter projects options and I implemented it. I was going to follow this up with the cookbook which is also listed as a starter project but if this has already been done I'll pick something else :)

**Comment by anne-glerum** [comment]
Could you add the number of the issue to your first comment here for reference to the starter project?

**Comment by Geoniette** [comment]
Sure! I just cannot do that for this PR specifically because as I cannot find the project on the list anymore and I don't remember it from last night. Sorry! I'll make sure to take note of the issue number next time

**Comment by jdannberg** [comment]
Issue #2904

**Comment by gassmoeller** [comment]
Hi @Geoniette, let's have a chat first about how to address this issue best. I think an extension to the convection box cookbook that explains periodic boundaries and the challenges related is a good idea, but that would also need some additional text, and we have a cookbook under `future/periodic_box.prm` that does part of that already. I think we can use `periodic_box` as a basis to create an extension for convection-box, but it will be a bit of work and I wanted to make sure this is something you are willing to put some more time into after the hackathon. The necessary steps would be:
1. Settle on a parameter file (probably a cleaned up version of future/periodic_box.prm)
2. Settle on a name for the cookbook.
3. Find a place in the manual for some text about periodic boundary conditions and the challenges involved.

Let us know how you feel about the issue.

**Comment by bangerth** [comment]
@Geoniette and @gassmoeller -- did you discuss how to move forward with this? How can I help?

**Comment by Geoniette** [comment]
Yes we did thanks! I'll be getting to it this week!

**Comment by bangerth** [comment]
@Geoniette I'm going through some old pull requests. Do you have any news about this one?

**Comment by Geoniette** [comment]
@bangerth no I haven't gotten to it just yet! Sorry!

**Comment by bangerth** [comment]
OK, no problem. Let us know when you want us to look at this again!

**Comment by gassmoeller** [comment]
We now have a cookbook illustrating periodic boundary conditions (#4468) and because this PR so far only contains a parameter file but no documentation text that would add something over the other cookbook I would propose to close this for now. Future contributions are of course always welcome :-)

**Comment by Geoniette** [comment]
That makes sense! Thanks for keeping me in the loop

**Pull request closed without merging**
