### PR TITLE
always print cheap Stokes solver iterations

### PR DESCRIPTION
**Pull request by bjs2**

### CODE REVIEW

**Comment by tjhei** [comment]
This change is based on my suggestion, because I got confused when we were looking at output and we couldn't tell if "X iterations" meant cheap or expensive iterations.

I assume we need to fix a lot more of those tests...

**Comment by bangerth** [comment]
The patch is ok if you fix the failing tests (e.g., by further adapting the script that filters/processes output before comparing).

**Comment by bjs2** [comment]
Here's the timesheet. Even though I entered 1.67 hours on that last
Thursday, it still shows it as 1.75.

**Comment by tjhei** [comment]
okay, tests are passing.

**Pull request merged**
