### PR TITLE
Remove deal.II 8.4.0 compatibility

### PR DESCRIPTION
**Pull request by zarestky**
This PR removes ifdef-ed code for deal.II 8.4.0, which we no longer support.

### CODE REVIEW

**Comment by zarestky** [comment]
... and happy birthday!

**Comment by tjhei** [comment]
You mean /run-tests ?

**Comment by bangerth** [comment]
@tjhei -- I did.

@zarestky -- well, this was a nice surprise. I always knew you had the hacker gene in you. I feel soo connected to you now that you've finally started to move back from those softie sciences to what *real* scientists do! ;-)

**Pull request merged**
