### PR TITLE
implement timestep repeating with mesh deformation

### PR DESCRIPTION
**Pull request by tjhei**
We forgot to undo mesh deformation when we repeat a timestep. Fix that.

### CODE REVIEW

**Comment by tjhei** [comment]
@EstherHeck it took me way too long, but this might work. Can you check?

**Comment by EstherHeck** [comment]
Hi @tjhei, thanks for getting back to this! I tried it with the free surface tractions benchmark and indeed it works. When I set the maximum relative increase parameter, I do get the same magnitude of surface movement as in the analytical solution! See more detail in #3770

**Comment by tjhei** [comment]
> and indeed it works

Awesome, thank you for checking!

**Comment by tjhei** [comment]
I think this is ready to go.

**Review by gassmoeller — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
