### PR TITLE
Clean up some places handling initial topography in geometry models.

### PR DESCRIPTION
**Pull request by bangerth**
The goal is to make them all look the same: They all should be handling their manifold objects the same way, for example -- create them in the same places, copy them the same way, have key member variables in the same order, etc.

### CODE REVIEW

**Comment by bangerth** [comment]
Related to #5421.

**Comment by bangerth** [comment]
That failing CI check is the same 18 tests that always fail.

**Comment by bangerth** [comment]
See #5504.

**Review by gassmoeller — APPROVED** [review]
Thanks for the cleanup :+1:

**Pull request merged**
