### PR TITLE
enable tests that require deal.II 9.2

### PR DESCRIPTION
**Pull request by tjhei**
part of #3582

### CODE REVIEW

**Comment by tjhei** [comment]
this will interfere with the changes in #3532, so we need to be careful.

**Comment by gassmoeller** [comment]
Do you want me to wait with this until #3532 is resolved?

**Comment by tjhei** [comment]
Either way. We just need to make sure that we rebase. Maybe we wait with this for Conrad.

**Comment by gassmoeller** [comment]
Since #3532 seems to be needing another pass lets merge this to get it out of the way.

**Pull request merged**
