### PR TITLE
Newton Stokes failing for a linear problem

### PR DESCRIPTION
**Pull request by tjhei**
This currently failing test is a linear problem, so the second nonlinear
iteration should do 0 iterations (and does when you use "single
Advection, iterated Stokes") but it crashes with the Newton solver because the Stokes solver is not
converging. It looks like we try to reduce the residual to 1e-20, which
won't work.
The test passes if you remove "set Linear solver tolerance".

### CODE REVIEW

**Comment by tjhei** [comment]
@MFraters what do you think is happening here?

**Comment by MFraters** [comment]
I have some idea's which can explain it, but I need to take a closer look at what the code exactly does. Will come back to this later today.

In general, you want to use a much looser tolerance for the Newton (or defect correction Stokes) solver then you would use for the full stokes solver.

**Comment by MFraters** [comment]
So the relevant lines are in solver.cc around 781. I don't remember entirely why it is different, but I think it comes down to that a defection correction system is setup differently and therefore requires a different (less strict) tolerance. One important difference could be the initial guess used by the linear solver. The Newton solver simply sets the guess solution vector to zero, while the normal linear solver guess is a bit more complicated.

**Comment by bangerth** [comment]
I think the criterion should be: If the nonlinear residual in iteration 2 is vastly smaller than in iteration 1 (e.g., because the problem is linear), then skip the solve.

**Comment by MFraters** [comment]
> I think the criterion should be: If the nonlinear residual in iteration 2 is vastly smaller than in iteration 1 (e.g., because the problem is linear), then skip the solve.

I don't really understand what you are proposing here. The linear solver is crashing in nonlinear iteration 2, so we never know what the residual is from nonlinear iteration 2.

**Comment by bangerth** [comment]
I was talking about the nonlinear residual, so the norm of the right hand side. If the norm of the rhs in iteration 2 is vastly smaller than the norm of the rhs in iteration 1, then the model is linear and we should not run the linear solver after assembly (or only run it with a very loose tolerance).

**Comment by MFraters** [comment]
ah, I now understand. We would need to check that in the `assemble_and_solve_defect_correction_Stokes` function at about line 442 in solver_schemes.cc. Most of the information is already computed for nonlinear iteration > 1, so it would be a small change. I could make a seperate pull request but I am also fine with @tjhei changing it if he wants to.

**Comment by bangerth** [comment]
Yes, right: The check needs to be right after `assemble_stokes_system()`. If the norm of the rhs is much smaller than it was in the previous iteration, then you can skip the solution of the linear systems, set the update to zero, and skip the line search stuff.

**Comment by tjhei** [comment]
This has been merged as part of #3787

**Pull request closed without merging**
