### PR TITLE
Update visco_plastic material model test suite

### PR DESCRIPTION
**Pull request by naliboff**
Pull request to simplify the visco_plastic material model test suite. The current test input files are unnecessarily complicated, as they were originally designed to also provide a template for continental extension.  The new test suite should be much easier to debug and modify in the future if necessary.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Did the old test cause problems (like false-positives)? Otherwise there is not much wrong with having complicated testcases, it tests more complicated code paths, which is a nice thing to have. 

There is also not much wrong with having simple testcases, which are easier to debug, when issues show up. Therefore as long as the old test did not cause issues, I would be in favor of adding your new test as an additional test setup (maybe 'visco_plastic_simple'?). 

Or did you just remove input sections that did not do anything at all? But why did the results change in that case?

**Comment by naliboff** [comment]
@gassmoeller - I both removed sections that did nothing, simplified the problem (isothermal, no compositional fields/only background material) and changed the boundaries from free-slip to a prescribed velocity.  Certainly much easier to read, debug and modify now, plus the velocities are derived from the boundary conditions rather than default values (initial strain rate, min strain rate, etc).

However, point taken about complicated tests being useful. How about keeping the new versions of the tests, but adding a single "complicated" test based on the prior test models?

**Comment by bangerth** [comment]
> However, point taken about complicated tests being useful. How about
> keeping the new versions of the tests, but adding a single "complicated"
> test based on the prior test models?

Yes, more tests are more better.

**Comment by gassmoeller** [comment]
Sure, I do not mind if we keep the old test and add a new one, or move the old one to a new name and add the new one. Just modify the PR in one way and let me know.

**Comment by naliboff** [comment]
@gassmoeller - I added a new test that contains much of the complexity (temperature field, composition stratification, non-linear flow law) of the prior test suite.  Happy to continue modifying or adding tests if needed.

**Comment by gassmoeller** [comment]
looks good :+1:, thanks for cleaning up. Lets see what the tester says.

**Comment by gassmoeller** [comment]
@tjhei is the aspect-8.4.1 tester stuck? This PR is queued since yesterday.

**Comment by gassmoeller** [comment]
It looks like one of the testers got stuck (it is working again for newer pull requests), so because this is a simple pull request and all other testers have succeeded I will merge this as is. Thanks for the work :+1:!

**Pull request merged**
