### PR TITLE
add citing_aspect.bib

### PR DESCRIPTION
**Pull request by tjhei**
This file is manually exported from the mendeley ASPECT group and
updated regularly. It is used to generate
https://aspect.geodynamics.org/publications.html

### CODE REVIEW

**Comment by bangerth** [comment]
Are we doing anything with this file at the moment?

**Comment by jdannberg** [comment]
What do you mean? As far as I understood what @tjhei wrote, the webserver uses this file to create the publications website (link above).

**Comment by tjhei** [comment]
> As far as I understood what @tjhei wrote, the webserver uses this file to create the publications website (link above).

correct.

**Comment by gassmoeller** [comment]
Can you update the link in the section 'Referencing ASPECT' of the manual to point to this website? No more comments from my side, feel free to merge when @bangerth is ok with it.

**Comment by tjhei** [comment]
> Can you update the link in the section 'Referencing ASPECT' of the manual to point to this website?

sure, see #1905

**Pull request merged**
