### PR TITLE
visualize undeformed mesh and mesh displacement

### PR DESCRIPTION
**Pull request by tjhei**
The graphical output of a computation with mesh deformation can now be optionally done on the undeformed reference mesh ("set Output undeformed mesh = true") and the displacement can be written as a separate vector field ("set Output mesh displacement = true").

### CODE REVIEW

**Comment by tjhei** [comment]
@naliboff FYI

**Comment by tjhei** [comment]
Hi @naliboff, does that make sense to you?

**Review by gassmoeller — APPROVED** [review]
Looks very nice! Ready to go from my side, but I will let @naliboff have the last word on it.

**Comment by tjhei** [comment]
@naliboff ?

**Comment by gassmoeller** [comment]
Let's merge. We can always change it later if necessary.

**Comment by tjhei** [comment]
Thank you. I guess @naliboff is busy with other stuff. 😉

**Pull request merged**
