### PR TITLE
[WIP] Melt visco plastic material model

### PR DESCRIPTION
**Pull request by naliboff**
Placeholder for accepting changes for a work-in-progress melt_visco_plastic material model.

### CODE REVIEW

**Comment by naliboff** [comment]
@jdannberg @anne-glerum  - At some point before the hack I'm going to rebase and cleanup outdated code/files. I'm also thinking about adding in viscoelasticity so we can reproduce more of the Keller et al. benchmarks with and without melt. Any objections?

**Comment by jdannberg** [comment]
I would first try to find a test case with an analytical solution for just the viscoplastic case before we make this material model more complicated. If we need elasticity in many more models, we should also think about a way to move it to a separate location to not duplicate the code...

**Comment by naliboff** [comment]
Sounds good. For these complicated material models it would be nice to have a way to compute the viscoelastic without reduplicating code.

The viscoelastic effects need to be computed after the background viscosities (linear, diffusion, dislocation, etc), but before yielding. In this sense, it almost needs to be treated as a function, rather than a 'compositing' material model like` depth_dependent`.

I suppose the same applies for different viscosity laws and yielding mechanisms. Is there a way to generalize all of this so that we can mix and match different constitutive properties easily? The downside to this approach is it may be easier to make choices that are not self-consistent. 

I recall @gassmoeller outlining some ideas for reusing code in the material models, but not the specifics. Something to discussing during the next maintainer meeting?

**Comment by naliboff** [comment]
@jdannberg, @anne-glerum - I'm closing this pull request for now until I've finished reworking the code and testing features. 

Lots of small commits related to fixing bug fixing reorganization coming soon, and there is no need to push those to an open PR. Most of these commits will be squashed later on for review purposes.

Once a few of the benchmarks are passing I'll reopen the PR, but all of the commits will still get pushed to the same branch.

**Pull request closed without merging**
