### PR TITLE
[WIP] Free surface and prescribed velocity boundary conditions on the vertical boundaries

### PR DESCRIPTION
**Pull request by anne-glerum**
After talking to Sascha who is working with @gassmoeller, I have run some simple 2D models looking at the behaviour of the free surface with a free slip boundary condition on the right vertical boundary. I specified this condition either by listing the boundary under "Tangential velocity boundary indicators" or under "Prescribed velocity boundary indicators" while only prescribing the x-component of velocity to be zero and leaving the vertical component free. The behaviour of the right corner point of the mesh is different (vertical movement vs no movement), I think because the "mesh_displacement_constraints" are set to zero for prescribed velocity boundary conditions. It is not taken into account that not all velocity components need to be prescribed. I've added a few lines such that in 2D vertical motion along the vertical boundary is allowed, but I'm not sure this is the best way to do it and I don't think it covers all combinations of prescribed/free velocity components and boundaries. I'm not very familiar with the free surface yet, so I'm looking for input from @ian-r-rose on this :)

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Can you confirm that using `Tangential velocity boundary indicators` works as expected? In that case the vertical boundary should allow vertical motion of the mesh.

You are correct that when the B.C. is set to prescribed, we just fix the mesh constraints on that boundary (what I had in mind there was something more like what is done in your crustal deformation cookbook).  I suppose this is too restrictive for the case you describe, and tangential boundary conditions would be more appropriate.

I am a little uncomfortable with this parsing of the boundary indicator strings. It seems fragile and not easy to generalize to other geometry models. Another option would be to have an optional setting in the `Free surface` subsection which allows for manual overriding of this default behavior for prescribed boundary indicators. This could be something like 'Tangential mesh constraint boundary indicators` (or something clearer than that, I don't know).

Do you have some images that illustrate what you are talking about, just so I am sure that I understand?

**Comment by anne-glerum** [comment]
Using `Tangential velocity boundary indicators` works as expected. 

Below are two snapshots of the right upper corner of a rectangular domain with a hot blob rising along the right vertical boundary. The boundary condition on the right vertical boundary is free slip, only in the left image it is specified using `Tangential velocity boundary indicators`, while in the right image using `Prescribed velocity boundary indicators`. In green the original outline of the rectangular domain.

The left image shows that the right upper corner point of the mesh has moved upward, while it has remained fixed in the right image. So, when using `Prescribed velocity boundary indicators`, the mesh is fixed, even though vertical movement is expected in this case.

grid_free_surface_corner_point

I agree that the x,y,z selectors are not easily generalized. When selecting velocity components for `Prescribed velocity boundary indicators` in the input file, one can select the actual x, y (and z) components of the velocity. So one cannot, for example, select the component of velocity that is tangential to the surface of a shell. I guess for spherical geometries, prescribing certain components and leaving others free is therefore only useful on boundaries aligning with the x,y(,z) axes. For, say, a 2D shell with a 90 degrees opening angle, the right vertical boundary would align with the x-axis, and the vertical component of the velocity would be the x-component, instead of the y-component. In this case a manual override to free slip for the right boundary would work well. 

What if, for a 3D box, the x and y components of velocity are prescribed on a vertical boundary parallel to the y-axis, but we want to leave the z-component free: should both the x- and y-components of the mesh constraints be set to zero?

**Comment by bangerth** [comment]
If I read this right, it's only about the one point. The problem I see is that we don't assign boundary indicators to points (because that is mathematically not sound), only to faces. So if you have two different boundary indicators for the two faces that come together at that point, the question is "who is going to win" because both are (or may be) setting constraints on the degrees of freedom on the vertex where they meet. In some cases, the end result will be different depending on the order in which you go over these faces. Is this a correct reading of the problem?

**Comment by gassmoeller** [comment]
@bangerth: I was just following the discussion superficially, but I think it is different from your description. In the current state we fix all components of the mesh movement at the side nodes, if the side is in the prescribed_boundary_indicators list, even if only the lateral velocity components are prescribed and the vertical is free  (is that a correct summary @anne-glerum?). Therefore the free surface code needs to check 'if the vertical velocity component is prescribed' instead of 'if any velocity component is prescribed', but sometimes it is hard to figure out what 'vertical' actually means (e.g. for a 90 degree shell there are 2 different directions depending on the boundary, and for the 3d box it is a different direction than for the 2d box).

**Comment by ian-r-rose** [comment]
Sorry, checked out of this discussion for a few days. 

I think you are correct @gassmoeller, it is pretty difficult to cover all the edge cases where this might come up. The end result is that in some cases the runs that @anne-glerum wants to do involve these mixed boundary conditions where a more appropriate constraint on the mesh displacements are tangential rather than zero displacement.

My current thinking is that in this case, rather than make further guesses about what the user wants in these cases, we could just specify a new parameter (something like `Additional tangential mesh constraint indicators`) so that the user can override the best guess as to the appropriate mesh constraints.

**Comment by anne-glerum** [comment]
@gassmoeller your summary is correct, thanks. @ian-r-rose specifying a new parameter is fine with me, what do you think @bangerth ?

**Comment by bangerth** [comment]
I'm ok with the additional parameters, though I also think that it should be possible to also parse the constrained velocity boundary indicators.

But thinking outside the box: Would it be useful to *completely* decouple the boundary condition interpretation of the velocity field and the mesh velocity field? In other words, introduce parameters for the *all* kinds of mesh velocity boundary conditions that the user would then have to specify?

**Comment by bangerth** [comment]
What's the status of this now that #701 has gone in?

**Comment by gassmoeller** [comment]
I think this can be closed, but I will leave it to @anne-glerum to close it, since it is her PR.

**Comment by anne-glerum** [comment]
#701 looks great, thank you all!

**Pull request closed without merging**
