### PR TITLE
Add new solver scheme: single advection, iterated Newton Stokes

### PR DESCRIPTION
**Pull request by anne-glerum**
This PR adds a new solver scheme to solve the advection equations only once per timestep, but do iterate out the solution of the Stokes equations using Newton iterations. It is very similar to the `iterated Advection and Newton Stokes` solver scheme. It therefore includes a lot of duplicate code; I've not looked at how to avoid this, suggestions welcome. Results for the added test are the same as for the `iterated Advection and Newton Stokes` solver in the original (`include`d) test.

### For all Pull Requests:

- [x] I have followed the instructions for indenting my code according to ASPECT's code style as described in the last paragraph of the ['Making ASPECT better'](../CONTRIBUTING.md#making-aspect-better) section of CONTRIBUTING.md.

### For Feature/Benchmark Submissions or Changes of Existing Behavior:

- [x] I have tested my new feature locally to ensure it is correct.
* [x] I have created a testcase for the new feature/benchmark in the [tests/](../tests/) directory as described in the corresponding section of the [manual](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests).
* [x] I have added a changelog entry in the [doc/modules/changes](../doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Comment by anne-glerum** [comment]
I don't understand the error message of the testers.

**Comment by anne-glerum** [comment]
Thanks @MFraters . 
- I've fixed the typo. 
- The CIG tester shows an error that I don't understand and was noticed by @gassmoeller in #3180 as well. 
- And just to clarify, the only difference between `solve_iterated_advection_and_newton_stokes` and `solve_single_advection_iterated_newton_stokes` is that the 2 advection solves are moved outside the loop. I'm glad #3109 will get rid of the duplicate code.

**Comment by gassmoeller** [comment]
Yes the CIG tester was failing for the last two days, should be back up now. @MFraters: if you want to merge this keep in mind that you then have to update #3109 accordingly to remove the duplication that is introduced here. Or should we merge #3109 first and ask @anne-glerum to update this PR? I am fine either way, I just want to make sure the duplicated code gets removed by somebody :wink:.

**Comment by MFraters** [comment]
@anne-glerum Great, looks good to me.

@gassmoeller Yes, I am fine with updating that pull request.

**Pull request merged**
