### PR TITLE
Make compile with gcc 4.8.4.

### PR DESCRIPTION
**Pull request by pmbremner**

### CODE REVIEW

**Comment by tjhei** [comment]
There is a bigger problem that might happen if we run with 64 bit indices. @bangerth I really don't like using the size of the linear system here. Would you be opposed to removing the ``min`` instead? I don't see a practical reason for having it in there.

**Comment by bangerth** [comment]
I don't see the point. If a user sets this number to 100,000, the size of the linear system is 1,000 but happens to be singular, then we're going to do 100,000 iterations. There is no point in this.

Why would it *ever* make sense to run more iterations than the size of the linear system?

**Comment by gassmoeller** [comment]
Well I suppose the question is, when would you ever run a model with a maximum number of Stokes iterations larger than the number of degrees of freedom? Surely there are a few example models with less than 1000 degrees of freedom (the default for the parameter), but they will definitely converge in less than 1000 iterations, and if not, they are not going to converge ever. So @tjhei's point is only that this min call is not helping for any model, and it creates more trouble than it helps to resolve.

**Comment by bangerth** [comment]
What is the *trouble* with the `min`, other than the fact that it currently doesn't compile?

**Comment by gassmoeller** [comment]
Nothing specific, only that it adds an additional source for errors, and it is hard to understand. For example there are several things in this call that are not even clear to me: Why are we calling some function m() of the matrix blocks(what does that even do?) and not use the size of the right-hand-side vector? Why do we have to add m() from the matrix block `block_vel,block_p` and `block_p,block_v`? I am aware we need to add the #Dofs for pressure and velocity, but would that not be possible by adding `block_vel,block_vel` + `block_vel,block_p`? What happens if the two variables are in the same block, does that work? What do we do with this line when we (eventually) use a matrix-free method?

**Comment by bangerth** [comment]
`m()` is the number of rows of a matrix. So the sum of these two terms it's the same as the number of Stokes dofs. I don't really care how we compute things, just that we use it.

The velocity and pressure are only in the same block if we use a direct solver -- which is not the case we have here.

**Comment by bangerth** [comment]
Superseded by #1541.

**Pull request closed without merging**
