### PR TITLE
added Bob and Cedric to the list of maintainers/principal developers

### PR DESCRIPTION
**Pull request by bobmyhill**
Added me to the list of maintainers :)

### CODE REVIEW

**Comment by jaustermann** [comment]
You could also add Cedric to the list of Principal Developers in this same pull request.

**Comment by bobmyhill** [comment]
I was going to let @cedrict do that himself :) ... but I certainly can do this if he doesn't want this special Wednesday treat!!

**Comment by cedrict** [comment]
you have my blessing :)

**Comment by bobmyhill** [comment]
Done!

**Review by bangerth — APPROVED** [review]
It's an honor to approve of this PR!

**Comment by bobmyhill** [comment]
> It's an honor to approve of this PR!

Don't you mean honour?! ;)

**Comment by bangerth** [comment]
In this case, it is an honour indeed :-)

**Comment by bangerth** [comment]
Hurray!

**Comment by MFraters** [comment]
Nice! :tada:

**Pull request merged**
