### PR TITLE
Use consistent ParaView capitalization.

### PR DESCRIPTION
**Pull request by Djneu**
Changes to keep all capitalization of ParaView consistent.

### CODE REVIEW

**Comment by bangerth** [comment]
It's only in the manual. The tester will not uncover anything useful.

**Comment by anne-glerum** [comment]
@bangerth just testing our permissions :)

**Comment by bangerth** [comment]
@anne-glerum -- yes, you did the right thing. It's just that the tester doesn't check the creation of the manual, and so won't find anything about this PR. You couldn't know that.

**Pull request merged**
