### PR TITLE
Add a test for global topography on a chunk geometry.

### PR DESCRIPTION
**Pull request by bangerth**
NOT READY TO MERGE!

I took the `surface elevation` postprocessor from #5563 along with a file I got from @alarshi that has global topography on a 1-degree-mesh to see whether we can use the latter with the `chunk` geometry and superimpose realistic topographies. It works as far as getting things to run, but when I look at the output, I do not recognize what part of the earth this represents -- so I might need some help.

The test here centers the chunk geometry on zero longitude, zero latitude (a spot south of Ghana and west of Gabon, in the Atlantic). It extends to +/- 45 degrees in all four directions, which is north to France, west almost to Brazil , and east just beyond Somalia. (South is not very interesting from this spot.) This is terrain that is not without interest. Yet, when I look at the result of the test (outputting VTU instead of the GNUPLOT format we use for tests), I get this picture: 
image
This does not look like Africa and the Atlantic.

There are some more interesting areas to see when choosing a different part of the world for the chunk, but in the end, I recognize nothing. What am I doing wrong here? @alarshi @gassmoeller @everyone Help! :-)

In pursuit of #5421.

### CODE REVIEW

**Comment by bangerth** [comment]
For reference, this is what I get for the area just to the east of the picture above (from 45 to 135 degrees): 
image

This *should* be the Indian Ocean, but it is not something I can recognize.

**Comment by bangerth** [comment]
I think I understand now. In the input file @alarshi gave me, the first column is colatitude (0=north pole) and runs from -pi to +pi, with everything from -pi...0 having an elevation (depth) of -4355m. Actual data is only in the second half, 0...pi. The second column is longitude. The third is elevation.

@alarshi This doesn't match the header of the file,
```
# Test data for ascii data sea level-topography.
# Only next line is parsed in format: [nlongitude] [ncolatitude] because of keyword "POINTS:"
# POINTS: 180 90
# Columns: longitude (radian) colatitude (radian) InitialTopography[m]
-3.124146798593041119e+00 0.000000000000000000e+00 -4.355000000000000000e+03
-3.089142667575259793e+00 0.000000000000000000e+00 -4.355000000000000000e+03
...
```
and it doesn't match the convention for ASCII input files.

So in the best of cases, all I need to do is put a different input file in.

**Comment by alarshi** [comment]
@bangerth : I am really sorry! I sent you the updated file. I do not know how I even got to the previous topography file. :(

**Comment by bangerth** [comment]
All good! I updated the PR with the new file from @alarshi and now it all works! <3 Here is Africa:
image

So this is now good to go. I'll add that I took the liberty to add the data file. We can read `.txt.gz` files, so I added it in this compressed format where it is only 100 kB. That seemed like a manageable addition.

**Review by gassmoeller — APPROVED** [review]
Great to see how all the pieces come together :+1:

**Comment by bangerth** [comment]
Only took 15 PRs to get here :-)

**Pull request merged**
