### PR TITLE
Rework morency plugin

### PR DESCRIPTION
**Pull request by tjhei**
- rename to "Morency and Doin"
- do not parse model depth and n_compositional_fields from the ParameterHandler

### CODE REVIEW

**Comment by bangerth** [comment]
If you don't read parameters any more from the input file, you probably shouldn't declare them either. OK with that change.

**Comment by tjhei** [comment]
> make it const

fixed.

> If you don't read parameters any more from the input file, you probably shouldn't declare them either.

Sorry, I don't understand what you mean. Anything you want changed?

**Comment by bangerth** [comment]
I misread. You deleted lines that read input parameters, so I thought you should also delete the lines that declare them. I hadn't realized that you were reading parameters from sections that weren't declared in the plugin. So it all looks good to me. Please merge if you think everything is addressed.

**Comment by tjhei** [comment]
Ah, okay. 

>  I hadn't realized that you were reading parameters from sections that weren't declared in the plugin. 

where "you" is certainly not me. :-)

**Comment by jperryhouts** [comment]
> where "you" is certainly not me. :-)

Ha, sorry about that. Thanks for fixing this up.

**Pull request merged**
