### PR TITLE
VoF: add test for graphical output

### PR DESCRIPTION
**Pull request by tjhei**
none of the tests trigger graphical output of "volume of fluid values".
Fix this.

### CODE REVIEW

**Comment by tjhei** [comment]
test failed crashed before being based on #2848 and passes now. Ready to be merged, I think.

**Comment by gassmoeller** [comment]
Yes looks good. I guess it was on purpose that you did not add the binary output files? We could also choose to include low resolution gnuplot files to the test data. What do you think?

**Comment by gassmoeller** [comment]
Anyway this is better than before, so I am going to merge. Thanks!

**Comment by bangerth** [comment]
In reference to #835.

**Pull request merged**
