### PR TITLE
Remove assert because initial topo is incorporated into pull_back(point)

### PR DESCRIPTION
**Pull request by anne-glerum**
Related to #1952.

### CODE REVIEW

**Comment by MFraters** [comment]
Good one, I think you can also remove the include statement of the zero topography

**Comment by gassmoeller** [comment]
@mfraters: Just a bit of advice in regards to reviewing pull requests (also of interest to @naliboff and @jaustermann). It is often helpful to clearly state:
- What you think the status of this PR is (is it ready to be merged, ready to be merged with minor changes, requires major changes, or you ask for a more in detail discussion, if you think it does not fit at all).
- What is *required* to make this mergeable.
- What the initiator of this PR *can* do if he has the time (i.e. optional improvements).
- In case the initiator also has merge rights (as in this case) you can add a statement if she is allowed to merge herself after minor changes.
- Dont forget to thank them for their contributions :smile:

There are no rules about this structure of pull requests reviews, but I think they are helpful, because it tells people clearly where they are, and what is required. Of course you are free to write your reviews in a way that fits to you.

So in this case, you likely wanted to say: Good one, please also remove the include statement of the zero topography, and then merge yourself.

I should add that I am aware you and @anne-glerum would have figured that out yourself, I just thought I can play the know-it-all. Also over the last years I have seen several pull requests lie around for extended periods of time because of unclear reviews. In these cases the reviewer thought he had done his job, and the initiator of the pull request did not know how to proceed.

**Comment by MFraters** [comment]
@gassmoeller, thanks, good points. I will try to use those next time. I think she can merge it herself as soon as the include statement is removed and the tester is fine with it :)

**Comment by anne-glerum** [comment]
Thanks @gassmoeller those are good points! And yeey, my first merge :)

**Pull request merged**
