### PR TITLE
Increase limit for the number of inner iterations.

### PR DESCRIPTION
**Pull request by tjhei**
Rework of #234 hopefully fixing the test results. Let's see.

### CODE REVIEW

**Comment by tjhei** [comment]
Any volunteers to look over 9d359c8 and check if the changes are reasonable? :-)

**Comment by tjhei** [comment]
(tests pass except the 2 that fail because of the boundary condition fix not on mainline)

**Comment by tjhei** [comment]
Otherwise this seems to be ready to merge. Finally.

**Comment by bangerth** [comment]
I've looked at a good number of the differences and none seemed to affect the output quantities in much of a significant way -- only round-off, plus of course the number of iterations in many places. I think this looks pretty good. I take your statement as approval to merge? If so, please hit the button.

**Comment by tjhei** [comment]
Thanks, I came to the same conclusion.

**Pull request merged**
