### PR TITLE
Rename a variable in Simulator to make its intent clearer.

### PR DESCRIPTION
**Pull request by bangerth**
This is follow-up to #1495 and another patch addressing #1229.

### CODE REVIEW

**Comment by bangerth** [comment]
This is failing with the same error that @gassmoeller saw earlier today (and which I think is due to the tester). The issue is fundamentally that the file `tests/depth_postprocessor_box/solution/solution-00000.0000.gnuplot` has a time stamp in it:
```
# This file was generated by the deal.II library.
# Date =  2015/10/14
# Time =  20:44:53
#
# For a description of the GNUPLOT format see the GNUPLOT manual.
#
# <x> <y> <velocity> <velocity> <p> <T> <depth> 
0.45 0.375 7.26423e-12 8.41579e-09 0.624999 1.08536 0.625 
0.6 0.375 -3.21857e-09 1.25958e-08 0.624999 1.09239 0.625 
```

This time stamp is supposed to be taken out when copying it from the source directory to the output directory where we create `tests/output-depth_postprocessor_box/solution/solution-00000.0000.gnuplot.cmp.notime` (which indeed for me does not have the time stamp). Apparently the new test setup forgets to do this step. I wonder if there is a race condition in creating the `.cmp.notime` file with running the test.

In any case, I don't think that my patch here has anything to do with the failure.

**Comment by bangerth** [comment]
The other tester seems to have the same problem.

**Comment by bangerth** [comment]
ping?

**Comment by bangerth** [comment]
ping?

**Comment by gassmoeller** [comment]
I would like to have one tester compile before merging. Can you rebase to a current master? That should at least tell us if it compiles.

**Comment by bangerth** [comment]
Rebased. Let's see what happens.

**Comment by bangerth** [comment]
The only test that fails is the one with the expensive solver steps. This seems unrelated to my patch here.

**Comment by bangerth** [comment]
Rebased and works fine now on the tester.

**Pull request merged**
