### PR TITLE
Fix Tosi Case 4 benchmark

### PR DESCRIPTION
**Pull request by anne-glerum**
Although I can't reproduce the error reported in  #3076 on my Macbook, this should fix it. Viscosity was being computed even though strain rate was set to size zero in the calling AdiabaticConditions to flag that viscosity wasn't needed. @tjhei could you test it on your machine?

### For all Pull Requests:

* [x] I have followed the instructions for indenting my code according to ASPECT's code style as described in the last paragraph of the ['Making ASPECT better'](../CONTRIBUTING.md#making-aspect-better) section of CONTRIBUTING.md.

### For Feature/Benchmark Submissions or Changes of Existing Behavior:

* [x] I have tested my new feature locally to ensure it is correct: I get the same results for Tosi_Case4.prm as before.

### CODE REVIEW

**Comment by tjhei** [comment]
@gassmoeller 
CIG tester says
```
+ docker inspect -f . c20d06764310d9fab0ac6af1286ccc7f46e47b71
Failed to run image 'c20d06764310d9fab0ac6af1286ccc7f46e47b71'. Error: docker: Error response from daemon: failed to start shim: exec: "docker-containerd-shim": executable file not found in $PATH: unknown.
```
have you seen that before?

**Comment by gassmoeller** [comment]
No, but it also happens on #3179 and #3178. I would guess it is our testing system, and not the pull request. I will look into it as soon as possible.

**Comment by tjhei** [comment]
a restart probably fixes the machine. :-)

**Comment by tjhei** [comment]
The tester is not going to do anything useful anyways, so we are good to merge.

**Pull request merged**
