### PR TITLE
Correct depth average gnuplot labels

### PR DESCRIPTION
**Pull request by bobmyhill**
Depth average output files using gnuplot format labelled the first two columns as `<x> <y>`. This has now been corrected to `<depth> <time>`.

This PR resolves Issue #945.

### CODE REVIEW

**Comment by tjhei** [comment]
can you run astyle?

**Comment by bobmyhill** [comment]
@tjhei indentation corrected. thanks!

**Comment by bangerth** [comment]
Wrong indentation notwithstanding, I'm curious whether this works with deal.II 8.5 or only 9.0. But we will find out if we run the tester:
/run-tests

**Comment by bobmyhill** [comment]
@tjhei, can you rerun jenkins with TRUST_BUILD=true please?

**Comment by bobmyhill** [comment]
@bangerth I guess we have our answer!!

**Comment by bangerth** [comment]
Indeed.

@bobmyhill: You can fix this if you enclose the new piece of code with
```
#if DEAL_II_VERSION_GTE(9,0,0)
...
#endif
```
This should then continue to work on both versions of deal.II, but of course only result in the changed output with 9.0. Since the regression tester still runs on 8.5, you'll have to revert back to the old test output.

**Comment by bobmyhill** [comment]
Thanks Timo. Requested change made... hopefully this passes the tests now!

**Pull request merged**
