### PR TITLE
Save and load some critical parameters during checkpoint/restart.

### PR DESCRIPTION
**Pull request by bangerth**
This allows us to do a basic integrity check upon restart time.

This has the potential to earn me the Puckett Bucket on day 1 of the hackathon,
but I'd still like to see what happens during tests.

In reference to #2090.

### CODE REVIEW

**Comment by bangerth** [comment]
I don't think this is ready yet, but I wanted to see what the tester does with it.

**Comment by tjhei** [comment]
This looks good. I assume the tests will pass and we can merge it...

**Comment by bangerth** [comment]
Oh, miraculously, it actually worked successfully through the testsuite! I had fully expected to break a whole bunch of tests :-)

**Comment by MFraters** [comment]
That seems like a great opportunity to add a test which would have failed and now works :)

**Comment by bangerth** [comment]
Yes. I need to figure out how to do this, but it's on my list.

**Comment by bangerth** [comment]
I pushed another commit with a new test that should current fail, and I want to see it fail on the tester. If that's what happens, then I'll add the `EXPECT FAIL` tag to it.

**Comment by bangerth** [comment]
OK, it failed as hoped for. I've updated the test to expect failure -- let's see how this does now.

**Comment by tjhei** [comment]
the test still fails: https://jenkins.tjhei.info/blue/organizations/jenkins/aspect/detail/PR-2310/5/pipeline

**Comment by bangerth** [comment]
Yes, I still needed to update the test output. Let's try this again.

**Comment by tjhei** [comment]
can you rebase to master please? Otherwise "bangerth-down" won't like your PR.

**Comment by bangerth** [comment]
I need help. I can't figure out why this one test fails -- it succeeds on my system and I have no idea why it doesn't on the tester. It complains about different output files, but the numbers look the same to me up to several digits down. It says
```

##28      #:3   <== 1.224703447855e+06
##28      #:3   ==> 1.224703422203e+06
@ Absolute error = 2.5652000000e-2, Relative error = 2.0945479154e-8
```
But that's basically identical. Don't we have a relative error of 1e-6?

**Comment by bangerth** [comment]
I think I see -- I just have to take the output file that the tester wants, not the one I get on my own machine :-(

**Comment by gassmoeller** [comment]
Looks good, thanks for fixing!

**Pull request merged**
