### PR TITLE
Have time as a postprocessor particle property

### PR DESCRIPTION
**Pull request by EstherHeck**
Pull Request Checklist. Please read and check each box with an X. Delete any part not applicable. Ask on the [forum](https://community.geodynamics.org/c/aspect) if you need help with any step.

I added a postprocessor that writes the current model time into the files of particle properties.

### Before your first pull request:

* [x] I have read the guidelines in our [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) document.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [x] I have tested my new feature locally to ensure it is correct.
* [x] I have [created a testcase](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests) for the new feature/benchmark in the [tests/](../blob/master/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/master/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Hi Esther, can you explain the purpose for which you want to use this? It feels like a lot of memory to store the same model time as a property for every particle, and each particle output file is already associated with a time (that is how paraview knows the time for each file). Do you need this for further calculations?

**Comment by EstherHeck** [comment]
Hi, I need this when I output particle properties to ascii files and then plot them directly from there without paraview. Like in my case velocity over time. Then I have it all in the same set of files, which makes it easier.

**Comment by bangerth** [comment]
Oh, I didn't even read @EstherHeck 's comment above and asked the same question that @gassmoeller already did.

I think what we're both saying is that there ought to be a better way to get at that information at the place where you're plotting it. When you're opening a file with particle information, you should be able to infer the corresponding time by looking at the statistics file what time that file corresponds to. It's then just a constant number you would use in gnuplot.

**Comment by EstherHeck** [comment]
ok. I found it useful, so I thought others might find it too. But if you don't think so, I will just use it for myself as a library. Should I then close this PR?

**Comment by bangerth** [comment]
But then we also don't want to discouraging! I think what we're both concerned about is people using this when they have a billion particles.

Do you know how to create your visualizations without this data in gnuplot? How about we close this PR and we'll help you with finding an alternative way to do what you want to do if you haven't found one already?

**Comment by EstherHeck** [comment]
Don't worry, I am not discouraged at all. And yes, you are right, when using a billion particles that is not helpful. I used 10 as a sort of analog for a GPS station. If you have a good idea on how to do that differently, that would be nice. Especially because I am thinking to switch to having active particles to track the composition

**Comment by bangerth** [comment]
Can you show me how you're currently using gnuplot to visualize your data?

**Pull request closed without merging**
