### PR TITLE
Depth dependent viscosity implemented in "Classic" material model

### PR DESCRIPTION
**Pull request by maxrudolph**
Classic extends the "Simple" material model, adding depth dependence in addition to the temperature and composition dependence present in Simple. Also included is a test case for the "Classic" material model.

### CODE REVIEW

**Comment by bangerth** [comment]
It's too late to review this in detail, but:
* Could we come up with a better name than "Classic" for the model?
* You'll have to indent the whole thing according to standard. To this end, install astyle 2.04 (this very particular version).

**Comment by bangerth** [comment]
Oh, and third: Please squash all of those commits into one or two.

**Comment by maxrudolph** [comment]
Do you have an alternate suggestion for the name?
I chose classic because many of the classic papers in mantle dynamics use depth-dependent viscosity or relatively simple flow laws with both temperature and depth dependence, or with temperature, depth, and stress-dependence. 

I will install the requisite version of astyle and fix this.

**Comment by bangerth** [comment]
Maybe "depth dependent simple"? What is class today may no longer be classic tomorrow. I've generally found that in software, temporal references don't work very well -- within a couple of years, people don't get the context any more. Recall that Citcom has been around for 20 years by now and is still heavily used. We may have to expect the same for ASPECT...

**Pull request closed without merging**
