### PR TITLE
Newton merge 1

### PR DESCRIPTION
**Pull request by MFraters**
a follow up to #1410, addressing the comments there.

### CODE REVIEW

**Comment by MFraters** [comment]
This is weird. I used astyle --options=../doc/astyle.rc ../source/simulator/newton.cc, but the astyle of the tester thinks it should be different. Any idea what is going on?

**Comment by bangerth** [comment]
What's your version of `astyle`? Instead of running it by hand, just do `./doc/indent` which sets all of the correct arguments to the program. You can also run `make indent` from the build directory.

**Comment by MFraters** [comment]
my version is 2.05.1, I am now trying to downgrade but apt only has the 2.05.1 version, so I will for now manually adjust it

**Comment by jperryhouts** [comment]
To save you some time: get 2.04 from
https://sourceforge.net/projects/astyle/files/astyle/astyle%202.04/astyle_2.04_linux.tar.gz/download
and install it with:
```
tar -xzf astyle_2.04_linux.tar.gz
cd astyle/build/gcc
make
sudo mv bin/astyle /usr/bin/astyle204
```

**Comment by MFraters** [comment]
thanks :)

**Comment by MFraters** [comment]
got it now!

**Comment by MFraters** [comment]
Any more comments?

**Comment by bangerth** [comment]
Let's get this Newton merge started. A small cleanup is coming in a minute.

**Pull request merged**
