### PR TITLE
Improve boundary checks in a number of places

### PR DESCRIPTION
**Pull request by gassmoeller**
Follow up to #4406 to improve the check for top/bottom boundary faces and more appropriate use of the manifold to compute centers of faces and cells. I did not explain the parameter more in the manual, because this is way too specific for the section it is used in, and it is just an example code sample, not something the user is expected to copy and use.

### CODE REVIEW

**Review by tjhei — APPROVED** [review]

**Comment by tjhei** [comment]
can you check and adjust test results? Ready to go otherwise.

**Comment by gassmoeller** [comment]
I have updated the tests. The changes were surprising to me, but they are caused by the improvements to the normalize_pressure function when normalizing the surface pressure. It seems the old check did miss some surface faces if the cells are coarse and of a bad aspect ratio. E.g. the average surface pressure in the merged_chunks_3d test went down from -2.841e+08 Pa to 0.01564 Pa in this PR.

**Comment by tjhei** [comment]
Fascinating. Would it make sense to add a changelog entry about this fact?

**Review by tjhei — APPROVED** [review]

**Comment by gassmoeller** [comment]
Yes it would. Changelog entry added.

**Comment by tjhei** [comment]
great, thank you.

**Pull request merged**
