### PR TITLE
MPI_Abort on exception in initial condition

### PR DESCRIPTION
**Pull request by gassmoeller**
If an initial condition plugin throws an exception it is usually impossible to recover, because other plugins will attempt MPI communication that the throwing plugin cannot participate in. In a case @alarshi and I were investigating the WorldBuilder would throw an exception that would lead to an MPI deadlock only on very highly refined models (it depends on the resolution).

This PR implements the same solution we already use for postprocessors and particle interpolators to catch the exception, print a useful message and then call MPI_Abort to avoid a deadlock. 

I also wonder if we should somehow generalize this pattern for all plugin calls (not sure how though).

@tjhei: This is what we talked about today.

### CODE REVIEW

**Review by tjhei — APPROVED** [review]
Great.

The only potential problem I see with this change is that you will receive a lot of output if all 100k MPI ranks decide to throw. I don't know a way around that, though.

**Comment by bangerth** [comment]
To @tjhei 's point about getting a lot of text on the console if all 100k processes fail: This is what we have `QuietException` for. We typically use this as follows:
```
        catch (const std::exception &exc)
          {
            if (Utilities::MPI::this_mpi_process(mpi_communicator) == 0)
              AssertThrow (false,
                           ExcMessage (std::string("The direct Stokes solver "
                                                   "did not succeed. It reported the following error:\n\n")
                                       +
                                       exc.what()))
              else
                throw QuietException();
          }
```
In other words, all but what happens on process 0 is converted to `QuietException`. In `main.cc`, we have this:
```
  catch (aspect::QuietException &)
    {
      // Quietly treat an exception used on processors other than
      // root when we already know that processor 0 will generate
      // an exception. We do this to avoid creating too much
      // (duplicate) screen output.

      // Sleep a few seconds before aborting. This allows text output from
      // other ranks to be printed before the MPI implementation might kill
      // the computation.
      std::this_thread::sleep_for(std::chrono::seconds(5));

      MPI_Abort(MPI_COMM_WORLD, 1);
      return 1;
    }
```
That is we abort the process regardless of where the exception happens, but we only generate output on process zero. This would only be a problem if the failure happens *only* on a process other than the root, but I suspect this to be rare.

**Comment by tjhei** [comment]
The problem @gassmoeller encountered is that only a few processes ended up triggering the issue, which means only reporting on rank 0 would not work.

**Comment by bangerth** [comment]
Out of curiosity, what happened on those processes that doesn't happen on process zero? Did you evaluate the initial condition function outside its range of definition?

**Comment by gassmoeller** [comment]
The WorldBuilder uses a Newton iteration and for some combination of feature and location the iteration would not converge and it threw exceptions.

**Comment by bangerth** [comment]
Ah, bugger. That's a nuisance.

**Pull request merged**
