### PR TITLE
Removed workaround that included vector_tools.templates.h in freesurf…

### PR DESCRIPTION
**Pull request by spco**
…ace.cc. I don't think it was ever truly needed.

### CODE REVIEW

**Comment by bangerth** [comment]
Can you trace back on whose request this was put in? Maybe we can ask them to test with their current setup?

**Comment by spco** [comment]
It was on my request! #641 I later came back to it a couple of months ago with a complete rebuild and never had the same problem - I forget what it was that I decided I'd done wrong in my previous setup, even when I thought I'd done a complete rebuild. Something in my Xcode setup I believe.

**Comment by bangerth** [comment]
In that case we should merge! :-)

First one to see that the tester is happy push "merge"!

**Comment by spco** [comment]
Looks good to merge!

**Pull request merged**
