### PR TITLE
Disabled pointwise visualization

### PR DESCRIPTION
**Pull request by Wang-yijun**
Fixed issue #4177 by `set Point-wise stress and strain = false` in `visualization_stress.prm` so that it is different from `visualization_stress_pointwise.prm.`

### Before your first pull request:

* [x] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [ ] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Comment by MFraters** [comment]
Hey Yijun,

Thanks for making this pull request! 

Looking at #4177 it also states: 
> The first test should not output point-wise stress and strain.

Looking at the file, I am not sure what is mend with that. @anne-glerum, do you want `set List of output variables` to be empty for `visualization_stress.prm`

/rebuild

**Comment by anne-glerum** [comment]
@Wang-yijun 
Thanks for making this change!

@MFraters 
These are two identical tests, apart from their name. One has the extension `_pointwise` to indicate that the stress and strain output is point-wise instead of element-wise (as well as the comment `# Like visualization_stress.prm but with point-wise output`). But both tests use the point-wise output. So the visualization_stress.prm should not have `set Point-wise stress and strain = true` but `set Point-wise stress and strain = false`.

**Comment by MFraters** [comment]
@anne-glerum Thanks for the explanation, it makes sense now :)

@timo, it seems like the rebuild command didn't work for me. Did I do it incorrectly?

**Comment by bangerth** [comment]
@MFraters It worked now. Can you check again?

**Review by MFraters — APPROVED** [review]
This looks good to me. @anne-glerum Since it was your issue, does this look good to you?

**Comment by anne-glerum** [comment]
Yes, great! @Wang-yijun Once it's merged, you could try to close the issue (I'm not you have the rights).

**Comment by gassmoeller** [comment]
I was not part of this discussion, but it looks like everyone agreed this is resolved. I will merge this.

**Pull request merged**
