### PR TITLE
Require deal.II 8.4.1

### PR DESCRIPTION
**Pull request by tjhei**
This will switch the required deal.II version to 8.4.1 and update the test results such that the 8.4.1 tester will pass. Consequently, this will break the output for the old tester based on 8.2.1.

### CODE REVIEW

**Comment by tjhei** [comment]
(do not merge yet, I want to make sure everything is working correctly)

**Comment by bangerth** [comment]
Alternatively: we currently output a lot of data with six digits. So any small change is on a relative order of slightly larger than 1e-6. That's why the new tester has so many failing tests. We could just up the relative tolerance for numdiff to 1e-5 and avoid this unfortunate mismatch for now and future cases.

**Comment by tjhei** [comment]
Many changes are number of linear iterations, unfortunately.

**Comment by bangerth** [comment]
Yes, we can't do much about that. Do you have a sense whether iterations tend to go up or down?

**Comment by tjhei** [comment]
> Do you have a sense whether iterations tend to go up or down?

Sometimes more, sometimes less. Differences are minor, though. See https://github.com/geodynamics/aspect/pull/878/commits/f61a83b9347e66394f7f4df56a6b7a7218dc337e

**Comment by tjhei** [comment]
okay, I think this is good to go!

**Pull request merged**
