### PR TITLE
Update test and plugin description and add test

### PR DESCRIPTION
**Pull request by anne-glerum**
To finalize addressing issue #4056, I've cloned the test that checks whether surface and volume stress visualization output give the same results to include `set Point-wise stress and strain = true`. With this setting the stresses should actually be equal.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [x] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Review by bangerth — APPROVED** [review]
I assume you have verified that the two really do agree?

**Comment by anne-glerum** [comment]
> I assume you have verified that the two really do agree?

In the issue, I wrote that they are the same: "I've checked again now that https://github.com/geodynamics/aspect/pull/4181 is merged, and with point-wise values, the output on the surface mesh and the volume mesh is the same 🥳 ."

Do you want me to check again?

**Comment by bangerth** [comment]
No, I was just wondering because here you wrote "With this setting the stresses should actually be equal." I take your word that they are :-)

**Comment by anne-glerum** [comment]
While fixing the test, I also compared the output on the volume and on the surface mesh, and the stresses are indeed still the same.

**Comment by bangerth** [comment]
You win the prize for the most thoroughly thought through PR then! :-)

**Pull request merged**
