### PR TITLE
add GWB and Newton to dynamic citation page

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by tjhei** [comment]
FYI @MFraters

**Comment by MFraters** [comment]
Thanks! The newton solver entry is a duplicate of entry FBTGS18 (line 11499 in manual.bib), but since the new one is more complete I think it is better to delete that one.

**Comment by tjhei** [comment]
I took the entry from citing_aspect.bib. I will clean that up.

**Comment by tjhei** [comment]
maybe like this?

**Comment by MFraters** [comment]
Yes, I think that is a good way to make it consistent. Just one thing, why did you use "FBTGS18" instead of "FBTGS19"?

**Comment by tjhei** [comment]
> why did you use "FBTGS18" instead of "FBTGS19"?

Because this is what is already used in the manual. I did not create that entry.

**Comment by tjhei** [comment]
I renamed the citation.

**Pull request merged**
