### PR TITLE
Fix RHS in assembly

### PR DESCRIPTION
**Pull request by rrgrove6**
In my weak form, the phi is on the left of each term in the RHS in the weak form that I recently proposed to be added, and I think the manual should match the code.  (It was also said that we want the phi to be on the left, which is why I did it the way I did).

### CODE REVIEW

**Comment by bangerth** [comment]
So does this supersede #386 ?

**Comment by tjhei** [comment]
No, it looks like Ryan based this branch off of the other PR and not off of master.

**Comment by rrgrove6** [comment]
This is a separate issue that is related to my other pull request to change the manual.  Careful though, as Timo has just mentioned that last time I changed the order to what I expected it to be, it broke things.

**Pull request closed without merging**
