### PR TITLE
[deal.II 9.3] Modernization of face loops.

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Comment by tjhei** [comment]
Isn't cell->face_indices() an addition after 9.2?

**Comment by bangerth** [comment]
I guess so it seems! I had forgotten. So then let's defer this to a later time -- I'll just keep this open for in a year or so :-)

**Comment by tjhei** [comment]
Can you please rebase?

**Comment by bangerth** [comment]
Rebased!

**Review by tjhei — APPROVED** [review]

**Pull request merged**
