### PR TITLE
checkpointing test for iterative solver

### PR DESCRIPTION
**Pull request by tjhei**
- move checkpoint_02 to checkpoint_02_direct
- change checkpoint_02 to use the iterative solver
- checkpointing with Trilinos iterative solvers requires a patch at
  least up to 12.2.1

Note: we should wait with merging this pull request until the bugfix lands in trilinos, we have a new release, and the tester is updated to that version.

### CODE REVIEW

**Comment by tjhei** [comment]
(confirmed to be working on my machine with patched Trilinos)

**Comment by gassmoeller** [comment]
@tjhei: Is this still relevant? It seems like it only affects tests and all version issues should be fixed, so it might be easy to rebase and merge.

**Comment by tjhei** [comment]
rebased. Let's see what happens.

**Comment by bangerth** [comment]
It fails the two `output-checkpoint_02{,_direct}` tests.

**Comment by gassmoeller** [comment]
Most likely the failures are caused by the differences from changes on mainline (more cheap iterations, different outputs in depth_average, different structure of the statistics file). As long as the iterative and direct output are similar this should be fine.

**Comment by tjhei** [comment]
things seem to be working...

**Comment by gassmoeller** [comment]
Looks good.

**Pull request merged**
