### PR TITLE
Rearrange timestep statistics location

### PR DESCRIPTION
**Pull request by class4kayaker**
Addresses #1214.

Given that the test results are certain to need  to be updated and the lack of dependency on the results of the calculations for the current timestep, I have taken the opportunity to move the insertion of the timestep into the statistics file so that it will occur in column 3. This is likely to be a nicer grouping of statistics data, though the change may result in needing to adjust scripts in some cases, and may suggest the inclusion of a `changes.h` entry including the modification.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Very nice! You will probably have to update most of the tests, but the code change looks good. Are you aware that there is a make target 'generate_reference_output' and a script `cmake/generate_reference_output.sh`? Might come in handy for this work. Thanks!

**Comment by bangerth** [comment]
Yes, nice change. Make sure the entry to changes.h mentions what users may have to do.

**Comment by class4kayaker** [comment]
I do know of the way to generate reference output, but given the need for the tester to generate the test output due to library differences etc., I decided to rely on the tester's output. I did do a simple check with the sol_cx output but did not include them in a commit.

**Comment by gassmoeller** [comment]
Looks good. Thanks for contributing. This should close #1214.

**Pull request merged**
