### PR TITLE
sphinx doc: treat warnings as errors

### PR DESCRIPTION
**Pull request by tjhei**
inspired by #5370

### CODE REVIEW

**Comment by tjhei** [comment]
```
/home/docs/checkouts/readthedocs.org/user_builds/aspect-documentation/checkouts/5374/CONTRIBUTING.md:120: WARNING: 'myst' cross-reference target not found: 'doc/modules/changes/' [myst.xref_missing]
/home/docs/checkouts/readthedocs.org/user_builds/aspect-documentation/checkouts/5374/CONTRIBUTING.md:142: WARNING: 'myst' cross-reference target not found: 'doc/modules/' [myst.xref_missing]
/home/docs/checkouts/readthedocs.org/user_builds/aspect-documentation/checkouts/5374/CONTRIBUTING.md:163: WARNING: 'myst' cross-reference target not found: 'AUTHORS.md' [myst.xref_missing]
/home/docs/checkouts/readthedocs.org/user_builds/aspect-documentation/checkouts/5374/CONTRIBUTING.md:167: WARNING: 'myst' cross-reference target not found: 'LICENSE' [myst.xref_missing]
```

**Comment by tjhei** [comment]
@gassmoeller Do you know how to fix this?

**Comment by gassmoeller** [comment]
Yes I noticed these two in #5370, but couldnt find an easy way to fix them. The problem is that `Contributing.md` is not in the root path of the sphinx documentation and we use the indirect include in `doc/sphinx/user/extending/contributing.md` to include it, but this breaks relative links. We could modify Contributing.md to directly link to the files on github (instead of using relative links), it's just not as pretty when you read it in a file editor. Thoughts?

**Comment by tjhei** [comment]
updated.

**Review by gassmoeller — APPROVED** [review]

**Pull request merged**
