### PR TITLE
Jenkinsfile.k8s : Build in Jenkins workspace instead of /home/dealii and other build step cleanup

### PR DESCRIPTION
**Pull request by tjesser-ucdavis-edu**
Some more refactoring to remove complexity.

Regarding https://github.com/geodynamics/aspect/commit/bbe3c56225d3e1b3178c3fc78a6dee0626376be5, I'm not sure how Aspect detects the Deal.ii installation in the container, so that change may need to be reverted.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Did you check if this makes Jenkins preserve all the build folders, which would quickly clutter the hard disk of the jenkins master? I remember that we looked into this last week, but dont remember our conclusion.

**Comment by tjesser-ucdavis-edu** [comment]
The files on the Jenkins master server just come from the `git clone` it does before creating the jnlp container. The files created by building never leave the jnlp container (except as artifacts).

**Comment by gassmoeller** [comment]
Ok, looks good. Since we are sure the files remain inside the container (and are thrown away after the test run) this is good to go. For reference: ASPECT finds deal.II via an environment variable DEAL_II_DIR that is set inside the container, so we do not need to worry about where we build ASPECT.

**Comment by tjhei** [comment]
Are you sure? I would assume that the workspace directory is mounted in the ``docker run`` command from the outside. Building inside it could a) be slower or b) leave the files behind.
What is the advantage of this approach?

**Comment by gassmoeller** [comment]
It is mounted from the outside, but the `outside` here means the jenkins-agent (jnlp) container, which was started by the jenkins-master. If we understood everything correctly, the jenkins-master should only store the artifacts. Maybe that is different to your jenkins setup, because we routinely destroy our agents after a test run has finished (because the kubernetes pod ends), and each pull request gets its new jenkins-agent container.

**Pull request merged**
