### PR TITLE
Fix initial composition stabilization

### PR DESCRIPTION
**Pull request by gassmoeller**
This is a first stab at some problems with constant compositional fields that I had (see #282). I am still a bit confused what the real reason behind this is, but at least the attached change improves the behaviour of the included test and my models (the advection solver does not converge in step-1 on master, but runs fine with this change). The reasoning behind this is that the gradients in the temperature field compared to the compositional field, are larger in dimensional units, because they are multiplied by rho and cp (and the temperature itself is usually 3 orders of magnitude larger than the composition). Therefore, every arbitrarily chosen number has to be scaled by around 1e-9 between temperature and composition as well. I would be happy to get opinions, and we should wait for the tester before going further with this, since it might change a number of test results (slightly).

### CODE REVIEW

**Comment by tjhei** [comment]
It looks like all the tests are passing. I am not too fond of the old or the new magic constant, though. Would it be possible to include rho C_p in that formula?

I don't understand why we need a smaller artificial diffusion to make the solver converge, though. Is this needed for timestep 0 or timestep 1?

**Comment by gassmoeller** [comment]
This would be an alternative, which uses rho and cp. There is still the magic number for the velocity though. 

I am also not sure, why the high diffusion causes problems. Maybe we introduce so much diffusion that we are indeed in the diffusion dominated regime and would need to use a conduction timestep only because of the stabilization? That could not be catched by checking with our conduction timestep either, because that only considers the normal diffusion, but not the artificial stabilization.

**Comment by gassmoeller** [comment]
Ah, the new version breaks the tests with constant fields. It should only reduce the initial diffusion though.

Concerning your first question, timestep 1 is the problem (I guess, because it is the first step with a timestep size larger zero and still using the large initial diffusion instead of the max_viscosity, because the entropy variation is zero).

**Comment by tjhei** [comment]
I like this much better, but velocity = 0.01m / year is only a good choice for models that are to scale, right? Should we use something based on geometry_model->length_scale() instead?

**Comment by bangerth** [comment]
I suppose if you use a length scale, then you also need to have something like a time scale. I don't really see a good way around using a magic number, though I'm also not fond of it (I'm guilty of the 1e-50, I believe).

Do such cases appear in realistic models at all, or does this only happen in artificial cases on a box, for example?

**Comment by gassmoeller** [comment]
This way the formulation should be independent of the dimensions of the model. In fact this is the same nondimensionalization for the velocity that CitcomS is using. It reduces the diffusion in this special case a bit further (now the reference velocity is around 3 mm/year for usual models), but that should be ok, this is only the backup case if the real velocity is 0 anyway.

@bangerth: This particular case (global velocity = 0) might not be happening often apart from tests, but the initial problem why we started cleaning this part indeed caused me some trouble in a real model. More specific, we have a model in which the composition is globally 0 in the beginning, and then it is used to sum up a quantity (degree of melting) over time that is advected with the flow.

**Comment by tjhei** [comment]
Thanks for reworking this, Rene. Can you take over 26b5058e47eb3476872d6f803a7fae08259a7922 from https://github.com/tjhei/aspect/commits/pull-321 to fix the tests please?

**Comment by gassmoeller** [comment]
I merged the updated tests, rebased, squashed and added an entry in changes.h. Do you think this is ready for merge?

**Comment by bangerth** [comment]
This looks good to me. @tjhei : Please merge if you're ok with it as well!

**Pull request merged**
