### PR TITLE
Convert more std::shared_ptr to std::unique_ptr.

### PR DESCRIPTION
**Pull request by bangerth**
This also removes a deprecated function that can't easily be converted.

Part of #2811 and #2375.

### CODE REVIEW

**Comment by tjhei** [comment]
```
214/669 Test  #32: ascii_boundary_member ..............................................***Failed    9.53 sec

*** "Test ascii_boundary_member failed": ***

[1/10] Building CXX object CMakeFiles/ascii_boundary_member.dir/ascii_boundary_member.cc.o

FAILED: /usr/bin/mpicxx   -DASPECT_SOURCE_DIR=\"/jenkins/workspace/aspect_PR-2958\" -DBOOST_NO_AUTO_PTR -DDEBUG -DTBB_DO_ASSERT=1 -DTBB_USE_DEBUG -Dascii_boundary_member_EXPORTS -isystem /home/dealii/dealii-v9.0.1/include -isystem /home/dealii/dealii-v9.0.1/include/deal.II/bundled -isystem /usr/include/mpich -isystem /home/dealii/libs/parmetis-4.0.3/include -isystem /home/dealii/libs/trilinos-release-12-10-1/include -isystem /home/dealii/libs/superlu_dist_5.1.2/include -isystem /home/dealii/libs/petsc-3.7.6/include -isystem /home/dealii/libs/adolc-2.6.4-rc1/include -isystem /home/dealii/libs/assimp-4.1.0/include -isystem /home/dealii/libs/hdf5-1.10.1/include -isystem /home/dealii/libs/nanoflann-v1.2.3/include -isystem /home/dealii/libs/oce-OCE-0.18.2/include/oce -isystem /home/dealii/libs/p4est-2.0/FAST/include -isystem /home/dealii/libs/slepc-3.7.3/include -isystem /home/dealii/libs/sundials-3.1.0/include -I/jenkins/workspace/aspect_PR-2958/include -fPIC    -pedantic -fPIC -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wsynth -Wsign-compare -Wswitch -Woverloaded-virtual  -Wno-literal-suffix -fopenmp-simd -std=c++14 -std=c++14 -Wno-parentheses -Wno-unused-local-typedefs -Og -ggdb -Wa,--compress-debug-sections -MMD -MT CMakeFiles/ascii_boundary_member.dir/ascii_boundary_member.cc.o -MF CMakeFiles/ascii_boundary_member.dir/ascii_boundary_member.cc.o.d -o CMakeFiles/ascii_boundary_member.dir/ascii_boundary_member.cc.o -c /jenkins/workspace/aspect_PR-2958/tests/ascii_boundary_member.cc

/jenkins/workspace/aspect_PR-2958/tests/ascii_boundary_member.cc: In instantiation of ‘void aspect::AsciiBoundaryMember<dim>::initialize() [with int dim = 2]’:

/jenkins/workspace/aspect_PR-2958/tests/ascii_boundary_member.cc:161:3:   required from here

/jenkins/workspace/aspect_PR-2958/tests/ascii_boundary_member.cc:82:50: error: ‘class aspect::AsciiBoundaryMember<2>’ has no member named ‘get_prescribed_boundary_velocity’

     bvs = this->get_prescribed_boundary_velocity()
```

**Comment by bangerth** [comment]
Let's see about this version.

**Comment by tjhei** [comment]
```
/jenkins/workspace/aspect_PR-2958/tests/ascii_boundary_member.cc:82:50: error: ‘class aspect::AsciiBoundaryMember<2>’ has no member named ‘get_prescribed_boundary_velocity’

     bvs = this->get_prescribed_boundary_velocity()
```

**Comment by bangerth** [comment]
Good grief...

**Pull request merged**
