### PR TITLE
corrected geoid parameter typo

### PR DESCRIPTION
**Pull request by bobmyhill**
The PR corrects a geoid parameter typo:
Include the contributon from dynamic topography -> Include the contribution from dynamic topography

### CODE REVIEW

**Comment by naliboff** [comment]
I hit approve a bit too quickly :) This will breaks backwards compatibility in parameter files. @gassmoeller and others - is the standard practice for this to provide an update script or modify an existing one?

**Comment by gassmoeller** [comment]
Can we hold off on this PR for a while? We are planning to fix this as part of #3776, where @mfmweerdesteijn will introduce two new parameters that will replace this one. We can keep this open as a back up.

**Comment by bobmyhill** [comment]
Sure! Feel free to close if/when it's superseded.

**Comment by bangerth** [comment]
@naliboff What's the status on this one?

**Comment by bangerth** [comment]
Actually, let's get this merged. The worst that can happen are minor merge conflicts when #3776 is ready, but this way we're sure the typo is fixed and that this PR has been dealt with.

**Comment by mfmweerdesteijn** [comment]
No :p I'm merging today hopefully, I'm not looking forward to conflicts haha

**Comment by mfmweerdesteijn** [comment]
Also, I was told that changing the parameter name like that, will break tests...

**Comment by bangerth** [comment]
@mfmweerdesteijn Ah, my apologies :-) Please draw on me to help you with merge conflicts if you get any! Find me on wonder.me.

**Pull request merged**
