### PR TITLE
Make the screen output of the tracer postprocessor look like all other postprocessors.

### PR DESCRIPTION
**Pull request by bangerth**
Seen while looking at #792.

### CODE REVIEW

**Comment by bangerth** [comment]
This is going to break some test outputs. Let the tester run so I can update these files before merging.

**Comment by bangerth** [comment]
Ah, or maybe no tests actually exercised this so far. That's interesting in itself, but nothing for the current patch to address.

So I think it's ready to review.

**Comment by tjhei** [comment]
Would you mind adding a test that actually executes this code?

**Comment by tjhei** [comment]
Otherwise good to go of course.

**Comment by bangerth** [comment]
OK, this is weird. On my system, the `particle_output_none` test actually fails with the current patch. It is beyond me why this is not the case on your tester.

I'm pushing a second commit that fixes the affected tests on my system.

**Comment by bangerth** [comment]
(In other words, there already are tests that this affects -- your tester just didn't reveal it for some reason.)

**Comment by bangerth** [comment]
The tester is (again) happy with this all. Merge?

**Pull request merged**
