### PR TITLE
Test what dependencies the material models declare.

### PR DESCRIPTION
**Pull request by bangerth**
In anticipation of @moorek 's complete rewrite of all of this.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Should this be merged before the other PR, or should we wait?

**Comment by bangerth** [comment]
Should be merged before the other PR so we can double-check.

I also added checks for the material models defined in tests/.

**Comment by bangerth** [comment]
Extremely boring patch, but I would appreciate someone taking a look now so we can still get @moorek on track tonight.

**Comment by gassmoeller** [comment]
There is a failing test for the burstedde material model ... it seems like the number of iterations is changing. Can you take a look? If it is only the number of iterations, we might merge it anyway, but it is weird anyway.

**Comment by bangerth** [comment]
I changed the number of iterations by hand in an updated commit. It's a new test, so it's not that the number changed by this commit -- it's just different between @tjhei 's tester and my laptop.

**Pull request merged**
