### PR TITLE
turn on c++ standard library debug checks

### PR DESCRIPTION
**Pull request by tjhei**
Also see https://github.com/dealii/dealii/pull/17485/files

### CODE REVIEW

**Comment by gassmoeller** [comment]
Looks like a lot of our tests are violating the debug checks. Do you want me to look into the particle tests?

**Comment by tjhei** [comment]
Let me see if I can figure it out. I am compiling on my machine right now.

**Comment by tjhei** [comment]
@gassmoeller : FYI

**Review by gassmoeller — APPROVED** [review]
Good find. If the solution or gradients are not used by the property plugins the vectors are not created in the particle world and so we had accesses outside the container here. They were not actually used, but an error nevertheless. Eventually this function implementation can be removed (once we remove the deprecated update function), but until then this is a good workaround.

**Comment by tjhei** [comment]
Agreed.

**Pull request merged**
