### PR TITLE
Escape some quotes in .md files

### PR DESCRIPTION
**Pull request by bangerth**
The first commit of this PR just updates the current set of parameters to what the main branch provides.

The second commit is the interesting one: It applies the transformation in #4791 to escape quotes. I made this a separate PR because if we merge this, the rendering of parameters will already be much nicer. 

/rebuild

### CODE REVIEW

**Comment by tjhei** [comment]
I would rather merge  #4791 with the changes here included there as well to be consistent.

**Comment by bangerth** [comment]
So you just want me to to throw these two commits into #4791 instead?

**Comment by bangerth** [comment]
OK, so done.

**Comment by gassmoeller** [comment]
This was part of #4791, right? Can this be closed?

**Pull request closed without merging**
