### PR TITLE
fix: create additional material model outputs for base models

### PR DESCRIPTION
**Pull request by jdannberg**
Some material models have base models, and these base models might create additional outputs. We need to let the base models create these additional outputs, but at least in the depth-dependent and the prescribed viscosity model this was not done. 
This PR fixes the issue, allowing it to use the additional outputs from the base models. I have also added a test for this functionality for the depth-dependent model. 

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [x] I have tested my new feature locally to ensure it is correct.
* [x] I have [created a testcase](https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Comment by jdannberg** [comment]
The dealii-master tester seems to fail, but the tests that fail do not use the material models I changed (at least the ones I checked) and it looks like it is related to issue #5504 instead.

**Review by tjhei — APPROVED** [review]

**Comment by tjhei** [comment]
> t looks like it is related to issue #5504 instead.

That is correct.

**Comment by bangerth** [comment]
The tests that fail are the same ones as everywhere else.

**Comment by jdannberg** [comment]
Without the fix, we get an exception:

```
An error occurred in line <54> of file </home/juliane/software/aspect-melt/source/postprocess/visualization/named_additional_outputs.cc> in function
    void aspect::Postprocess::VisualizationPostprocessors::NamedAdditionalOutputs<dim>::initialize() [with int dim = 2]
The violated condition was: 
    out.additional_outputs.size() > 0
Additional information: 
    You activated the postprocessor <named additional outputs>, but there
    are no additional outputs provided by the material model. Either
    remove the postprocessor, or check why no output is provided.
```

**Comment by jdannberg** [comment]
I have also added the other test.

**Comment by bangerth** [comment]
Thank you! At least the error message is a bit better than a segfault :-)

**Review by bangerth — APPROVED** [review]

**Pull request merged**
