### PR TITLE
README: replace license badge

### PR DESCRIPTION
**Pull request by tjhei**
the readme currently shows MIT as our license. Pick the right image instead (manually).

### CODE REVIEW

**Review by bangerth — APPROVED** [review]

**Comment by gassmoeller** [comment]
I think the one missing test result got lost, it passed all other testers, and I dont see it in the queue on the waiting tester. Since this is not changing any code I am going to merge.

**Comment by gassmoeller** [comment]
Actually I cant merge, because the missing tester is required, I triggered a rebuild, lets see if this works.

**Comment by bangerth** [comment]
I had that same thought and ran into the same problem :-)

**Comment by tjhei** [comment]
The funny thing is: I created the PR on the website (to see the preview) and GitHub created the branch in the upstream repo. The tester won't run...

**Comment by bangerth** [comment]
Well, since we can't merge it, I'm afraid you'll have to pull that branch from upstream, push to your fork and create a new PR out of it :-)

**Pull request closed without merging**
