### PR TITLE
[WIP] Always apply compressible preconditioner

### PR DESCRIPTION
**Pull request by gassmoeller**
This is the test for the first comment of Timo on top of #1976. Lets see what the tester says.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Well this certainly changes things, but some tests benefit while others need more iterations. How to decide?

**Comment by bangerth** [comment]
Can you rebase on top of all of the other patches we merged?

**Comment by gassmoeller** [comment]
From what I see there are at least as many increases in iteration numbers as decreases. Therefore I will close this for now, until we have more time for testing or a better theoretical understanding for how to proceed.

**Comment by bangerth** [comment]
OK, just to make sure I understand -- we now use the compressible terms only if the model is in fact compressible? This makes sense to me.

**Comment by gassmoeller** [comment]
Yes, we now only subtract the compressible strain-rate terms in compressible models.

**Pull request closed without merging**
