### PR TITLE
Fix grammar mistake in simulator_access.h

### PR DESCRIPTION
**Pull request by SophieCoulson**
In response to issue #2256 and in addition to Wolfgang's correction #2313

### CODE REVIEW

**Comment by MFraters** [comment]
Good start! I did find that you missed one (line 554). Could you fix that one as well and squash your commits?

**Comment by jdannberg** [comment]
@MFraters I think the one in line 554 is in @bangerth's pull request #2313.

**Comment by MFraters** [comment]
ah, you are correct :)

**Comment by bangerth** [comment]
Yes, nice! For completeness, I'm going to let the tester machine run on this with the following special command that only maintainers can use:
/run-tests
I don't expect this to turn up anything, but we like to make sure anyway!

**Comment by bangerth** [comment]
All clear -- yay!

**Pull request merged**
