### PR TITLE
Fix S40RTS spherical harmonic normalization

### PR DESCRIPTION
**Pull request by Shangxin-Liu**
When I did a robustness comparison among current global tomography models, I found that S40RTS actually doesn't use the normalization after Dahlen and Tromp, 1986, Appendix B.6, but SAVANI actually used this normalization. There is a sqrt(2) prefactor difference. To confirm this, I attach the comparison maps below:

The first map is the Vs anomaly of S40RTS at depth 175km directly from the S40RTS website data:
s40rts_175km

Here the Vs anomaly plotted from current ASPECT temperature postprocess:
global_vs_anomaly_175km

Here is the Vs anomaly plotted from ASPECT temperature postprocess after remove the sqrt(2) prefactor, same as the one from S40RTS website:
global_vs_anomaly_175km

### CODE REVIEW

**Comment by jaustermann** [comment]
Good point Shangxin. I looked back at my initial commit and in my comparison I used different color schemes in the comparison, which might allow for this bug to not be apparent. Here are the comparisons I posted with my initial commit:
https://cloud.githubusercontent.com/assets/7633875/3191573/9070c5e4-ecdc-11e3-91bc-e130f2361267.png
https://cloud.githubusercontent.com/assets/7633875/3191574/90715766-ecdc-11e3-93fb-f8ea0de686a2.png
If you don't mind I'll look into this first thing in the morning to triple check this issue but your figures are very convincing. If this is the case I'll also redo the figures for the cookbook that uses S40. Thanks!

**Comment by Shangxin-Liu** [comment]
Yes. The reason why I thought of the normalization issue is that I found the geoid and dynamic topography from S40RTS also are apparently larger than SAVANI. So I made this kind of slice comparison between ASPECT output and original data to confirm.

**Comment by jaustermann** [comment]
I double checked this and it looks good to me. Thanks @Shangxin-Liu!

**Pull request merged**
