### PR TITLE
Revert "Improve cmake system" to improve Tester performance

### LINKED ISSUE #5630: [CI] Jenkins tester is timing out / OOM / slow
It seems that with a recent change the Jenkins tester is having some issues. I see internal compiler errors, timeouts after 30 minutes, or much slower performance (build time increased from <5 minutes to 20+). See:
https://ci.tjhei.info/job/aspect/job/main/

### PR DESCRIPTION
**Pull request by tjhei**
This reverts commit fbec533dffc9923385f3e0e6f3c390675c9b8b61 PR #5621 

An attempt to fix #5630. Please do not merge.

### CODE REVIEW

**Comment by tjhei** [comment]
This seem to bring compile times back down @gassmoeller . Not sure why. :-(

**Comment by gassmoeller** [comment]
The only explanation would be if the compile definitions are actually affected by this change. I thought it would only make a difference for DebugRelease mode, but maybe I was wrong. I can give it a try later this week (comparing the definitions set for the WorldBuilder cmake target).

**Comment by tjhei** [comment]
Note that Jenkins compiles in DebugRelease mode.

**Comment by gassmoeller** [comment]
I guess this can be closed now. Feel free to reopen if necessary.

**Pull request closed without merging**
