### PR TITLE
disable precompiled header for Intel compiler

### LINKED ISSUE #4312: Compiling issues with deal.ii-master on Frontera
Building ASPECT with deal.ii-master on Frontera gives the following errors.  @tjhei 
(This is not a new issue and can be resolved by using `cmake -DASPECT_PRECOMPILE_HEADERS=OFF ../aspect`, because Frontera's Intel Compiler does not seem to like precompiling the bundled boost library inside deal.II. Therefore, disable precompiling headers. see: https://github.com/geodynamics/aspect/wiki/Installation-on-Frontera)
```
/work2/08254/jiaqi2/frontera/test_candi/install/deal.II-master/include/deal.II/bundled/boost/serialization/throw_exception.hpp(35) (col. 31): internal error: assertion failed: missing typeinfo variable (shared/cfe/edgcpfe/lower_eh.c, line 3077)


compilation aborted for /work2/08254/jiaqi2/frontera/aspect-build/CMakeFiles/aspect.dir/Unity/unity_29_cxx.cxx (code 4)
make[2]: *** [CMakeFiles/aspect.dir/Unity/unity_29_cxx.cxx.o] Error 4
make[2]: *** Waiting for unfinished jobs....
compilation aborted for /work2/08254/jiaqi2/frontera/aspect-build/CMakeFiles/aspect.dir/Unity/unity_28_cxx.cxx (code 4)
make[2]: *** [CMakeFiles/aspect.dir/Unity/unity_28_cxx.cxx.o] Error 4
/work2/08254/jiaqi2/frontera/test_candi/install/deal.II-master/include/deal.II/bundled/boost/serialization/throw_exception.hpp(35) (col. 31): internal error: assertion failed: missing typeinfo variable (shared/cfe/edgcpfe/lower_eh.c, line 3077)


compilation aborted for /work2/08254/jiaqi2/frontera/aspect-build/CMakeFiles/aspect.dir/Unity/unity_26_cxx.cxx (code 4)
make[2]: *** [CMakeFiles/aspect.dir/Unity/unity_26_cxx.cxx.o] Error 4
/work2/08254/jiaqi2/frontera/test_candi/install/deal.II-master/include/deal.II/bundled/boost/serialization/throw_exception.hpp(35) (col. 31): internal error: assertion failed: missing typeinfo variable (shared/cfe/edgcpfe/lower_eh.c, line 3077)


compilation aborted for /work2/08254/jiaqi2/frontera/aspect-build/CMakeFiles/aspect.dir/Unity/unity_25_cxx.cxx (code 4)
make[2]: *** [CMakeFiles/aspect.dir/Unity/unity_25_cxx.cxx.o] Error 4
/work2/08254/jiaqi2/frontera/test_candi/install/deal.II-master/include/deal.II/bundled/boost/serialization/throw_exception.hpp(35) (col. 31): internal error: assertion failed: missing typeinfo variable (shared/cfe/edgcpfe/lower_eh.c, line 3077)


compilation aborted for /work2/08254/jiaqi2/frontera/aspect-build/CMakeFiles/aspect.dir/Unity/unity_27_cxx.cxx (code 4)
make[2]: *** [CMakeFiles/aspect.dir/Unity/unity_27_cxx.cxx.o] Error 4
/work2/08254/jiaqi2/frontera/test_candi/install/deal.II-master/include/deal.II/bundled/boost/serialization/throw_exception.hpp(35) (col. 31): internal error: assertion failed: missing typeinfo variable (shared/cfe/edgcpfe/lower_eh.c, line 3077)


compilation aborted for /work2/08254/jiaqi2/frontera/aspect-build/CMakeFiles/aspect.dir/Unity/unity_24_cxx.cxx (code 4)
make[2]: *** [CMakeFiles/aspect.dir/Unity/unity_24_cxx.cxx.o] Error 4
/work2/08254/jiaqi2/frontera/test_candi/install/deal.II-master/include/deal.II/bundled/boost/serialization/throw_exception.hpp(35) (col. 31): internal error: assertion failed: missing typeinfo variable (shared/cfe/edgcpfe/lower_eh.c, line 3077)


compilation aborted for /work2/08254/jiaqi2/frontera/aspect-build/CMakeFiles/aspect.dir/Unity/unity_40_cxx.cxx (code 4)
make[2]: *** [CMakeFiles/aspect.dir/Unity/unity_40_cxx.cxx.o] Error 4
/work2/08254/jiaqi2/frontera/test_candi/install/deal.II-master/include/deal.II/bundled/boost/serialization/throw_exception.hpp(35) (col. 31): internal error: assertion failed: missing typeinfo variable (shared/cfe/edgcpfe/lower_eh.c, line 3077)
```

### PR DESCRIPTION
**Pull request by tjhei**
fixes #4312

### CODE REVIEW

**Comment by tjhei** [comment]
@zjiaqi2018 Can you please confirm that this works? Also, what Intel version is making problems?

**Comment by zjiaqi2018** [comment]
Test on Frontera, error: 
CMake Error at CMakeLists.txt:608 (SET):
  SET given invalid arguments for CACHE mode.

**Comment by tjhei** [comment]
Can you try again, please?

Also, what is the version (icpc -v)?

**Comment by zjiaqi2018** [comment]
Built sucessfully!
icpc version 19.1.1.217 (gcc version 8.3.0 compatibility)

**Comment by tjhei** [comment]
Perfect, this is good to go.

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
It's a shame having to do it that way, because that means that we will keep it disabled indefinitely, regardless of the compiler version. I wished we could query the compiler version to make it more specific, but that would be a substantial amount of work.

**Comment by tjhei** [comment]
We can query the compiler version but I have no idea which version is good/bad. Suggestions?

**Comment by bangerth** [comment]
Start by disabling 19.1, and if someone complains about another version not working, we can always adjust the range of versions. I'd just start with the assumption that all versions other than 19.1 actually work. Internal compiler errors have become reasonably rare these days.

**Pull request merged**
