### PR TITLE
Disable combining particle with free surface

### PR DESCRIPTION
**Pull request by gassmoeller**
Picks #2358 into the 2.0.1 release branch.

### CODE REVIEW

**Comment by anne-glerum** [comment]
Actually, another assert is triggered in the test (ExcMessage("The free surface scheme can only be used with no pressure normalization"), so set 
`set Pressure normalization                 = no`
Otherwise it looks good.

**Comment by bangerth** [comment]
OK to merge after #2358.

**Comment by gassmoeller** [comment]
Nice catch Anne, I totally did not check the test output :-(. Should be fixed now, same for #2358.

**Comment by tjhei** [comment]
to double-check: is this up to date with the changes in #2358 ?

**Comment by gassmoeller** [comment]
Yes this is exactly the same state.

**Pull request merged**
