### PR TITLE
do not create temperature matrix for first_timestep_only_single_Stokes

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by tjhei** [comment]
@tcclevenger FYI

**Comment by tjhei** [comment]
> Looks good. Somehow the upload of the coverage failed, lets see if a rebuild fixes that.

maybe because the commit is older?

**Comment by gassmoeller** [comment]
Hmm, maybe. All other stages succeed and your tester is fine as well so I will merge. We should maybe look into making the coverage upload into a separate stage to clearly distinguish test failures from failure to post results.

**Pull request merged**
