### PR TITLE
Fix some gcc warnings

### PR DESCRIPTION
**Pull request by jperryhouts**

### CODE REVIEW

**Comment by bangerth** [comment]
Can you git rebase fixup the second commit into the first?

**Comment by jperryhouts** [comment]
if git can actually push it, then yes. It seems to be having trouble though. I think there's a clog somewhere in the series of tubed that makes up the internet.

**Comment by jperryhouts** [comment]
Oh, there it goes. I thought it was weird that github comments were moving faster than the git client.

**Pull request merged**
