### PR TITLE
Python script that converts the ascii data to netcdf in spherical system

### PR DESCRIPTION
**Pull request by alarshi**
This PR adds a python script to convert ascii data into netcdf in spherical system.
Currently, the output in paraview is still a box with correct field values (figure below). I am not sure how to fix it to get spherical system.
image

@tjhei : Could you review it when you get a chance?

### Before your first pull request:

* [x] I have read the guidelines in our [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md) document.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [x] I have tested my new feature locally to ensure it is correct.
* [x] I have [created a testcase](https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Comment by tjhei** [comment]
I am not sure if the names of the dimensions and of their values have to be identical but this works:
https://github.com/tjhei/aspect/commit/a592b4514ba417b321a1bc3250f8137246162084

**Comment by alarshi** [comment]
Thank you for fixing it! 
I tested that the updated branch gives similar result from the netcdf file output (left) and the aspect output which reads in the ASCII file (right) :
image

Do we want a unit_test for this like in the python script for cartesian coordinates ? Currently, the python file takes an input ASCII file to return the corresponding netcdf file.

**Comment by tjhei** [comment]
unit_test, yes. Why are the results slightly different?

**Comment by alarshi** [comment]
@tjhei: This is not ready yet. The unit tests look okay but I am still testing the netcdf files with similar resolution models.

**Review by tjhei — APPROVED** [review]
very nice

**Comment by alarshi** [comment]
Okay, I am able to reproduce the solution using same resolution (left from ascii input and right is the generated netcdf file):
image

Below are a few observations:
1. The generated netcdf file is 51 MB compared to 126 MB in the ASCII file
2. It is still annoying to preview the generated files in paraview directly, because paraview expects `latitude, longitude` in degrees, but  we can't use this as structured data in aspect, which needs columns in spherical coordinates (radians)
3. For multiple fields, it is important to note the order in which the data is loaded. This means that if we have `coordinates field_1 field_2` in the ascii data, we need to assign data first for `field_1` and then `field_2`. This was most strange to me and hardest to figure out why.

**Comment by tjhei** [comment]
part of #5447

**Review by gassmoeller — APPROVED** [review]
If I understand correctly this now works and can be merged. Thanks for the script @alarshi!

**Pull request merged**
