### PR TITLE
improve bib file check

### PR DESCRIPTION
**Pull request by tjhei**
catch (and fix) all warnings

### CODE REVIEW

**Comment by tjhei** [comment]
I am not sure what I am doing wrong. @gassmoeller Do you have an idea why it fails?

**Comment by tjhei** [comment]
Ok, things seem to be working correctly now! (some of the ubuntu downloads have been failing regularly today, so I had to restart the checks).

**Review by gassmoeller — APPROVED** [review]
Great, looks ready.

**Comment by tjhei** [comment]
I take that as a permission to merge. :-)

**Comment by gassmoeller** [comment]
:+1: Yes, the testers were not done when I wrote that.

**Pull request merged**
