### PR TITLE
remove invalid tests/

### PR DESCRIPTION
**Pull request by tjhei**
There is no corresponding .prm so I don't know what to do except
deleting the output files.

### CODE REVIEW

**Comment by tjhei** [comment]
I left replace_lithosphere_viscosity_file in there and will make a separate PR.

**Comment by gassmoeller** [comment]
Please also leave particle_multiple_output_formats untouched, I opened #3202 to fix that. Afterwards feel free to merge yourself.

**Comment by tjhei** [comment]
done, but I want to wait for the tester...

**Comment by gassmoeller** [comment]
Tester is happy. Good to go.

**Pull request merged**
