### PR TITLE
Fix initial guess

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by tjhei** [comment]
please wait until the tester finishes...

**Comment by bangerth** [comment]
Does this have any effect on the number of inner iterations?

If not, please squash into one commit and merge.

**Comment by tjhei** [comment]
Inner iterations change slightly for a few tests especially those that have a null space. See 9698f9a. Most tests did not change, though.

That means the destination vectors are already zero for most tests.

**Comment by bangerth** [comment]
Yes, I observed this as well yesterday that most of the time the dst vectors are zero (the dst vectors are temp vectors inside GMRES, and are probably zero every time we haven't done a restart yet).

Like I said, squash and merge.

**Comment by tjhei** [comment]
> Like I said, squash and merge.

You want me to squash the commit with the test output fixes and the other one? I prefer to keep them separate.

I will merge when the tester is through...

**Comment by bangerth** [comment]
Yes, I think we should keep changes to code, the changes.h file, and to the testsuite atomic so that whichever location in the commit history you choose, they are all in synch. In particular, this way the checked in test results always match what the code produced with the then current sources.

**Comment by tjhei** [comment]
Interesting. I always want to be able to look at the history and ignore the gigantic test related commits and see the important code changes only. Note that going back in time on master always taking the left parent only hits the merge commits so you are always at a consistent state:
```
git log --first-parent
```

**Comment by bangerth** [comment]
Fair enough. Do at your discretion :-)

**Pull request merged**
