### PR TITLE
Only use reference strain rate during the first nonlinear iteration in viscoplastic material model

### PR DESCRIPTION
**Pull request by anne-glerum**
As described in #5736, the reference strain rate is intended to be used only during the first nonlinear iteration when the strain rate is still zero at timestep 0. During later nonlinear iterations and timesteps, a strain rate that is too low is already caught by the parameter min_strain_rate that sets a minimum strain rate value.

The condition in line 265 can be removed as `effective_edot_ii` has been set to `edot_ii` which has remained unchanged from the first time it was set to `ref_strain_rate` or the real strain rate.

Would it be useful to have a check in parse_parameters() that makes sure `ref_strain_rate >= min_strain_rate` or to cap the `ref_strain_rate` with the `min_strain_rate` when it is used?

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [ ] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Comment by tjhei** [comment]
I think an assert to check it is larger than min would make sense

**Comment by anne-glerum** [comment]
Okay, I've added the Assert :)

Four tests fail:

1. continental_extension: in the second timestep the residual of the only nonlinear iteration drops by 3 orders.
2. visco_plastic_yield_strain_weakening_defect_corr_stokes: in the second timestep the initial Newton residual and relative nonlinear residual change, but they stay the same order of magnitude.
3. viscoplastic_melt_blob_freezing: the viscosity in the gnuplot output increases. This test uses the default values of the viscoplastic material model; the lower strain rate probably leads to the viscosity increase.
4. viscoplastic_melt_blob_freezing: same as for 3.

**Comment by anne-glerum** [comment]
I tried running the repo cookbook both on main and on this branch (changing the solver to single Advection, iterated Stokes) on my laptop. Convergence is very bad and I had to restrict the maximum number of nonlinear iterations to 5. For timestep 0 and 1, the solution is the same unfortunately. 

The test has a lower resolution and uses only 1 nonlinear iteration (and a different way of specifying the same initial temperature). If I decrease the resolution of the cookbook to the test resolution, but use 20 nonlinear iterations, again main and this branch produce the same results.

Restricting the number of nonlinear iterations to 1 still gives the same results, so I cannot reproduce the tester's changed results. The change in this PR would only have an effect if there are points in the domain where the strain rate is ~0, and looking at the strain rate of timestep 0 in ParaView, the lowest strain rate is on the order of 1e-17 1/s.

**Comment by anne-glerum** [comment]
For completeness, here the results for the iterated Newton solver.
main:
```
*** Timestep 0:  t=0 years, dt=0 years
   Initial Newton Stokes residual = 3.14159e+14, v = 2.70823e+14, p = 1.59218e+14
      Relative nonlinear residual (Stokes system) after nonlinear iteration 1: 1
*** Timestep 1:  t=20000 years, dt=20000 years
   Initial Newton Stokes residual = 1.82575e+14, v = 1.81636e+14, p = 1.84963e+13
      Relative nonlinear residual (Stokes system) after nonlinear iteration 1: 0.0782348
*** Timestep 2:  t=40000 years, dt=20000 years
   Initial Newton Stokes residual = 6.30132e+14, v = 6.2938e+14, p = 3.07775e+13
      Relative nonlinear residual (Stokes system) after nonlinear iteration 1: 0.0425342
```
this branch:
```
*** Timestep 0:  t=0 years, dt=0 years
   Initial Newton Stokes residual = 3.14159e+14, v = 2.70823e+14, p = 1.59218e+14
      Relative nonlinear residual (Stokes system) after nonlinear iteration 1: 1
*** Timestep 1:  t=20000 years, dt=20000 years
   Initial Newton Stokes residual = 9.30886e+16, v = 9.30886e+16, p = 1.84963e+13
      Relative nonlinear residual (Stokes system) after nonlinear iteration 1: 0.000153442
*** Timestep 2:  t=40000 years, dt=20000 years
   Initial Newton Stokes residual = 9.36565e+16, v = 9.36565e+16, p = 3.07775e+13
      Relative nonlinear residual (Stokes system) after nonlinear iteration 1: 0.000286175
```

**Comment by naliboff** [comment]
@anne-glerum - For reference, I saw a noticeable change in convergence behavior using a modified (added elasticity, use full Newton solver, other changes) version of the continental extension cookbook when I manually reduced the reference strain rate to the same value as the minimum strain rate. 

I'm a bit surprised the test for the [Kaus brick benchmark](https://github.com/geodynamics/aspect/blob/main/tests/visco_plastic_vep_brick_extension.prm) was not affected, which runs for a few time steps and does multiple nonlinear iterations.

Regardless, I agree with @gassmoeller that the changes to the continental extension cookbook test make sense.

**Pull request merged**
