### PR TITLE
Evaluate cell center instead of vertices for min/max mesh refinement function

### PR DESCRIPTION
**Pull request by anne-glerum**
This addresses #4521: instead of evaluating all vertices of a cell to see whether they should refine/coarsen according to the min/max refinement functions, only the cell center is evaluated. This should avoid differences in refinement due to round-off e.g. along a specified depth level that coincides with cell boundaries.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [x] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [x] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Comment by anne-glerum** [comment]
PS I didn't add a test, because there are several tests for the min/max refinement functions already, but I think a change log might be useful?

**Comment by tjhei** [comment]
Yes, please add a changelog as it is a change in behavior.

**Review by tjhei — APPROVED** [review]

**Comment by anne-glerum** [comment]
Alright, I've added a change log, and I looked at the failing tests. For three tests I modified the refinement settings so that they show the same levels of refinement as before. For these tests, the center of the coarse elements did not meet the minimum refinement criterion, so they weren't refined any more. I'll update the test results once the tester is done.

**Review by tjhei — APPROVED** [review]
Looks great!👍

**Comment by anne-glerum** [comment]
Okay thanks, test results are updated.

**Review by tjhei — APPROVED** [review]

**Comment by bangerth** [comment]
Thanks!

**Pull request merged**
