### PR TITLE
Added copyright statement to 14 .cc benchmark files that did not have…

### PR DESCRIPTION
**Pull request by ljhwang**
Added copyright statement to 14 .cc benchmark files that did not have a copyright header.

### CODE REVIEW

**Comment by bangerth** [comment]
These have the same issues with the missing empty lines :-(

**Comment by bangerth** [comment]
Hm, the astyle machine failed but refuses to show its output -- @tjhei ?

**Comment by tjhei** [comment]
it is now visible.

**Comment by bangerth** [comment]
I think I fixed the indentation.

**Pull request merged**
