### PR TITLE
Augment the documentation of the particle integrators.

### PR DESCRIPTION
**Pull request by bangerth**
This came out of a discussion with @egpuckett .

### CODE REVIEW

**Comment by egpuckett** [comment]
I don't think that rk_4.cc is a correct implementation of fourth-order Runge-Kutta. I think this is borne out by the fact that when Rene ran it with Prescribed-Stokes flow = circle.cc he found it was second-order or third-order accurate (I forget which). I think it would be best if rk_4.cc is fourth-order accurate. I believe we can test this by running it with Prescribed-Stokes Flow = circle.cc. 

Do you agree?

I'm happy to the work, but may not have time until our quarter is over on June 11 or, more likely, during the Hackathon. 

My apologies for being slow to respond. It's the last month or five weeks of our Academic Year and I'm rather overcommitted.

**Comment by bangerth** [comment]
@gassmoeller may have additional insight into this. I think you will only be able to truly observe fourth order convergence if (i) the prescribed flow field is in fact in the finite element space, i.e., is bi-quadratic, and (ii) does not change in time. Both of these appear to be the case for the circle flow. It would indeed be interesting to test things for this flow field and see whether we can really not get fourth order.

**Comment by egpuckett** [comment]
Rene and I had an email exchange concerning this, shortly before he left for EGU, which I cc'd @bangerth. I got the impression @gassmoeller was putting further work on rk4_.cc on the 'back burner', so to speak. However, the issue is still relatively high on my list of things to do; e.g., see #831.

I then implemented a third-order rk_3.cc, since the time-stepping method - assuming the velocities were at least-third order accurate in time - is fairly straight-forward. I was particularly intrigued by the possibility of creating a third-order time stepping algorithm along the lines of what @bangerth said in an email exchange with me and @gassmoeller:

> You actually have access to the velocities not only at t_{n+1} and t_n, but also t_{n-1}. You may be able to fit a quadratic parabola through these three data points and evaluate it at t_{n+1/2}. This should get you one order higher in accuracy. Except in the first time step, where you only have t_n and t_{n+1}. This is what the various use_bdf2 variables check everywhere.

I have been thinking about this, but have not made sufficient progress to implement anything.

However, I sent my basic rk_3.cc code to Rene (by email) for comments. This is code I implemented under the assumption that the velocities (*velocity) and (*old_velocity) are at least-third order accurate in time. Rene responded with  

> Feel free to submit a PR for your RK3 plugin at any time you feel comfortable with it.

I think an rk_3.cc would be useful in and of itself to individuals who use the particles, since we may be able to make it third order in ASPECT as it stands now, This is assuming we can figure out a third order accurate time stepping, say along the lines @bangerth has suggested.

Would @bangerth and @tjhei accept an rk_3.cc?  In other words, would you not be intrinsically opposed to an additional Runge-Kutta method for the particle integration?

**Comment by egpuckett** [comment]
BTW (By The Way) I have invited Rene to present his poster via Adobe Connect to the ASPECT Working Group (WG) here at Davis on Friday May 13 at 10:00 AM PDT.  At first I thought the discussion would revolve mostly around the current capabilities / functionality of the tracer particles and especially the scaling of the algorithms when run in parallel.  However, John Naliboff is very interested in the current functionality vis-à-vis active tracers.

This is a long winded way of inviting  @bangerth, @tjhei, @jdannberg, and anyone else who may be interested to join the Adobe Connect virtual conference at that date and time.

Can you suggest others who I should invite or a method to advertise this?

**Comment by bangerth** [comment]
More choices = more better. Go right ahead with the RK3 integrator pull request!

**Comment by bangerth** [comment]
As for the Adobe Connect meeting: please send an invitation to the ASPECT developers mailing list. Who knows who is interested in this!

**Comment by egpuckett** [comment]
Will do! Thanks!

**Comment by gassmoeller** [comment]
I am jumping late into the discussion, but I feel like you solved most of it already. I think your explanation and documentation is very good Wolfgang, I would have probably formulated it less precise, but the essence is: If the finite-element solution can not accurately describe the velocity field (in space and over time), then the ODE integrator is always bounded by this limitation. I can confirm however that our current RK4 implementation behaves as expected for an analytically known velocity field (4th order, independent of the flow field). I can elaborate a bit on this during the adobe connect meeting.

**Pull request merged**
