### PR TITLE
Merge #783 Remove assembly scratch.explicit_material_model and cleanup

### PR DESCRIPTION
**Pull request by tjhei**
- merge and resolve conflicts of #783
- fix a warning

### CODE REVIEW

**Comment by bangerth** [comment]
If you're ok with it, then so am I. I've looked over #783 earlier today and it looked good to me. Please merge if the tester is happy!

**Comment by bangerth** [comment]
It's a bit unusual that you merged @gassmoeller 's branch into yours and create a merge commit (though of course not wrong). Why not cherry-pick it?

**Comment by tjhei** [comment]
I didn't think about it too hard, but I guess I wanted to keep his original commits intact and make it obvious what I did so I can be blamed if I mess up the merge? :-)

**Comment by gassmoeller** [comment]
Thanks for finishing this, I was offline for a few days. :+1:

**Pull request merged**
