### PR TITLE
GMG: fix order of RHS correction [WIP]

### PR DESCRIPTION
**Pull request by tjhei**
Fix the order of GMG correct_stokes_rhs() and make_pressure_rhs_compatible().

this is on top of #4324

### CODE REVIEW

**Comment by tjhei** [comment]
I am not sure if this makes a difference in test output or if anything else breaks because of it, but this ordering seems correct to me.

**Comment by bangerth** [comment]
I have no idea what this patch does, but have you given some more thought to the issue?

**Comment by gassmoeller** [comment]
@tjhei: any news on this PR?

**Comment by tjhei** [comment]
Interestingly, only 2 tests fail:
[grain_size_ridge](https://ci.tjhei.info/job/aspect/job/PR-4325/186/testReport/projectroot/tests/grain_size_ridge/) converges faster!
[prescribed_dilation_gmg](https://ci.tjhei.info/job/aspect/job/PR-4325/186/testReport/projectroot/tests/prescribed_dilation_gmg/) does not converge

All other PRs are not affected.

**Comment by tjhei** [comment]
I think we can ignore this PR as it doesn't improve anything.

**Pull request closed without merging**
