### PR TITLE
Fix memory postprocessor to output with types::global_dof_index.

### PR DESCRIPTION
**Pull request by spco**
Fixes overflow issues.

### CODE REVIEW

**Comment by bangerth** [comment]
Nice catch. Did you actually hit this?

**Comment by spco** [comment]
Yup, on 256 cores.
```
Number of active cells: 395,617 (on 6 levels)
Number of degrees of freedom: 22,749,589 (11,548,287+519,643+10,681,659)

...

Total system matrix memory consumption: 45170.69 MB.
Total system matrix nnz: -370,850,057
system matrix nnz by block:
1,548,068,911 123,497,487           1
 123,497,487     196,203           1
           1           12,128,857,147

Total system preconditioner matrix memory consumption: 30843.65 MB.
Total system preconditioner matrix nnz: -1,622,766,425
system preconditioner matrix nnz by block:
 534,596,649           1           1
           1   8,747,069           1
           1           12,128,857,147
```

**Comment by bangerth** [comment]
That's a little bit funny :-)

**Pull request merged**
