### PR TITLE
Import global topography with longitudes 0...2*pi.

### PR DESCRIPTION
**Pull request by bangerth**
This updates the topography file I added in #5567 by one @alarshi kindly provided in which the longitudes are in the interval 0...2*pi instead of -pi...+pi.

### CODE REVIEW

**Comment by bangerth** [comment]
Part of #5421.

**Comment by bangerth** [comment]
Well, this now doesn't work because for some reason, the `Chunk` geometry provides longitudes in the range -pi...+pi. I will have to investigate :-(

**Comment by bangerth** [comment]
This is awkward. I pushed a change that changes the `Chunk` geometry to use longitude in the agreed-upon range 0...2pi. This then works for the global topography file provided by @alarshi , but it breaks the existing tests that read the ASCII files in `data/geometry-model/initial-topography-model/ascii-data/test/` that use the previous convention -pi...+pi and have data points for negative longitudes.

How do we want to address this? It seems like whatever convention we choose, we will always break something. Should we just say that we will go with 0...2pi from now on, and adjust the existing test input files?

**Comment by bangerth** [comment]
Does anyone have any thoughts?

**Comment by gassmoeller** [comment]
Sorry for the late response, we are at the GWB hack at the moment. I would say we should enforce the 0..2pi convention consistently everywhere. All other ascii data example files use 0..2pi already, it is just the initial topography that acts differently. Can you reformat the existing test data (or recreate with 0..2pi coordinates)? If that is not much work I would say let's go with that.

**Comment by bangerth** [comment]
Yes, these test input files aren't particularly large, and I should be able to convert them with not too much trouble. My main concern is the incompatibility in case anyone should be using these -- but then I don't know that anyone does. Perhaps it's just something to document clearly in the changelog.

Will get to it over the next couple of days. Thanks for getting back to me, and have fun at the hack!

**Comment by bangerth** [comment]
OK, I've updated the input files and the relatively minor changes in output.

**Comment by bangerth** [comment]
In other words, this is now ready to go!

**Review by gassmoeller — APPROVED** [review]
Looks good to go.

**Pull request merged**
