### PR TITLE
add project to Q1 only viscosity averaging

### PR DESCRIPTION
**Pull request by tcclevenger**
Discussed in https://github.com/geodynamics/aspect/pull/3495. Simply adds "project to Q1 only viscosity" averaging scheme. I added a test which uses solkz.

### CODE REVIEW

**Comment by tjhei** [comment]
This looks good and uncontroversial.

**Comment by gassmoeller** [comment]
Yes looks good. Thanks!

**Comment by tcclevenger** [comment]
Thanks @gassmoeller!

**Pull request merged**
