### PR TITLE
check script for cookbooks

### PR DESCRIPTION
**Pull request by tjhei**
- add script to test cookbooks
- remove broken .prms (Crameri wil be added by Ian soon)
- gplates 3d example will be added by Rene
- update release tasks
- fix blankenbach

### CODE REVIEW

**Comment by gassmoeller** [comment]
Looks good, except I do not understand the parameter changes in blankenbach. Have you checked that the new values actually are the ones from the blankenbach benchmark?

**Comment by gassmoeller** [comment]
In case the change in blankenbach is ok, feel free to merge yourself.

**Comment by tjhei** [comment]
blankenbach was broken and I copied it from tests/blankenbach that works. Didn't you write that one? :-)

**Comment by tjhei** [comment]
I did not look at the output of blankenbach. Are you willing to help with that?

**Comment by tjhei** [comment]
removed blankenbach.prm after discussion with Rene and Juliane...

**Comment by gassmoeller** [comment]
Ok, ready to merge when the tester is ok.

**Pull request merged**
