### PR TITLE
Fix assert two merged boxes in point_in_domain on free surface.

### PR DESCRIPTION
**Pull request by MFraters**
When running a model with this geometry model and a free surface the assert was triggered before the first timestep, which is not consistent with the assert message. I think this should fix it. @anne-glerum Could you look at this?

### CODE REVIEW

**Comment by gassmoeller** [comment]
I do not quite believe this would be the correct solution. Could this error be related to #2362 - the fact that the timestep number before the first timestep is now set to `invalid_unsigned_int` instead of 0? There was a change to `Box` in that PR, but not to `TwoMergedBoxes`, presumably, because there is no test for this case.

**Comment by anne-glerum** [comment]
@MFraters I'd agree with Rene that this is not the correct solution. Changing the timestep number is probably the way to go.

**Comment by MFraters** [comment]
Sorry for my late reply. I think that i should work. I will add a simple test.

**Comment by bangerth** [comment]
Once #2972 , you could probably use the function introduced there to check whether we have started time stepping.

**Comment by MFraters** [comment]
ok, I have now added the test. I can update the code once #2972 is merged.

**Comment by gassmoeller** [comment]
Looks good. Thanks!

**Pull request merged**
