### PR TITLE
WIP: Add get manifold function

### PR DESCRIPTION
**Pull request by MFraters**
This pull request is intended to add a structure for for example initial conditions plugins to have a unified sense of the geometry. The idea is that if get_manifold returns a NULL pointer, that it is a box type of model. If there is a manifold, then use that manifold.

I have added a initial conditions model as an example implementation and test. In the final version of this pull request, the initial conditions model will probably become a .cc file in the test directory.

I am curious to hear what you think of the idea and implementation. If you have any questions, please let me know :)

### CODE REVIEW

**Comment by tjhei** [comment]
> This pull request is intended to add a structure for for example initial conditions plugins to have a unified sense of the geometry.

Can you explain what information you need that you currently don't have? I also don't understand why you need a new class hierarchy instead of using the deal.II ``Manifold``.

To me it looks like you want a more canonical "depth, lat, long" coordinate for every geometry model. Maybe we should extend the interface from ``depth(p)`` to give back three coordinates instead of exposing the manifold?

**Comment by MFraters** [comment]
Hey Timo,

You are right that there is no need of the manifold in the interface, so I removed it and rewrote the rest of the code. 

Yes, more or less. I need functions which go both ways, for different points, potentially unrelated to the current point given to the initial conditions model. Since the manifold is designed to do this, I thought getting direct access to the manifold was the best way of doing this.

**Comment by bangerth** [comment]
What do we want to do with this now? Is it superseded by #1543?

**Comment by MFraters** [comment]
yes, I will close this one.

**Pull request closed without merging**
