### PR TITLE
Add get_model_operator_options function in utilities so operator options don't get out of sync

### PR DESCRIPTION
**Pull request by SophieCoulson**
I added a get_model_operator_options function in utilities which returns "add|subtract|minimum|maximum|replace if valid", and then replaced the list with a call to this function in all the relevant interface.cc files. This way they cannot become out of sync if someone adds a new operator.

### CODE REVIEW

**Comment by tjhei** [comment]
can you please fix the indentation? (``make indent``)

**Comment by SophieCoulson** [comment]
Done!

**Comment by tjhei** [comment]
Thanks. :+1:

**Pull request merged**
