### PR TITLE
Change shared pointer of melt in simulator_access to unique pointer.

### PR DESCRIPTION
**Pull request by MFraters**
split from #1707

### CODE REVIEW

**Comment by bangerth** [comment]
Well, it doesn't compile:
```
/home/dealii/source/source/simulator/core.cc:156:44: error: no matching function for call to â€˜construct_variables(aspect::Parameters<2>&, aspect::SimulatorSignals<2>&, std::unique_ptr<aspect::MeltHandler<2>, std::default_delete<aspect::MeltHandler<2> > >&)â€™
     introspection (construct_variables<dim>(parameters, signals, melt_handler), parameters),
                    ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dealii/source/source/simulator/core.cc:93:44: note: candidate: template<int dim> std::vector<aspect::VariableDeclaration<dim> > aspect::{anonymous}::construct_variables(const aspect::Parameters<dim>&, aspect::SimulatorSignals<dim>&, std::shared_ptr<aspect::MeltHandler<dim> >&)

```

**Comment by gassmoeller** [comment]
Yes there is a corresponding change in #1707 that also needs to be taken over into this PR.

**Comment by gassmoeller** [comment]
Thanks!

**Pull request merged**
