### PR TITLE
Aspect 1.3 DO NOT MERGE

### PR DESCRIPTION
**Pull request by tjhei**
I am just creating this as a PR so we can:
- have the tester run it
- look at the diffs

So, do not merge. :-)

### CODE REVIEW

**Comment by tjhei** [comment]
I messed up the branch to base it on, so the current RC is now www.ces.clemson.edu/dealii/aspect-1.3-rc2.tar.gz

**Comment by tjhei** [comment]
@bangerth Do you have comments/edits for the release announcement at https://github.com/geodynamics/aspect/commit/23b63cafe1d1591825ebdf769dd283d87ef5ee7d ?

**Comment by bangerth** [comment]
Looks pretty good, thanks for doing this! In the announcement, some items are terminated by a period, others are not -- just choose one style.

**Comment by tjhei** [comment]
fixed.

**Comment by bangerth** [comment]
The release announcement doesn't appear to be part of this PR, so I can't check -- but I'm pretty sure you got it right. 

I don't know if you want to merge this PR, but if you do, please go ahead.

**Comment by bangerth** [comment]
On 05/17/2015 09:54 AM, Timo Heister wrote:
> I messed up the branch to base it on, so the current RC is now
> www.ces.clemson.edu/dealii/aspect-1.3-rc2.tar.gz
> <http://www.ces.clemson.edu/dealii/aspect-1.3-rc2.tar.gz>

Other than the warnings addressed in #340, this compiles and runs fine for me. 
I do get 32 test failures, but I probably always do on this machine (haven't 
checked recently). If it works on your "official" tester, then this all looks 
good to me.

Cheers
  W.

-- 
------------------------------------------------------------------------
Wolfgang Bangerth               email:            bangerth@math.tamu.edu
                                 www: http://www.math.tamu.edu/~bangerth/

**Comment by tjhei** [comment]
Yeah, I have it in a separate branch for now: https://github.com/tjhei/aspect/commit/f711d39ab503872be2a63ff30fc57c8153c5c53a

Thanks.

**Pull request closed without merging**
