### PR TITLE
string_to_unsigned_int

### PR DESCRIPTION
**Pull request by tjhei**
required for #5748

### CODE REVIEW

**Review by gassmoeller — APPROVED** [review]
Probably also a good candidate for a deal.II PR. Ready to merge.

**Review by bangerth — CHANGES_REQUESTED** [review]
Why can't you just use `string_to_int` and check that the result is nonnegative?

**Comment by tjhei** [comment]
> Why can't you just use `string_to_int` and check that the result is nonnegative?

Do you mean like this? Or do you mean I should just do this wherever I need to parse unsigned ints?

**Comment by bangerth** [comment]
Yes, something like this, but I was really just thinking of using `string_to_int` everywhere. You probably use this for reading parameters, where the `ParameterHandler` has already checked that the numbers you're parsing are non-negative.

**Comment by tjhei** [comment]
> has already checked that the numbers you're parsing are non-negative.

Yes. Except I then have to somehow convert a std::vector<int> to std::vector<unsigned int> to store it (for example compositional degrees).

**Review by bangerth — APPROVED** [review]
It doesn't hurt to have the function, and we do insist on using `unsigned int` where appropriate.

Might be nice to migrate this to deal.II.

**Pull request merged**
