### PR TITLE
Allow use of 'No Advection, No Stokes' nonlinear solver scheme with the strain rheology module

### PR DESCRIPTION
**Pull request by naliboff**
This PR adds the 'No Advection, No Stokes' nonlinear solver scheme to the list of permitted solvers that can be used with a strain-dependent rheology. 

* [X] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).
* [X] I have tested my new feature locally to ensure it is correct.
* [X] I have [created a testcase](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Review by gassmoeller — APPROVED** [review]

**Comment by gassmoeller** [comment]
You will have to update the test results. Ready otherwise.

**Comment by naliboff** [comment]
@gassmoeller @tjhei - thanks for the quick reviews! Oddly, the indent+documentation tester is saying there was not a suitably recent of deal.II available. I'll restart the tester and see if the same error pops up.

**Comment by gassmoeller** [comment]
We had the same error on a few other PRs too, restarting the tests worked for them.

**Comment by naliboff** [comment]
@gassmoeller - More oddity, the _jenkins.tjhei.info/pr-merge_ tester is saying the _ready to test_ label is required, although it is already there. I tried removing and then reading that label, followed by /rebuild, but the same error came up. I will wait a bit and try restarting the tester again.

**Comment by gassmoeller** [comment]
It just took a while, testers are done now, you can update the test results.

**Comment by bangerth** [comment]
You just need to update the following output files:
```
[1/2] Generating output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/screen-output.diff
FAILED: output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/screen-output.diff 
cd /__w/aspect/aspect/build/tests && /__w/aspect/aspect/tests/cmake/diff_test.sh /usr/bin/numdiff visco_plastic_yield_strain_weakening_no-advect_no_stokes/screen-output /__w/aspect/aspect/tests /__w/aspect/aspect/build/tests ON
******* Error during diffing output results for visco_plastic_yield_strain_weakening_no-advect_no_stokes/screen-output
******* Results are stored in /__w/aspect/aspect/build/tests/output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/screen-output.diff.failed
******* Check /__w/aspect/aspect/build/tests/output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/screen-output /__w/aspect/aspect/tests/visco_plastic_yield_strain_weakening_no-advect_no_stokes/screen-output
******* All of 9 lines of diffs are:
----------------
##10      <==      Writing graphical output:           visco_plastic_yield_strain_weakening_no-advect_no_stokes/solution/solution-00000
##10      ==>      Writing graphical output:           output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/solution/solution-00000

##10      #:4   <== visco_plastic_yield_strain_weakening_no-advect_no_stokes/solution/solution-00000
##10      #:4   ==> output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/solution/solution-00000
@                                                     @@

+++  File "/__w/aspect/aspect/build/tests/output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/screen-output.cmp.notime" differs from file "/__w/aspect/aspect/build/tests/output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/screen-output.notime"
[2/2] Generating output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/statistics.diff
FAILED: output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/statistics.diff 
cd /__w/aspect/aspect/build/tests && /__w/aspect/aspect/tests/cmake/diff_test.sh /usr/bin/numdiff visco_plastic_yield_strain_weakening_no-advect_no_stokes/statistics /__w/aspect/aspect/tests /__w/aspect/aspect/build/tests ON
******* Error during diffing output results for visco_plastic_yield_strain_weakening_no-advect_no_stokes/statistics
******* Results are stored in /__w/aspect/aspect/build/tests/output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/statistics.diff.failed
******* Check /__w/aspect/aspect/build/tests/output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/statistics /__w/aspect/aspect/tests/visco_plastic_yield_strain_weakening_no-advect_no_stokes/statistics
******* All of 9 lines of diffs are:
----------------
##16      <== 0 0.000000000000e+00 0.000000000000e+00 100 1003 441 441 0 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 visco_plastic_yield_strain_weakening_no-advect_no_stokes/solution/solution-00000 
##16      ==> 0 0.000000000000e+00 0.000000000000e+00 100 1003 441 441 0 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/solution/solution-00000 

##16      #:15  <== visco_plastic_yield_strain_weakening_no-advect_no_stokes/solution/solution-00000
##16      #:15  ==> output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/solution/solution-00000
@                                                     @@

+++  File "/__w/aspect/aspect/build/tests/output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/statistics.cmp.notime" differs from file "/__w/aspect/aspect/build/tests/output-visco_plastic_yield_strain_weakening_no-advect_no_stokes/statistics.notime"
ninja: build stopped: subcommand failed.

CMake Error at /__w/aspect/aspect/tests/run_test.cmake:14 (MESSAGE):
  *** Test aborted.
```
(You probably ran this test by hand, rather than in the `$BUILD/tests` directory under `ctest`.)

**Review by tjhei — APPROVED** [review]

**Pull request merged**
