### PR TITLE
Elasticity: unconditionally fill elastic outputs

### PR DESCRIPTION
**Pull request by tjhei**
We used to only fill elastic outputs when reaction terms are requested
(meaning strain_rate is provided). This seems to be a bug, because we
don't need the strain rate for this.

This probably fixes a bug in elasticity with GMG, where we do not
request the strain rate in all cases.

related to #4248

### CODE REVIEW

**Comment by tjhei** [comment]
FYI @naliboff @zjiaqi2018 @anne-glerum

**Comment by tjhei** [comment]
This indeed fixes the test that is found to be #4248. Ready for review/merge.

**Review by gassmoeller — APPROVED** [review]
Looks good to me.

**Comment by tjhei** [comment]
@naliboff Can you check if this changes any of the test output of your GMG tests?

**Comment by naliboff** [comment]
@tjhei - I just compared the tests results for the viscoelastic_stress_build-up problem, and either running the low-resolution test case (1 tilmestep) or regular benchmark to 20 time steps gives identical values for the stress_xx and stress_yy terms, but slightly different values for the much smaller stress_xy terms. Given they were run on the same machine, I'm inclined to merge #4622 so we can check how much the test changes in this PR.

**Comment by naliboff** [comment]
@tjhei - I just ran the bending beam test in #4622 and those results changes in non trivial ways (RMS velocity, etc).

**Review by naliboff — APPROVED** [review]
This looks good to me as well. 

As noted, I think we should  merge first #4622 to have additional elasticity tests to compare against. The bending beam test case results from that PR does change with the fix here. 

Hopefully this resolves the elasticity + mesh deformation issue entirely!

**Comment by gassmoeller** [comment]
Let's get this merged so it does not block the other PRs.

**Pull request merged**
