### PR TITLE
change depth_average zones from 100 to 10

### PR DESCRIPTION
**Pull request by tjhei**
In each cell we place 10 quadrature points, which means 100 zones
require probably 50 cells in depth direction, which typical computations
do not have.

Example:
depth_average_broken

### CODE REVIEW

**Comment by tjhei** [comment]
Thoughts?
(need to update test output before we merge)

**Comment by gassmoeller** [comment]
Seems reasonable to me. High resolution models can still set it to higher values for their purpose, but these weird results for low resolution will confuse users.

**Comment by bangerth** [comment]
Looks good to me. Please add a sentence to changes.h in the incompatible section and merge.

**Comment by tjhei** [comment]
We don't have an "incompatible" section. Okay like this?

**Comment by bangerth** [comment]
Yes, looks good. If you don't have other things you want to change, please merge.

**Pull request merged**
