### PR TITLE
Change the representative point to include initial topography in the box model geometry

### PR DESCRIPTION
**Pull request by Djneu**
This PR is a small fix to include the initial topography in the representative point for the box model geometry. When using initial topography with adiabatic conditions, a floating point exception happens while computing the adiabatic profile. This seems to occur because when the compute_profile::get_property function calls the geometry depth function the representative point does not include the initial topography while the depth calculation does. 

### For all pull requests:

* [X ] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [ X] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests) for the new feature/benchmark in the [tests/](../blob/master/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/master/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Review by gassmoeller — COMMENTED** [review]
I think this is an improvement, but you will have to update the test results.

Also: You compute the topography in the middle of the top surface, but the representative point that is returned is at the south-west most corner. Is there a reason you prefer the middle of the domain? There is no fundamental reason why we should not use the middle, but I think it would be more consistent to use x=0/y=0 as well if we return this as representative point.

**Comment by Djneu** [comment]
Hi both,
Thank you for taking a look at it. I've made the suggested change to clarify the point location, and updated the tests.

**Review by gassmoeller — APPROVED** [review]
Thanks!

**Pull request merged**
