### PR TITLE
[WIP] update gitattributes and release tasklist

### PR DESCRIPTION
**Pull request by tjhei**
- Use gitattributes to exclude files from the release tarball: scripts
and doc/manual/, which is used to generate manual.pdf.
- Update release tasks.- Use gitattributes to exclude files from the release tarball: scripts
and doc/manual/, which is used to generate manual.pdf.
- Update release tasks.
- doc/Makefile: better default target, cleanup, and nice error message if manual/ is missing.

### CODE REVIEW

**Comment by tjhei** [comment]
This is work in progress. We should discuss what other files we can remove. Do you need to be able to:
- run tests
- generate manual.pdf
with a release? If not we could slim down the release quite a bit.

**Comment by bangerth** [comment]
This looks good enough to merge, IMO.

I think we do want the manual to be part of the release. Did you mean whether we want to include the sources for it? We could indeed strip those (in which case one would also need to adjust `doc/Makefile` to give a reasonable error message if it doesn't find the `doc/manual` directory).

Tests: I don't know. I think it creates public trust if we include them :-)

**Comment by tjhei** [comment]
> Did you mean whether we want to include the sources for it?

correct, why would anyone with a release tarball generate documentation or pdf ...

>  We could indeed strip those (in which case one would also need to adjust doc/Makefile to give a reasonable error message if it doesn't find the doc/manual directory).

or nuke everything except manual.pdf from doc/ :-)

**Comment by gassmoeller** [comment]
I agree that probably nobody with a release would try to recreate (or modify) the manual, but I would vote for keeping the tests. It is not only useful to create trust, but also to check if the installation was successful. Even if most of them fail, the results are generally not far off, except something went wrong during the build process.

**Comment by bangerth** [comment]
On 01/26/2015 08:41 AM, Timo Heister wrote:
>     Did you mean whether we want to include the sources for it?
>
> correct, why would anyone with a release tarball generate documentation
> or pdf ...

I think there's a good point to be made about keeping the ability to run 
doxygen locally. I'm ok with the doc/manual directory disappearing.

**Comment by tjhei** [comment]
okay, what about now?

**Pull request merged**
