### PR TITLE
require SUNDIALS and deal.II 9.5

### PR DESCRIPTION
**Pull request by tjhei**
I am not sure if we should delay merging this a bit further, but it would be great to have this in place at some point so we can start merging features requiring it and so we can test installation instructions, CI, etc..

### CODE REVIEW

**Comment by gassmoeller** [comment]
I would prefer if we can combine this change with the switch to requiring deal.II 9.5. That way users will only have to install a new deal.II version once. The first step for that would be to start a new reference tester with 9.5 and include that in the CI.

**Comment by tjhei** [comment]
Sure. :-)

**Comment by tjhei** [comment]
We need for deal.II packaging of 9.5 to finish first...

**Review by bangerth — APPROVED** [review]
I'll approve now already, even though I know that this shouldn't yet be merged.

It would probably be nice (here or in a follow-up) to also output SUNDIALS version information in `source/global.cc` in the `print_aspect_header()` function in the same way as we do for the other dependencies.

**Comment by bangerth** [comment]
What's our timeline for this?

**Comment by gassmoeller** [comment]
soonish. the only missing piece is to switch our reference tester results to the new 9.5 tester.

**Comment by gassmoeller** [comment]
@bangerth @tjhei This should now be ready to merge.

**Review by tjhei — COMMENTED** [review]
Looks good to me. @bangerth ?

**Review by bangerth — APPROVED** [review]

**Pull request merged**
