### PR TITLE
Dependencies

### PR DESCRIPTION
**Pull request by gassmoeller**
This is a continuation of #467 to remove the dependency_ functions from the material models. To fully merge this we should maybe wait for #543, and #450, otherwise we produce some conflicts. I also saw some style things in this one that I will change, I mostly open this to check the test results.

### CODE REVIEW

**Comment by gassmoeller** [comment]
@tjhei, terribly sorry for this, there was an endless recursion in one of the changed tests that I did not see when uploading this PR. I hope it did not crash your tester (as it did twice with my machine), but better check.

**Comment by gassmoeller** [comment]
Ok, this should be ready for review. I did mostly style changes and the test postprocessor was broken. Together with a few wrong dependencies in the material models (probably wrong even before this PR) this caused the tests to fail. After #543 and #450 are merged this will clean up our material models significantly. Now we just need to find a way to get rid of the reference_* functions.

Thanks @moorek for preparing this. I know it is some boring work, but I really like the new (simpler and shorter) material models.

**Comment by tjhei** [comment]
The machine running the ASPECT tests crashed and I can't ssh into it from here. Sadly, I can only press the reset button in about 2 weeks from now. Sorry about that.

**Comment by gassmoeller** [comment]
Dont worry, entirely my fault. I should have checked and tested the whole PR instead of simply re-uploading after I fixed the first problem. Interesting though that this did not happen with #467 (or it did, and we did not notice?). I guess this means no merge for the next two weeks. But since you are busy with deal.II anyway, I guess that is not too much of a problem.

**Comment by tjhei** [comment]
How did your machine crash? Tests should time out after a while. It might be that this was not your fault, though. The machine has crashed before about once a month.

**Comment by gassmoeller** [comment]
One parse_parameters function calls itself recursively and fills all available memory in seconds. I would have expected the program to fail when also the swap was filled, but somehow it simply did not longer respond. Maybe it notices at some point that the 10 minutes are over, but from the reaction of my machine (complete freeze) I would dought it.

**Comment by bangerth** [comment]
On 07/31/2015 02:04 PM, Rene Gassmöller wrote:
> One parse_parameters function calls itself recursively and fills all
> available memory in seconds. I would have expected the program to fail
> when also the swap was filled, but somehow it simply did not longer
> respond. Maybe it notices at some point that the 10 minutes are over,
> but from the reaction of my machine (complete freeze) I would dought it.

Yes, most machines are configured in a way that allow them to use a 
significant amount of swap space (say, twice as much as they have main 
memory). But because disks have become so slow relative to memory 
accesses, when you have a memory-eating infinite loop, this leads to a 
very long phase where the operating system tries to swap stuff out or 
in, and doing so for many GB of memory takes a long time before the 
system finally gives us and kills the job (or, possibly, other jobs that 
would otherwise have been important for a running system). Running out 
of memory is a pretty insidious way of making sure the people in front 
of the machine is not having fun.

**Comment by gassmoeller** [comment]
Ok, #543 and #450 have been merged and included in this PR. When the tests pass this should be ready for review.

**Comment by bangerth** [comment]
@gassmoeller -- can you please rebase so I can merge?

**Comment by gassmoeller** [comment]
Rebased. Feel free to merge.

**Pull request merged**
