### PR TITLE
www: update cite.html

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by gassmoeller** [comment]
The website itself has no option yet for 2.2.0 so the link still recommends the following text: `Computations were done using the ASPECT code version 2.1.0, see \cite{KHB12,heister_aspect_methods2,aspect-doi-v2.1.0}.` and the following reference:
```
@misc{aspect-doi-v2.1.0,
  title        = {{ASPECT} v2.1.0 [software]},
  author       = {Wolfgang Bangerth and
                  Juliane Dannberg and
                  Rene Gassmoeller and
                  Timo Heister and
                  others},
  month        = apr,
  year         = 2019,
  DOI          = {10.5281/zenodo.2653531},
  URL          = {https://doi.org/10.5281/zenodo.2653531},
  organization = {Computational Infrastructure for Geodynamics},
  address      = {Davis, CA},
}
```

Is that part of a follow up?

**Comment by ljhwang** [comment]
Yes. The release package still needs be created on the website.

Best,
-Lorraine

*****************************
Lorraine Hwang, Ph.D. - Director
Computational Infrastructure for Geodynamics
UC Davis
530.752.3656
geodynamics.org

**Comment by tjhei** [comment]
> The website itself has no option yet for 2.2.0 so the link still recommends the following text

yes, working on it. #3576 and then the follow-up to update the database.js

**Comment by tjhei** [comment]
if you want we can wait with this PR until the others are merged.

**Pull request merged**
