### PR TITLE
Replace std::shared_ptr by std::unique_ptr in the heating models.

### PR DESCRIPTION
**Pull request by bangerth**
Strictly speaking, this is an incompatible change because the heating model manager
exports its list of heating models. I suspect that few plugins we don't have
in the tree ourselves (which I have all converted) make use of this.

Related to #2375 and #2811.

### CODE REVIEW

**Comment by tjhei** [comment]
```
The following tests FAILED:
	312 - material_model_dependencies_tangurnis (Failed)
	584 - tangurnis_ba (Failed)
	585 - tangurnis_ba_custom (Failed)
	586 - tangurnis_tala (Failed)
	587 - tangurnis_tala_c (Failed)
	588 - tangurnis_tala_implicit (Failed)
``
should we delay this change until after 2.1? I am more happy to break things then.

**Comment by bangerth** [comment]
Let's try this again. 
/rebuild

It's ok with me if we want to postpone this until after the release. I realize that it's an incompatible change. Anyone got an opinion on a changelog entry?

**Comment by gassmoeller** [comment]
Unless you have checked all benchmarks and cookbooks I would vote for postponing this after the release. Who knows what hidden plugins rely on this (ideally we should have a test for all cookbooks and benchmarks of course).

**Comment by gassmoeller** [comment]
Since we branched off the release we can merge this. About the changelog entry: Do we require changelog entries that change the API, or only entries if we change the parameter files? I do not think we had many entries with interface changes, so maybe we just go ahead and merge this? Users who found and used this function can likely find it again and change the type.

**Comment by bangerth** [comment]
Let me know what you prefer and I'll do it. I don't feel strongly.

**Comment by gassmoeller** [comment]
Lets just merge it. I think the function is not used widely.

**Pull request merged**
