### PR TITLE
Fixes and minor updates to dynamic friction

### PR DESCRIPTION
**Pull request by naliboff**
Address issues #1773 and #1774. A limit for the minimum viscosity is also applied.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Looks good. Ready to merge if the tester is happy.

**Comment by gassmoeller** [comment]
Oh, please rebase and solve the conflict before that.

**Comment by naliboff** [comment]
Rebased :+1:

**Comment by bangerth** [comment]
Thanks for the quick fixes!

**Pull request merged**
