### PR TITLE
I changed the shell script to end in .sh as is convention.

### PR DESCRIPTION
**Pull request by orionjohnston**
I changed the shell script to end in .sh as is convention.

### CODE REVIEW

**Review by bangerth — CHANGES_REQUESTED** [review]
You added the renamed version, but did not delete the old version. Would you mind doing that too?

**Comment by orionjohnston** [comment]
I changed all benchmark run_all_models shell scripts to .sh. The shell script I wrote should have removed the old files but I am still figuring out git.

**Comment by orionjohnston** [comment]
Please wait, small mistake

**Comment by orionjohnston** [comment]
Ok, the typo should be fixed.

**Review by orionjohnston — COMMENTED** [review]
Still learning github but the problem should be fixed as well as modifying similar files in benchmarks to end in .sh.

**Review by gassmoeller — APPROVED** [review]
Looks good, thanks for cleaning up the repository!

**Review by bangerth — APPROVED** [review]

**Review by bangerth — CHANGES_REQUESTED** [review]
Actually, on second thought, would you mind combining all four commits into one? Feel free to find me or anyone else to walk you through the process.

**Review by bangerth — APPROVED** [review]

**Pull request merged**
