### PR TITLE
post 2.5.0 release

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by tjhei** [comment]
tests should be fixed with #5185

**Comment by tjhei** [comment]
This is ready to merge.

**Comment by MFraters** [comment]
rebase now https://github.com/geodynamics/aspect/pull/5185 is merged? Or should this be merge as soon as possible before the other pull requests start coming in?

**Comment by tjhei** [comment]
I rebased.

**Review by MFraters — APPROVED** [review]
Looks good to me.

**Review by bangerth — COMMENTED** [review]
Doesn't merging the changelog into one have to happen *before* the branch, not after the branch?

The versioning changes are of course ok.

**Comment by tjhei** [comment]
> Doesn't merging the changelog into one have to happen _before_ the branch, not after the branch?

The commits are also included in the aspect-2.5 branch, see https://github.com/geodynamics/aspect/commits/aspect-2.5

**Comment by bangerth** [comment]
I see. Thank you!

**Pull request merged**
