### PR TITLE
Update citation recommendation

### PR DESCRIPTION
**Pull request by ljhwang**
Updates credit and citation (Section 1.1) information by adding version
number to manual, explicitly requesting citation of manual and
additional motivational language.

### CODE REVIEW

**Comment by bangerth** [comment]
See also #1092. The same changes now also have to be done on the website.

**Comment by tjhei** [comment]
Args, I didn't look at this earlier. I don't think this will work. Version 1.5.0 might never exist so we need to reference the last released version.

**Comment by bangerth** [comment]
Oh, bummer. Right. How do we proceed?

**Comment by ljhwang** [comment]
1.5.0 refers to what I found in the VERSION file. So unless someone automates this, this will need to be updated _everytime_ there is a new release. Like, one more thing to forget, right?

**Comment by bangerth** [comment]
That's what we have a release task list for, see https://github.com/geodynamics/aspect/blob/master/doc/release-tasklist

**Pull request merged**
