### PR TITLE
Active particle benchmarks

### PR DESCRIPTION
**Pull request by hlokavarapu**
Part 3 of PR #1319:

- Added SolCx, SolKz, and Inclusion benchmarks using active particles.

Contributed by A. Kaloti (@aaronistheman), J. Jiang (@jonny97), H. Levinson (@Tester12453), N. Nyguen (@ngocng05), @yinghe616 and @egpuckett.

### CODE REVIEW

**Comment by bangerth** [comment]
@gassmoeller -- would you be willing to look at this?

**Comment by bangerth** [comment]
By the way, are the material models and everything else that is in the .cc files exactly the same as what's already in `benchmarks/*`? (Same for #1345.) If that is the case, maybe we can find a way to not duplicate the code three times over.

**Comment by gassmoeller** [comment]
I can look at this and #1345. @hlokavarapu: I would really prefer to not  duplicate the code as @bangerth suggested. You could for example include the new benchmarks as subdirectories in the existing folder `benchmark/inclusion` and `benchmark/solkz`, as it is already done for the `tangurnis` benchmark. If there are minor differences we can figure something out (e.g. an input parameter switch or derived classes from a base class), but avoiding code duplication makes our live maintaining the whole code so much easier.

**Comment by bangerth** [comment]
I could also live with replacing the contents of the `.cc` file by something like `#include "../inclusion/inclusion.cc", but @gassmoeller's suggestion is of course much nicer.

**Comment by hlokavarapu** [comment]
@gassmoeller, in order to reduce code duplication, I have used SolKz compositionial field as a starting point. If all the loose ends are taken care of in #1345 , I will then follow up and refactor the active particle benchmarks similarly.

**Comment by hlokavarapu** [comment]
Split this PR into parts based on benchmark.

#1498

**Comment by gassmoeller** [comment]
Is this superseded by #1539 and #1498? If so, please close.

**Comment by hlokavarapu** [comment]
This PR has been superseded by PRs #1539, #1498, and #1633.

**Pull request closed without merging**
