### PR TITLE
Multi VoF field correction

### PR DESCRIPTION
**Pull request by class4kayaker**
I ran into another volume of fluid edge case that I had not explicitly checked due to assuming it was covered by existing tests.
If multiple VoF fields were used, they were not associated with the correct compositional fields due to using incorrect indexes in the map (source was forgetting about the indexes including temperature).

This both corrects the implementation, and adds a postprocessor to an existing test to ensure that it remains correct.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Ok, looks good to me. You will need to `make indent` to fix the style.

**Comment by class4kayaker** [comment]
Force pushed  indentation correction commit to force new check.

**Comment by gassmoeller** [comment]
Looks good. Thanks!

**Comment by bangerth** [comment]
In reference to #835.

**Pull request merged**
