### PR TITLE
Avoid compiler warnings for a test.

### PR DESCRIPTION
**Pull request by bangerth**
The `.cc` file that goes with this test has numerous unused arguments and variables that show up when you do `ctest -V`.

/rebuild

### CODE REVIEW

**Review by tjhei — APPROVED** [review]

**Comment by tjhei** [comment]
Interesting. I never use -V but I use ``--output-on-failure`` which you can set automatically if you have ``export CTEST_OUTPUT_ON_FAILURE=1``in your environment.

**Comment by bangerth** [comment]
The test doesn't fail because, I assume, we don't compile with `-Werror`.

**Comment by tjhei** [comment]
That is right. There should be a ton of warnings in other tests...

**Comment by bangerth** [comment]
Yes, I"m sure there are many more warnings in tests.

**Pull request merged**
