### PR TITLE
use SimulatorAccess in mesh deformation

### PR DESCRIPTION
**Pull request by tjhei**
This is the only place I could change to using SimulatorAccess. All
other occurrences require non-const access.

### CODE REVIEW

**Comment by tjhei** [comment]
@gassmoeller FYI

**Comment by gassmoeller** [comment]
Huh, too bad. Even this does not work, because in the constructor the pointer to simulator is not yet initialized (`initialize_simulator` has not yet been called). Maybe we need to postpone the issue.

**Comment by tjhei** [comment]
Well, that is annoying.

**Comment by gassmoeller** [comment]
Yeah, sorry for suggesting it without checking. I appreciate the try though :+1:

**Pull request closed without merging**
