### PR TITLE
new test geoid prm file using Matt's spherical coordinates input

### PR DESCRIPTION
**Pull request by Shangxin-Liu**
Using Matt's new spherical coordinates input to set the single degree 2 order 0 spherical harmonic temperature field, making the test prm file more readable. @gassmoeller  @bangerth @mbweller

### CODE REVIEW

**Comment by Shangxin-Liu** [comment]
It has a minor floating point difference in the other degree/order which is nearly zero on my machine. But the output degree 2 order 0 and degree 0 order 0 terms are still the same as analytic solution.

**Comment by gassmoeller** [comment]
Ready to merge if the tester is happy

**Comment by bangerth** [comment]
Nice simplification!

**Pull request merged**
