### PR TITLE
Fix representative point in ellipsoidal geometry

### PR DESCRIPTION
**Pull request by MFraters**
The representative point was given in degree's, which should have been radians. This patch fixes that.

### CODE REVIEW

**Comment by tjhei** [comment]
Why do you use the middle between NE and SE instead of NE and SW? /run-tests

**Comment by MFraters** [comment]
Good point. I have change it :)

**Comment by tjhei** [comment]
Your changes change the test output slightly. Can you please apply http://www.math.clemson.edu/~heister/cib/aspect-8.4.1b/2b7abfd3f5aa54d432b78f0993ef394c388346cc/changes-gcc.diff ?

**Comment by tjhei** [comment]
:+1:

**Pull request merged**
