### PR TITLE
cmake: do not configure test project every time

### PR DESCRIPTION
**Pull request by tjhei**
The wait is kind of annoying, so only configure the tests when it is
actually needed.

### CODE REVIEW

**Comment by tjhei** [comment]
This is quite an important change. @gassmoeller @jdannberg are you okay with this?

**Comment by gassmoeller** [comment]
I am ok with the test (though I need to change my workflow for it), but only if you update the instructions in the manual in the `Writing tests` subsection, they currently just state you have to run `cmake .` to add a new test.

**Comment by tjhei** [comment]
updated.

**Comment by gassmoeller** [comment]
I talked to @jdannberg and she is fine with the change.

**Pull request merged**
