### PR TITLE
New melt solver

### PR DESCRIPTION
**Pull request by tjhei**
supersedes #1516 and created from my repo so we can edit it

### CODE REVIEW

**Comment by jdannberg** [comment]
I am working on a melt cookbook at the moment that runs on a laptop in a reasonable time (similar to the melt global model from our paper), and once I get that to work I thought I could use it to see how it would work with this pull request (faster/slower, number of iterations, convergence of the nonlinear solver etc...). Does that sound good? Is there anything in particular I should pay attention to?

**Comment by tjhei** [comment]
That would be great! Let me know what you find out.

We are now getting back to this PR. If I remember correctly, things are working okay as long as we don't do nonlinear iterations. If this is related to the melt reactions and how those interact with the new constraints, I don't know. So the first thing might be to just use IMPES.

**Comment by jdannberg** [comment]
I can try that, and I could also try to rebase it to my operator splitting branch (which fixes the melt reactions and the nonlinear solver seems to converge as long as I don't set a melt transport threshold > 0, which I guess is exactly the thing that this pull request should fix with the constraints).

**Comment by tjhei** [comment]
> I could also try to rebase it to my operator splitting branch

also an interesting thing to try!

**Comment by jdannberg** [comment]
I played around a bit with your branch, and I tried a simple test case with a [rising melt blob](https://github.com/jdannberg/aspect/commit/1720a588575dee52252bce97ab4a249b8dc8e545). There are no reactions, it just starts out with a given amount of melt, which then rises upwards. On mainline, it works without problem, but using this branch it crashes in the Stokes preconditioner (both with IMPES and iterated IMPES). I can continue to look into this, but right now I don't really have ideas as to what exactly the problem is or what I should try. It's definitely not the reactions though.

**Comment by tjhei** [comment]
The Schur complement becomes singular for some reason. I can work around this, but then the nonlinear solver is not converging in timestep 1. I assume this is because the area that is below the threshold flips in each iteration. ;-(

**Comment by jdannberg** [comment]
Superseded by #2138.

**Pull request closed without merging**
