### PR TITLE
update screen-output of S40RTS test

### PR DESCRIPTION
**Pull request by Shangxin-Liu**
Here is the test result of the new S40RTS initial condition that also removes degree zero cos and sin coefficients.

### CODE REVIEW

**Comment by bangerth** [comment]
@jaustermann : Since you wrote this model, can you take a look?

/run-tests

**Comment by Shangxin-Liu** [comment]
indentation fixed. Do you know why the astyle-tester continues to show "fail"?

**Comment by bangerth** [comment]
Click on it: http://www.math.clemson.edu/~heister/aspect-astyler-logs/a200284f23877b1f77bd48b3735d8b6920abb2ab/log 
You have a line that has a space or two but nothing else.

**Comment by Shangxin-Liu** [comment]
Thanks. Fixed.

**Comment by Shangxin-Liu** [comment]
I accidentally deleted the previous patch so I created a new one. Can't you merge it from this patch 1? @jaustermann

**Comment by Shangxin-Liu** [comment]
All the revised S40RTS/S20RTS stuff include test output are done. @bangerth @jaustermann

**Comment by jaustermann** [comment]
This patch looks good to me. @bangerth, this also explains why the test results changed so much when I did the first (incorrect) bugfix. Comparing Shangxin's test results with the original test results shows a much smaller difference.

**Comment by bangerth** [comment]
OK. @Shangxin-Liu : Can you please squash the 10 commits into one?

**Comment by Shangxin-Liu** [comment]
Squashed one done. @bangerth

**Comment by Shangxin-Liu** [comment]
Squashed one done. @bangerth

**Comment by bangerth** [comment]
@tjhei : One more for you.

**Comment by Shangxin-Liu** [comment]
@tjhei  I just realized that the test results on your machine may differ a little from VT cluster, you may further update the test results based on your cluster.

**Comment by bangerth** [comment]
@tjhei -- please update test results and merge.

**Pull request merged**
