### PR TITLE
Documentation: Mass Conservation punctuation

### PR DESCRIPTION
**Pull request by ljhwang**
Enforce lower case 'equation'.

### CODE REVIEW

**Comment by tjhei** [comment]
Isn't it common to use Figure, Section, Equation X?

**Comment by ljhwang** [comment]
I concede the point which means we need to change all lower case to upper case ;).

**Comment by bangerth** [comment]
I think the rule is that if you are referencing a specific section, equation, figure with a name/number, then you use uppercase. So that would call for uppercase here. We are probably reasonably consistent for `Figure X`, but not sure about equations.

**Comment by bangerth** [comment]
So this was correct to begin with because it references a concrete equation.

**Comment by ljhwang** [comment]
Idk. But it should be consistent.  

Best,
-Lorraine

*****************************
Lorraine Hwang, Ph.D. - Director
Computational Infrastructure for Geodynamics
UC Davis
geodynamics.org

**Pull request closed without merging**
