### PR TITLE
Update some matrix-free functions

### PR DESCRIPTION
**Pull request by zjiaqi2018**
`gather_evaluate()`  is equivalent to calling `read_dof_values()` followed by `evaluate()`, but might internally use some additional optimizations.

`integrate_scatter()` is equivalent to calling `integrate()` followed by `distribute_local_to_global()`, but might internally use some additional optimizations. 

passed all the tests with gmg. @tjhei

### CODE REVIEW

**Review by tjhei — APPROVED** [review]
Awesome!

**Comment by tjhei** [comment]
If you have other smaller cleanup or optimizations, please go ahead!

**Comment by zjiaqi2018** [comment]
Sure!

**Pull request merged**
