### PR TITLE
Return user-set maximum topography when the initial topography model Function is asked for the max topography

### PR DESCRIPTION
**Pull request by anne-glerum**
The maximum topography is read in from the prm for the `function` initial topography model, but it is not used. This PR returns the user-set maximum topography when the topography model is asked for it. It is not used to restrict topography as given by the function itself, and the user should take care that the value is reasonable.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [ ] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Comment by anne-glerum** [comment]
The four failing tests are all tests that include initial topography through the `function` plugin.

**Review by gassmoeller — COMMENTED** [review]
Yes, this was clearly an oversight. Can you update the test output? Afterwards this is good to go.

**Comment by anne-glerum** [comment]
@gassmoeller I've updated the test results. The failing tests on dealii-master are still all gmg tests with the same error.

**Review by gassmoeller — APPROVED** [review]
Thank you, good to go.

**Pull request merged**
