### PR TITLE
Update flags in postprocessor

### PR DESCRIPTION
**Pull request by bangerth**

### CODE REVIEW

**Comment by tjhei** [comment]
so how come tests were not catching this problem before?

**Comment by bangerth** [comment]
The material models may simply not have accessed the arrays that were uninitialized, or they accessed them and they happened to be zero by chance, or any other possible reason. @jperryhouts found one example in the testsuite that failed because he used the size of `in.positions` for the number of quadrature points instead of `in.pressures`, and they had different dimensions in that particular call to `evaluate()`. The rest I found just by inspection. These postprocessors may not have computed anything wrong *unless* one would call them with a material model that has a location dependent viscosity, for example, which we may simply never have used.

**Comment by gassmoeller** [comment]
Why do you remove the update_gradients from internal_heatings.cc? This may be not used at the moment, but Juliane will change this file with her heating model (#416), and it will need this flag afterwards (to compute the shear heating we will need the gradients).

**Comment by bangerth** [comment]
internal_heating.cc implements the main function as
```
     template <int dim>
      void
      InternalHeating<dim>::
      compute_derived_quantities_vector (const std::vector<Vector<double> >              &uh,
                                         const std::vector<std::vector<Tensor<1,dim> > > & /* duh */,
                                         const std::vector<std::vector<Tensor<2,dim> > > &,
                                         const std::vector<Point<dim> > &,
                                         const std::vector<Point<dim> >                  &evaluation_points,
                                         std::vector<Vector<double> >                    &computed_quantities) const
```
i.e., it doesn't even look at the gradients. There is no need to compute them (at least right now).

**Comment by bangerth** [comment]
I dropped that one commit.

**Comment by gassmoeller** [comment]
Ok, thanks for cleaning this up.

**Pull request merged**
