### PR TITLE
Compositional vectors

### PR DESCRIPTION
**Pull request by jperryhouts**
I had this idea to track vector fields (like anisotropic viscosity directors) with `dim` compositional fields, and for that purpose it's handy to be able to visualize those fields as such. This patch is a bit of a hack, but it gets the job done. Does anyone have a better idea for how I might do this? Perhaps a separate variable which lists "indicators" for which compositions are part of a vector or not?

As it is, this patch will look for a sequence of compositional field names which end with _x, _y,( and _z if in 3d) and will combine those fields as a vector in the output.

### CODE REVIEW

**Comment by bangerth** [comment]
Let's not do it this way. I like keeping things in the plugin categories as far as possible, and for this my suggestion would be to write a viz postprocessor derived from `DataPostprocessorVector` that takes as input parameters from the input file a list of indices (or names, or either) of the fields you want to group together as one vector. In its `compute_derived_quantities_vector` it would then simply copy the selected compositional fields from the input `uh` field into the `dim` components of the output field. What do you think?

**Comment by jperryhouts** [comment]
Sounds good. Is it then possible to have *two* vectors made out of different compositional fields (ie can that visualization plugin be run twice, or output two vectors from one plugin or something)?

**Comment by jperryhouts** [comment]
For example, with something like this I could write `set Names of fields = vec1_x, vec1_y, vec2_x, vec2_y` and get two vector fields in the output (called vec1 and vec2) and no redundant scalar fields. Would that be possible with a plugin?

**Comment by jperryhouts** [comment]
Sorry to split this comment up in to three rambly ones... Just one more thing.

The redundant field thing isn't super important, because I think it is really uncommon that anyone would need this feature and if you do need it you can just put up with the extra file size and write time, but I like the flexibility to have multiple vector fields defined by compositions.

**Comment by bangerth** [comment]
If you want multiple vector fields, you need to go back to the `DataPostprocessor` class that you already had. My preference would be that the list of names (or numbers) you need to specify would be semicolon-separate lists of dim comma-separated names. So, in your case, you'd have to say something like this in the input file:
```
subsection Postprocessing
  subsection Visualization
    subsection Compositional fields as vectors
      set Names of fields = vec1_x, vec1_y ; vec2_x, vec2_y 
```
This allows for simpler error checking, and you can use functions that split a string first by semicolons and then by commas to break the text apart into its proper pieces.

As for suppressing the scalar output in that case -- that'd be more difficult since it requires feedback from the list of viz postprocessors to the visualization plugin. There is not mechanism for this right now. I don't think it's important enough to worry about it -- just output these fields both as scalars and as vectors.

**Comment by jperryhouts** [comment]
Closing. Better alternative implemented in #542

**Pull request closed without merging**
