### PR TITLE
Correctly compute stress for grain size reduction

### PR DESCRIPTION
**Pull request by jdannberg**
The grain size material model now computes the stress that is used to calculate the grain size reduction rate with the viscosity that has been limited between its minimum and maximum given in the input file, rather than with the unlimited viscosity. This is more consistent, because the limited viscosity is the one we use to compute the strain rate (and stress is 2*viscosity_strain_rate).
This updated implementation prevents artificial grain size reduction in regions with large viscosity.

To demonstrate, below is the output of the test case I added (in higher resolution). Top is the new version, bottom is current main. I used traction boundary conditions to make sure all grain size reduction comes from actual forces in the model (the issue gets worse when we prescribe the boundary velocity, because that means we might prescribe a strain rate even in regions with very high viscosity). The streak of low grain size within the lithosphere, where the strain rate is low and the viscosity is above the upper limit of 1e23 Pa s is gone in the new version. 

limit_stress
limit_stress_strain_rate
limit_stress_viscosity

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [x] I have tested my new feature locally to ensure it is correct.
* [x] I have [created a testcase](https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [x] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Comment by jdannberg** [comment]
I have updated the grain size ridge test, which has exactly the same problem. Below are the results if I run that test for 10,000 years (rather than the 500 in the actual test). Top is this PR, bottom is the original. Note that since this is a test case, it is underresolved, and that causes the strange patches of low grain size at the base of the lithosphere that are visible in both images. 
ridge

**Review by MFraters — COMMENTED** [review]
This change makes sense to me. Also nice that you added the testcase you used.

**Review by MFraters — APPROVED** [review]

**Comment by gassmoeller** [comment]
Could you reduce the test output size a bit? Otherwise this is ready.

**Comment by jdannberg** [comment]
I made the test case smaller.

**Review by gassmoeller — APPROVED** [review]

**Pull request merged**
