### PR TITLE
Update SolCx and SolKz benchmarks in tests folder

### PR DESCRIPTION
**Pull request by hlokavarapu**
Update SolCx benchmark and SolKz benchmark in tests directory due to refactoring of the benchmarks in PR #1498 and PR #1539

### CODE REVIEW

**Comment by gassmoeller** [comment]
I am not sure this will work (i.e. if we support header files in tests). But I would like to use a different approach for the tests anyway. Take a look at how tests/shear_bands.cc includes the cc file of a benchmark. The reason I want to use that way is to actually check the code in the benchmark folder, not a *copy* of it that might get changed in a different way.

**Comment by hlokavarapu** [comment]
I ran ctest before creating the pull request and verified that support for header files in tests works. Either way though, I agree with you that fewer copies of these benchmarks in the main branch is for the better. 

Aat the moment though, a number of tests that depend on SolCx include the copy of solcx.cc that exists in the tests directory. For example, sol_cx_2.cc.  will create an issue.

**Comment by tjhei** [comment]
> I am not sure this will work (i.e. if we support header files in tests).

They shouldn't break anything, but we also have not used them yet.

> The reason I want to use that way is to actually check the code in the benchmark folder, not a copy of it that might get changed in a different way.

Good argument. I agree that this is a good approach, though. We should look into all the other tests that made copies at some point.

**Comment by tjhei** [comment]
Why did you close this PR, Harsha?

**Comment by hlokavarapu** [comment]
My intent was to open an issue and another PR to standardize the test cases that depend on SolCx and/or SolKz. However, perhaps this PR is as good as any.

**Pull request closed without merging**
