### PR TITLE
Apply strain weakening before elasticity

### PR DESCRIPTION
**Pull request by anne-glerum**
Currently, viscous strain weakening is applied to the visco-elastic viscosity when elasticity is switched on. It should only be applied to the viscous viscosity determined through diffusion and/or dislocation creep. This change will not matter for viscoplastic models, only for vep ones. 

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [x] I have tested my new feature locally to ensure it is correct.
* [x] I have [created a testcase](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests) for the new feature/benchmark in the [tests/](../blob/master/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/master/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Review by naliboff — COMMENTED** [review]
👍 I agree that this is the right approach and the . I don't recall why we (likely I) set the viscous weakening to occur afterwards. 

Do you think we need a test for this? We already have a test for VP viscous strain weakening, and I'm not sure an additional one is needed. Thoughts from others on this?

**Comment by bobmyhill** [comment]
I think if this PR changes/fixes functionality without breaking any tests, we should add a new test that would have been broken before the fix. Sorry for giving you more work, @anne-glerum. Thanks for catching these things!

**Comment by anne-glerum** [comment]
I found two tests with elasticity enabled, and neither of them has viscous strain weakening. So a test with vep + viscous strain weakening is probably a good idea. Maybe I'll convert a vep benchmark to a test.

**Comment by anne-glerum** [comment]
Ok, I've added a test, not sure it's very meaningful, but it should the ordering should matter for the results. Will update the tester when you agree.

**Review by naliboff — APPROVED** [review]
@anne-glerum - Thanks for adding the test and this fix!

**Pull request merged**
