### PR TITLE
[WIP] Modularize assembly

### PR DESCRIPTION
**Pull request by bangerth**
This is the work we discussed today. It turns out that it requires a lot of work around the seems, and it's not finished nor currently compiles (and won't get finished today because it's already late), but I wanted to put it out there for comment anyway.

What this patch does, in essence, is declare a hierarchy of classes for the assembly of linear systems (currently at the top of `simulator.h`) and implement them in `assembly.cc`. The changes in `assembly.cc` look massive but in reality they just pertain to moving existing functions out of `Simulator` and modifying them in such ways that they can stand alone and access what they need via `SimulatorAccess` -- there really is no magic here at all, it's just moving code around. The only other interesting piece is the creation of these objects in `core.cc`. 

In essence, `simulator.h` and `core.cc` are the only interesting pieces of the patch.

### CODE REVIEW

**Comment by jdannberg** [comment]
@bangerth , thanks for working on this!
René and I had a look at it, and we had some ideas. When we discussed this last time (also with Timo), we thought it might be a good idea to be able to add different plugins instead of only selecting one plugin that then has to implement all of the terms in the assembly. This would have the advantage that we would not need to duplicate code for the plugins, but every plugin would just have the terms (and the required variables) that it needs. And another place in the code would then define which combination of plugins are BA, EBA, and so on. I thought about this as plugins with functions that modify the data.local_matrix and data.local_rhs in the new class, but leave everything else that is needed for all of the plugins (like filling the scratch object and computing material model inputs) at its original place in the assembly. 
What do you think about that? @tjhei , did we summarize this correctly?

PS: What about the advection sytem residual? Do we have to modify that too?

**Comment by bangerth** [comment]
On 12/19/2015 12:13 AM, Juliane Dannberg wrote:
> @bangerth <https://github.com/bangerth> , thanks for working on this!
> René and I had a look at it, and we had some ideas. When we discussed this
> last time (also with Timo), we thought it might be a good idea to be able to
> add different plugins instead of only selecting one plugin that then has to
> implement all of the terms in the assembly. This would have the advantage that
> we would not need to duplicate code for the plugins, but every plugin would
> just have the terms (and the required variables) that it needs. And another
> place in the code would then define which combination of plugins are BA, EBA,
> and so on. I thought about this as plugins with functions that modify the
> data.local_matrix and data.local_rhs in the new class, but leave everything
> else that is needed for all of the plugins (like filling the scratch object
> and computing material model inputs) at its original place in the assembly.
> What do you think about that?

Yes, that was on my list. I think this can easily be done via a boost::signal, 
or just a list of assembler objects. For the moment, I just wanted to do it in 
a way that it produces the same output and shows the direction for others to 
comment on.


> PS: What about the advection sytem residual? Do we have to modify that too?
Yes, that too. I ran out of time that evening. It needs to be added to the list.

**Comment by tjhei** [comment]
I would prefer handling the Stokes preconditioner outside of these new assembly components. The assembler doesn't need to know, if it is operating on the preconditioner or the main system. It would be easy to add a variant of the Stokes operator that assembles the diagonal blocks. This would allow us to play with the way we construct it or optionally skip doing it altogether to save memory.

**Comment by tjhei** [comment]
My vision was to have smaller and more modular objects that can assemble certain parts of the PDE. This makes them composable and the whole approach very flexible. Otherwise we need to make copies of the code for every single combination. I was thinking along the lines of:
- Stokes block (incompressible)
- Stokes block with full tensor
- compressible terms (to be combined with the one above)
- separate temperature terms

The separation should probably be on a lower level (filling local vectors/matrices?). I am not sure how to handle the scratch objects, though (who fills them and what is needed). Ideally, we also figure out a way to compute residuals directly instead of using the matrices as right now (yuck).

**Comment by tjhei** [comment]
>  @tjhei , did we summarize this correctly?

Yes, I think that makes it more flexible and gives a lot less duplication.

**Comment by bangerth** [comment]
@tjhei -- I agree that composability would be nice. I think the `boost::signal` mechanism I outlined would provide for this nicely. I'll work on this over the next few days.

As for breaking out the Stokes preconditioner part -- that's tricky. I think the way you're seeing it is that *every* assembler (whether for the Stokes system, the temperature system, or the preconditioner) is simply *just another* assembler, and that we should just queue them one after the other. But that's not so trivial: the assemblers for different components get called at different times, and they have different interfaces. So I do need a base class with several member functions.

Of course, we could decide that each derived class simply only implements one of these member functions and leaves the others as no-ops. Then we could just have a grab bag of assemblers that will *all* be called whenever something needs to be assembled; most of the ones in the bag will simply do nothing at all. Is that what you have in mind?

@jdannberg -- yes, the residual assembler also still needs to move there. I hadn't realized this right away, and so didn't have it in the first version of this patch before running out of time that night and wanting to upload it for comments.

**Comment by tjhei** [comment]
> But that's not so trivial: the assemblers for different components get called at different times, and they have different interfaces.

I think the Stokes matrix and Stokes preconditioner could have the same interface: as an input an FEValues and a scratch object and as an output a local matrix/vector.

I don't think we have to get the interface right the first time, either. This is not user-facing (at first), so we can have it evolve as we go.

**Pull request closed without merging**
