### PR TITLE
Make dg limiter field specific

### PR DESCRIPTION
**Pull request by gassmoeller**
Currently the DG limiter can only be enabled for all compositional fields, or no fields. This PR allows to switch it on selectively for some fields. However, it is not working yet, and I dont see why. At the moment for the attached test it does not seem to limit anything. I will look more into it tomorrow.
@anne-glerum: FYI

### CODE REVIEW

**Comment by anne-glerum** [comment]
@gassmoeller Thanks for making the limiter field specific! Looking at the prm file there are 2 fields with an initial maximum value of 3 and they are limited to maximum values of 1 and 2. The composition statistics show maximum values of ~1 and ~2, so they are limited. The minimum value is a bit more off, about 3%. Maybe it would be better without the adaptive mesh refinement?

**Comment by gassmoeller** [comment]
Oh, I should have been more specific about the problem. The test is a copy of the existing test with same name (without the specific field limiter). I did not update the test results, but if I run the new test  locally the limiter is not limiting anything (both fields are still at a value of 3 in the visualization output). I will rerun this today when I have a free minute to make sure I didnt hallucinate yesterday. But I guess my question was: do you see anything wrong with my code?

**Comment by anne-glerum** [comment]
The implementation makes sense to me. The difference in test setups is that you start with values that are over the limits, while the old test does not (max values 2 and 1). Could that have an effect?

**Comment by gassmoeller** [comment]
Maybe, it looks like the limiter is not applied if the whole solution is above the limiter, although I cannot figure out why. I found a good other test though. It has two identical fields and only one is limited and you can see the difference between them in the composition statistics postprocessor. One has overshoots the other one does not.
This PR is ready for another look.

**Review by anne-glerum — APPROVED** [review]
The new test is great, thanks. Looks good!

According to the comment on the limiter in helper_functions.cc, the average over the limited cell doesn't change. So if the whole cell has a composition value of 3, I don't see how it could be limited to 2 and still have the same average:

```
               * Define theta: a scaling constant used to correct the old solution by the formula
               *   new_value = theta * (old_value-old_solution_cell_average)+old_solution_cell_average
               * where theta \in [0,1] defined as below.
               * After the correction, the new solution does not exceed the user-given
               * exact global maximum/minimum values. Meanwhile, the new solution's cell average
               * equals to the old solution's cell average.
```

**Review by bangerth — COMMENTED** [review]
This looks good to em other than @anne-glerum 's comments.

**Comment by gassmoeller** [comment]
Good suggestions, I have updated the parameter description.

> I don't see how it could be limited to 2 and still have the same average

Ah, I completely missed that the limiter cannot change the cell average, I thought it would limit the solution no matter what. Then the behavior makes sense.

Good to go from my side.

**Review by bangerth — APPROVED** [review]

**Pull request merged**
