### PR TITLE
[WIP] Chunk geometry follow-up

### PR DESCRIPTION
**Pull request by anne-glerum**
Dear Wolfgang and Timo,

I’d like to come back to the chunk velocity anomalies of issues #822 and #1016 (and for shells #1077).

As a simple test case, I take the tests chunk_first_timestep_2d.prm and chunk_first_timestep_3d.prm and set all velocity boundary conditions to free-slip except for the zero velocity inner boundary. I add AMR with the following settings:

subsection Mesh refinement
    set Initial adaptive refinement     = 1
    set Initial global refinement          = 4
    set Strategy                                         = minimum refinement function
    subsection Minimum refinement function
     set Coordinate system                    = spherical
     set Variable names                          = r,phi, theta
     set Function expression                 = if(r>5250000.0&phi<45.0*pi/180.0,5,4) #or
   #set Function expression              = if(r>5250000&phi<45.0*pi/180.0&theta>45.0*pi/180.,5,4)
   end
 end

Because there are no driving forces in these test cases, velocity should be as low as possible. For comparison, I reproduce the chunk 2d model with the spherical shell geometry in 2d.  For the original chunk, the following velocity fields are the result (note the different scales; from left to right: shell 2d, chunk 2d, chunk 3d; top: no AMR, bottom: with AMR):
original
original_amr

To improve the velocity fields I made the following changes:

1) Remove manifold id only on boundaries (pr #822)
Remove the manifold only on the domain boundaries, as we discussed at the Hackaton. This removes the anomalies in 2D, except on the cells along the boundaries (at high resolutions, these disappear).
chunk0_amr
2) Setting the proper boundary object (pr #1016)
Since the manifold id is removed on the boundaries, we need a boundary object. Therefore I set the inner and outer boundary to HyperBall, the east and west boundary to StraightBoundary and the north and south boundaries to ConeBoundary.
chunk1_amr
3) Only using the boundary object for normal vectors
As the boundary objects are only necessary (I think) for the normal vectors needed for tangential boundary conditions, I’ve added a new signal around the ‘compute_no_normal_flux’ function in setup_dofs(). These signals are now used to remove the manifold id from the boundaries before the ‘compute_no_normal_flux’ function and set it again after, instead of the reverse before and after refinement. This seems to fix the problems in 2d sufficiently.
chunk3_normalcone

4) ConeBoundary normal vectors
In 3D, there are still anomalies along the conical boundaries of the chunk. As the ConeBoundary object has no normal_vector function, it defers to the StraightBoundary normal_vector function. To give it a try, I’ve added a SpecialConeBoundary class in compat.h that computes normal vectors along a cone, and this reduces the anomalies. 
chunk3_amr

5) Convective pattern
However, we remain with a flow field of ~1e-5 m/yr even though there is no force to drive it. This flow is reduced by an increased resolution. A similar field is seen for no-slip conditions on all boundaries. It is also seen for the original chunk if we filter out the anomalies along mesh refinement boundaries.
When there are lateral variations in mesh refinement, differences in pressure, velocity and strain rate between the differently refined regions are significant. The convective pattern changes, see below. The velocity changes with gravity magnitude and a smaller length scale used for pressure scaling decreases the velocity.
chunk3_noamr_amr
What is your opinion on the above and do you have an idea how to pursue this?

I’ve kept the new chunk model as a separate geometry model in this branch because I was comparing the different models. I’d like to hear what you think about these changes and then I’ll clean everything up.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Hi Anne,
as mentioned in my mails I am not an expert in geometries and manifolds, but I think I have some ideas how to proceed with this PR. There are several layers to the problem though.
As your changes show, the interaction between boundary objects and manifolds can cause issues that we do not quite understand. You propose to remove manifolds from the problematic faces/cells and replace them by boundary objects that do not seem to cause the issues. I do not quite agree with this approach, but would rather want to fix the manifold. Main reason: If I understand correctly the deal.II release 8.5 should be able to handle everything with manifolds, and we will require deal.II 8.5 for the next ASPECT release anyway, so we might as well look for a uniform solution within the framework of manifolds, instead of making complicated changes between manifolds and boundaries (see also #1017). 
*Update*: I just checked deal.II 8.5. Unfortunately we can not yet solve #1017, because `VectorTools::compute_no_normal_flux_constraints` still seems to expect boundary objects and does not accept manifolds. I opened a pull request for that (see dealii/dealii#4183).

Next, I will try to reproduce the anomalies with a chunk geometry that does not longer use boundary objects.

**Comment by gassmoeller** [comment]
It seems a chunk geometry model that only uses the chunk manifold (and a flat manifold at the boundary for the `compute_no_normal_flux` function) is somewhere between 1. and 2. of your accuracy improvement steps in 2D, but even worse than 1. for 3D (see attached figure). For the chunk manifold we should be able to do better (as you have already done for the coneboundary). We could either overload
```
Manifold::normal_vector (const Triangulation<2, 2>::face_iterator &face,
                                      const Point<2> &p) const
```
or
```
ChartManifold<dim,spacedim,chartdim>::
push_forward_gradient(const Point<chartdim> &) const
```
for the chunk manifold, and provide analytical normal vectors or gradients for the straight, cone and spherical boundaries, and use `Manifold::normal_vector` for all faces in the inside. I guess that we should do much better then.

Concerning your residual velocity in step 5. Did you solve that with an iterative solver with default tolerance? Could this be a residual velocity? What happens for a smaller tolerance, or when using a direct solver?


velocity_magnitude_no_boundary_object

**Comment by gassmoeller** [comment]
[Anne Issue](https://trello.com/c/dxIwmRgo/49-anne-issue)

**Comment by anne-glerum** [comment]
Hi Rene, 
Because boundary objects were still expected, I went for removing the manifold from the boundaries and setting boundary objects. I agree fixing the manifold and using the manifold only is the way to go. Good to see https://github.com/dealii/dealii/pull/4183 is merged.

**Comment by anne-glerum** [comment]
Ok, so now only the manifold is needed and we need to provide normal vector descriptions for the manifold. If I understand correctly, the Chart push_forward_gradient is used by the Chart get_tangent_vector which in turn is used by the Manifold::normal_vector function. Maybe then it's more complete to overload push_forward_gradient than overloading Manifold::normal_vector directly?

Concerning the velocity in step 5: I used the default settings of the test: IMPES and a solver tolerance of 1e-7. Decreasing the tolerance to 1e-9 reduces the velocities by an order of magnitude and the velocity anomaly along the cone boundary becomes larger than the velocities along the spherical surface. I haven't tried with a direct solver yet.

**Comment by gassmoeller** [comment]
Yes, implementing `push_forward_gradient` should be simpler. Do you want to give it a try?

Ok, this sounds to me as if the remaining velocities are simply the residual error from the solver. I do not think there is something we can do about that (but the velocities should be small, is this output in `m/year` or `m/s`?). Changing the length scale for the pressure scaling should simply shift the error from the velocities to the pressure, or back.

**Comment by anne-glerum** [comment]
So in chunk_4.cc the `push_forward_gradient` function is overloaded. This greatly reduces the velocity anomalies along edges of refined mesh, but leaves significant differences in pressure, velocity and strain rate between areas of different refinement in 3d:
chunk4_amr_vel
chunk4_3d_amr

The residual velocities are reduced with resolution and solver tolerance, but also increase for lower viscosities (viscosity in the test is set at 1e21 Pas). Aren't residual velocities of ~1e-5 m/yr still a bit high? Along the surface, velocities increase with latitude and along the north boundary, velocity is highest, increasing with depth (see cross section with velocity vectors below). In a chunk that is symmetric around the equator, a velocity pattern symmetric around the equator is seen (i.e. increasing with latitude). 2d chunks lie along the equator and don't show this pattern. I feel like this could be improved, but need some directions where to look. Outputting the normals along the outer and north boundaries shows normalized vectors pointing in the correct, outward direction.
chunk4_3d_crosssection

**Comment by gassmoeller** [comment]
Hi Anne,
I did a number of tries with different parameters (parameter file attached) and your new geometry model. I do not know if there is a single cause for these residual velocities, but things I have found:
- the velocities are mostly independent from AMR now (there are some fluctuations along AMR boundaries, but most of the pattern including the max velocities is independent)
- the anomalies exist also in models that have driving forces (e.g. a small initial perturbation that produces velocities in the same order of magnitude than the anomalies)
- the anomalies also exist in the second timestep
- they converge towards ~0 with resolution with approximately h^3 (for FE degree 2), which is good news, because production runs hopefully have a high enough resolution to keep the anomalies very small:

 degree | max velocity
---- | ---- 
2 | 0.0895
3 | 0.0118
4 | 0.00151

- they strongly converge towards 0 with finite element degree (here for global resolution 3, for the same number of dofs faster than with resolution). This makes me wonder if in general a higher order finite element is needed for curved geometries independent of the structure of the solution? @bangerth do you know if there is theory about this question?

degree | max velocity
---- | ----
2 |  0.0118
3 | 1.64e-05
4 | 2.9e-07 (I suppose this is limited by the solver tolerance)

- using a linear mapping for second order elements **reduces** the maximum velocities from 0.0118 to 0.00221! This is really confusing, I had thought the higher order mapping is necessary to correctly handle this curved surface.

For no reason I can explain, I am somewhat suspicious about the interaction of the manifolds and the `VectorTools::compute_nonzero_normal_flux_constraints` function. If there would be something wrong there it would explain why steps 3. and 4. in your first post helped reduce the errors. I went through that function however, and could not see anything obvious wrong (although it is pretty complicated, so I might have missed something). I also tried replacing the use of the face normal vector given by the manifold, by the face normal vector given by the mapping (less precise, but more consistent with the assembly of matrix terms), but it did not change anything significant.

So for now I am somewhat out of ideas. Maybe we can start replacing boundary objects for other simpler geometries, and see if they work as expected (e.g. spherical shell). 
As far as I understand chunk_4 is already an improvement over chunk? Should we think about merging that first, and open an issue for the remaining anomalies? Or would you prefer to keep looking?

**Comment by bangerth** [comment]
@gassmoeller -- do the tables correspond to the bullet points above or below the table?

In general, theory says that the limiting factor is the *lower* of the polynomial degrees used for the element and the boundary approximation. But this is an asymptotic statement, so it is certainly possible that for finite mesh sizes and particular geometries, we are not yet in the asymptotic regime. Your tables, at least, suggest that we can't be completely wrong since they do show nice convergence.

**Comment by bangerth** [comment]
(The pre-asymptotic issue is what I would suspect to be the issue when dropping from quadratic to linear mappings -- it would be interesting to see whether the linear mapping is consistently better even for finer meshes.

You may also ask why we use degree-4 mappings by default, even though we only use quadratic elements: I did in essence the experiment from which the last table was generated and found that we can get substantially better results -- though not better convergence *order* -- by using p=4. But it did not pay off any further to go to even higher orders, so p=4 was chosen.

The reason why we don't use a higher order polynomial degree for the element is that it doesn't pay off for cases where the viscosity is not smooth. It also relatively quickly becomes too expensive to solve the linear systems.)

**Comment by gassmoeller** [comment]
That makes sense. I agree higher order elements are usually not practical. I am not so much worried about the convergence order, I think @anne-glerum and I mostly worry that the residual velocity for moderate resolutions (4-5) is only 1e-2 - 1e-4 smaller than the magnitude of velocities we are interested in, so our accuracy is significantly reduced (at least close to curved boundaries). Also the residual velocities do not look like noise, they scale pretty uniformly with the curvature of the elements, as if somewhere we use an assumption about non-curved faces. I can test the linear mapping for higher resolution next, currently I am running some tests with spherical shell without boundary objects.

**Comment by gassmoeller** [comment]
Superseded by #1533. The spurious velocities remain, but are much smaller.

**Pull request closed without merging**
