### PR TITLE
CI: run on branches

### PR DESCRIPTION
**Pull request by tjhei**
Run github actions also on branches (important for the releases)

### CODE REVIEW

**Comment by gassmoeller** [comment]
This would trigger the actions on every users fork for every push they make. Can you somehow limit the trigger to geodynamics/aspect or to only the release branches?

**Comment by tjhei** [comment]
> This would trigger the actions on every users fork for every push they make.

That does not harm us or cost anything, I would think?

Anyways. I tried changing it to only test certain branches now. Not sure how we can test this...

**Review by gassmoeller — APPROVED** [review]
Thanks, this looks correct and will save quite a bit of energy ;-).

**Comment by gassmoeller** [comment]
It looks like the actions now dont trigger. Can you try `pull_request:` instead of `pull_request`?

**Comment by gassmoeller** [comment]
Seems to work now.

**Pull request merged**
