### PR TITLE
Removed interface compatibility.

### PR DESCRIPTION
**Pull request by alarshi**
In benchmarks/solkz

### CODE REVIEW

**Comment by tjhei** [comment]
It looks correct, so I am surprised that the output changes. I guess we ignore this slight change and update the results?

**Comment by bangerth** [comment]
@tjhei: Even though this patch changes a file in `benchmarks/`, are there tests that reference the material model?

**Comment by bangerth** [comment]
@tjhei -- no, the output shows errors, and they are a factor of 5-10 smaller than before. We need to figure out what is different here before this can be merged. Something is substantially wrong here.

**Comment by tjhei** [comment]
> @tjhei: Even though this patch changes a file in benchmarks/, are there tests that reference the material model?

Yes. We include the .cc in the test.

> @tjhei -- no, the output shows errors, and they are a factor of 5-10 smaller than before.

One additional Stokes iteration can cause such a difference (errors are small to begin with).

**Comment by bangerth** [comment]
Really? This is crazy. What you're saying is that the total error is completely determined by the iteration error, not the discretization error.

**Comment by bangerth** [comment]
Addresses #1538.

**Comment by tjhei** [comment]
Well, not 100% sure...

**Comment by bangerth** [comment]
Let's leave this for some later time after the hackathon to investigate. We're not going to get to the bottom of it tonight.

**Comment by gassmoeller** [comment]
Found the problem. The `particle_interpolator_bilinear_solkz` test uses a material model that is derived from the SolKzMaterial class, which changed in this PR. The derived model overloads the density and viscosity functions and modifies their behavior. Because of this PR these functions are not longer called, and therefore the modified behavior is never triggered. @alarshi: Please keep this PR as is, except that the new class still needs the `density` and `viscosity` function exactly as they were before. `evaluate` then needs to call these functions to determine the density and viscosity.

**Comment by tjhei** [comment]
I did the fix.

**Comment by bangerth** [comment]
Yes, @tjhei's is the way to go. But can you (@tjhei) run astyle on your patch?

OK to merge if the tester is happy.

**Comment by tjhei** [comment]
Beginner mistake. ;-)

**Pull request merged**
