### PR TITLE
[WIP - Do not merge] Melt assembly

### PR DESCRIPTION
**Pull request by jdannberg**
This is work in progress, we moved to the new assembly structure and want to see if the tests work.

### CODE REVIEW

**Comment by bangerth** [comment]
Wow, more than 250 commits :-( Let me know when you want me to look at this. Of course, in an ideal world you'd first break off littler chunks that build up some infrastructure and that could be reviewed and merged independently first. I don't know whether that's possible here.

**Comment by jdannberg** [comment]
Yes, right now we have 348 commits...
Once we have the new assembly for the advection system, we will restructure everything so that the melt functionality is mostly in separate files, and once this is done it would be great if you could have a look at this, but I don't think it makes much sense before that. We will keep you in the loop :smile:
We already try to make separate pull requests of everything that can be merged independently, and maybe we can break it down into smaller pieces, right now we mainly have the pull request open to see if any of our changes breaks the tests.

**Comment by tjhei** [comment]
Pullrequest planning:
```
mesh_refinement/

postprocess/artificial_viscosity_composition.h

main!
postprocess
doc/manual/* <- split

benchmarks/*
doc/manual/cookbooks
doc/manual/* <- split

material_model/simple 
material_model/global

heating_model/

delete? material_model/keller ? or into cookbooks?
delete? cookbooks/melting_test.prm
```

**Comment by bangerth** [comment]
Is this superseded by #894?

**Comment by jdannberg** [comment]
No, this is the whole pull request with the complete history, #894 only has the core functionality squashed into one commit (so it excludes all benchmarks/material models/cookbooks/etc. to make it shorter and easier to review).

**Comment by bangerth** [comment]
I see. So you'll rebase after #894 is merged to get only what's left?

**Comment by jdannberg** [comment]
We can still decide how exactly we want to do this... we probably don't want to keep all of the commits, but it would also be nice if two years of work would end up being more than just three commits or so...

**Comment by bangerth** [comment]
Right. I will be happy to leave it up to you to figure out how to merge the remainder that's not already part of #894.

**Pull request closed without merging**
