### PR TITLE
Switch continental extension to AMG solver.

### PR DESCRIPTION
**Pull request by MFraters**
Implementation of a simple solution #6002. Although the best fix would be to find the issue why the gmg solver fails, setting it to the amg solver will at least fix the cookbook in the main branch for now.

### CODE REVIEW

**Comment by gassmoeller** [comment]
I think it is fair to switch back, we should make sure all cookbooks always work. Can you fix the test results?

**Comment by MFraters** [comment]
@gassmoeller, I fixed the tests.

**Review by gassmoeller — APPROVED** [review]
:+1:

**Review by naliboff — APPROVED** [review]

**Pull request merged**
