### PR TITLE
GMG: rm compute_no_normal_flux_constraints_box/shell

### PR DESCRIPTION
**Pull request by zjiaqi2018**
With `dealii::VectorTools::compute_no_normal_flux_constraints_on_level()`, we can remove `compute_no_normal_flux_constraints_box/shell()` now. @tjhei

### CODE REVIEW

**Review by tjhei — APPROVED** [review]
Very nice!

**Comment by tjhei** [comment]
/rebuild
Can you check and update test results?

**Review by tjhei — APPROVED** [review]

**Comment by zjiaqi2018** [comment]
one test failed...
```

*** Timestep 0:  t=0 seconds, dt=0 seconds
   Solving Stokes system... 0+
--------------------------------------------------------
An error occurred in line <1853> of file <../include/deal.II/lac/la_parallel_vector.templates.h> in function
    dealii::LinearAlgebra::distributed::Vector<Number, MemorySpace>::real_type dealii::LinearAlgebra::distributed::Vector<Number, MemorySpace>::norm_sqr_local() const [with Number = double; MemorySpace = dealii::MemorySpace::Host; dealii::LinearAlgebra::distributed::Vector<Number, MemorySpace>::real_type = double]
The violated condition was: 
    dealii::numbers::is_finite(sum)


Stacktrace:
-----------
#0  /usr/local/lib/libdeal_II.g.so.9.5.0-pre: dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>::norm_sqr_local() const
#1  /usr/local/lib/libdeal_II.g.so.9.5.0-pre: dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>::norm_sqr() const
#2  /usr/local/lib/libdeal_II.g.so.9.5.0-pre: dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>::l2_norm() const
#3  /__w/aspect/aspect/build/aspect: aspect::internal::BlockSchurGMGPreconditioner<aspect::MatrixFreeStokesOperators::StokesOperator<2, 2, double>, aspect::MatrixFreeStokesOperators::ABlockOperator<2, 2, double>, aspect::MatrixFreeStokesOperators::MassMatrixOperator<2, 1, double>, dealii::PreconditionMG<2, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, dealii::MGTransferMatrixFree<2, double> >, dealii::PreconditionMG<2, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, dealii::MGTransferMatrixFree<2, double> > >::vmult(dealii::LinearAlgebra::distributed::BlockVector<double>&, dealii::LinearAlgebra::distributed::BlockVector<double> const&) const
#4  /__w/aspect/aspect/build/aspect: void dealii::SolverFGMRES<dealii::LinearAlgebra::distributed::BlockVector<double> >::solve<aspect::MatrixFreeStokesOperators::StokesOperator<2, 2, double>, aspect::internal::BlockSchurGMGPreconditioner<aspect::MatrixFreeStokesOperators::StokesOperator<2, 2, double>, aspect::MatrixFreeStokesOperators::ABlockOperator<2, 2, double>, aspect::MatrixFreeStokesOperators::MassMatrixOperator<2, 1, double>, dealii::PreconditionMG<2, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, dealii::MGTransferMatrixFree<2, double> >, dealii::PreconditionMG<2, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, dealii::MGTransferMatrixFree<2, double> > > >(aspect::MatrixFreeStokesOperators::StokesOperator<2, 2, double> const&, dealii::LinearAlgebra::distributed::BlockVector<double>&, dealii::LinearAlgebra::distributed::BlockVector<double> const&, aspect::internal::BlockSchurGMGPreconditioner<aspect::MatrixFreeStokesOperators::StokesOperator<2, 2, double>, aspect::MatrixFreeStokesOperators::ABlockOperator<2, 2, double>, aspect::MatrixFreeStokesOperators::MassMatrixOperator<2, 1, double>, dealii::PreconditionMG<2, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, dealii::MGTransferMatrixFree<2, double> >, dealii::PreconditionMG<2, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>, dealii::MGTransferMatrixFree<2, double> > > const&)
#5  /__w/aspect/aspect/build/aspect: aspect::StokesMatrixFreeHandlerImplementation<2, 2>::solve()
```

**Comment by tjhei** [comment]
This is unrelated, see #4960.

**Pull request merged**
