### PR TITLE
CI: add github actions

### PR DESCRIPTION
**Pull request by tjhei**
As discussed during the meeting today.
This CI job runs unconditionally in about 12 minutes and checks indentation, compilation (unity build), and documentation. This will help us with rapid iteration for pull requests but our own testers are obviously required before merging anything.

Github actions currently runs 20 concurrent linux jobs for open source projects.

### CODE REVIEW

**Comment by tjhei** [comment]
not sure why it is not building in this repo but on mine it is: https://github.com/tjhei/aspect/runs/924996261

**Comment by gassmoeller** [comment]
Maybe it has to be merged to be activated if the repo is not owned by you? Anyway the actions look good, if you fix the indentation this can be merged. Or do you want to generate similar artifacts for download as in Jenkins?

**Comment by tjhei** [comment]
I wanted to test the failure here, but maybe it needs to be merged to be enabled first.

**Comment by tjhei** [comment]
We can merge (even though I prefer to see the status beforehand).

**Pull request merged**
