### PR TITLE
support netcdf in prm files

### PR DESCRIPTION
**Pull request by tjhei**
- support loading netcdf files everywhere you can load ascii data in prms
- fix scaling when loading netcdf files
- add test

part of #5447

### CODE REVIEW

**Comment by tjhei** [comment]
Well, this requires the testers to have netcdf enabled...

**Comment by gassmoeller** [comment]
Ok, NetCDF inside the image is now available. It is just the test results that need an update.

**Comment by tjhei** [comment]
updated!

**Review by gassmoeller — APPROVED** [review]
Nice!

**Pull request merged**
