### PR TITLE
Cleanup some unused variable warnings.

### PR DESCRIPTION
**Pull request by jperryhouts**

### CODE REVIEW

**Comment by gassmoeller** [comment]
Thanks for fixing warnings :+1:
Looks good, but I will wait for the tester.

**Comment by bangerth** [comment]
The tester is unhappy about your patch to hdf5.cc: http://www.math.clemson.edu/~heister/aspect-logs/f3ef1c8b1a9b155b924e9675a316494a94c77efd/gcc

**Comment by gassmoeller** [comment]
That makes sense, I forgot to include `(void) property_component_list;` in hdf5.cc:253. Jonathan can you revert your change in the argument list and add that line instead? The warning you see should only occur if DEAL_II_WITH_HDF5 is not defined.

**Comment by jperryhouts** [comment]
Ah, good point. Should be fixed now.

**Comment by gassmoeller** [comment]
Ok, thanks for fixing.

**Pull request merged**
