### PR TITLE
set DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=OFF for tester

### PR DESCRIPTION
**Pull request by gassmoeller**
As described in #5119 enabling Trilinos_ENABLE_EXPLICIT_INSTANTIATION for the tester seems to be missing some instantiations. Try to remove the setting in order to fix the tester. Note that I switched to use this docker image in #4922 in order to reduce memory requirements while compiling aspect on the github tester. We will have to see if this change reintroduces the problems with occasional out of memory errors on the tester or an unacceptable change in compile time.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Our tester image build is triggered around 10pm EDT nightly. Since this PR only affects the tester image, and it can only be tested if it is merged by that time I will take a look at the testers later and merge in case all other testers are ok.

**Comment by gassmoeller** [comment]
Looks like something else is going on with the testers as well. I will try to figure this out tomorrow.

**Comment by gassmoeller** [comment]
The failures for `linux/no-unity-build` and `linux/indent+documentation` are unrelated (see #5122). Therefore I will merge this PR for now to be able to see if the tester base image is built correctly for deal.II master with these changes.

**Comment by gassmoeller** [comment]
Oh, I would need an approving review by someone (branch protection).

**Comment by MFraters** [comment]
ah, I now read the other pull request :)

**Review by tjhei — APPROVED** [review]

**Pull request merged**
