### PR TITLE
corrected vof parameter typo

### PR DESCRIPTION
**Pull request by bobmyhill**
This PR corrects a volume of fluid parameter typo:
Volume of fluid intialization type -> Volume of fluid initialization type

### CODE REVIEW

**Comment by bobmyhill** [comment]
This will break backwards compatibility, and would also interfere with #3425. 
I'm happy for #3425 to be merged first and then I can edit this PR.

**Comment by bangerth** [comment]
Ah, yes, this is unfortunate. Let's keep this open for a few days so we have time to read through #3425 one more time. It'll be easier to adjust the current patch than the one in #3425.

**Comment by bangerth** [comment]
@bobmyhill -- #3425 was merged. Would you mind updating this PR?

**Comment by bobmyhill** [comment]
Now updated.

**Review by bangerth — APPROVED** [review]

**Pull request merged**
