### PR TITLE
Free surface resume

### PR DESCRIPTION
**Pull request by ian-r-rose**
This adds checkpointing to free surface computations, addressing #614.

I attempted to add a checkpointing test, but I think I was running into the same issue as in #616, so was having difficulty getting complete reproducibility. I have not included it at the moment, but am open to suggestions.

### CODE REVIEW

**Comment by tjhei** [comment]
It should work if you use a direct solver. You can copy the existing ```checkpoint_02``` test for example.

**Comment by tjhei** [comment]
(let me know if you need help)

**Comment by ian-r-rose** [comment]
The solvers in the free surface module are not currently set up for direct solution. I have confirmed that the Stokes solves are bitwise reproducible with the direct solver, but the ones involving the mesh displacement are not at the moment.

The differences that I am seeing are quite small: of order machine precision, so I think they should pass any numdiff-oriented test.

**Comment by tjhei** [comment]
okay, that makes sense.

**Comment by tjhei** [comment]
Can you take that test and create a separate [WIP] pull request for it please?

**Comment by ian-r-rose** [comment]
Yes, I can do that.

**Pull request merged**
