### PR TITLE
Adds publications for February

### PR DESCRIPTION
**Pull request by ljhwang**
This adds publications using ASPECT for February AND also adds a bunch of missed publications. Google scholar does not seem to be doing a good job in finding mentions in AGU publications. And probably does not search supplementary materials.

Also my first foray into visual studio code.  

Let's see what the tester finds ...

### CODE REVIEW

**Review by tjhei — APPROVED** [review]
Tester and Timo are happy. 😉

Seems like @anne-glerum has been productive!

**Comment by tjhei** [comment]
@ljhwang ?

**Comment by ljhwang** [comment]
Can you help me with fixing the conflict?

**Comment by tjhei** [comment]
Sure. What happens if you try to rebase?

**Comment by ljhwang** [comment]
That got messy.  @tjhei please tag me if this still does not look right.

**Comment by tjhei** [comment]
Looks good to me. 👍

**Review by tjhei — APPROVED** [review]

**Pull request merged**
