### PR TITLE
Replace using std::shared_ptr in tests and benchmarks.

### PR DESCRIPTION
**Pull request by bangerth**
In reference to #2811 and #2375.
Follow-up to #3010.

### CODE REVIEW

**Comment by tjhei** [comment]
tests are failing, can you check? I am sure you compiled all benchmarks and cookbooks too, right?

**Comment by bangerth** [comment]
I fixed the test.

I find it awkward to let the tests run on my laptop, because it takes quite a long time and also because so many tests fail on my local setup. So I use the tester to do part of the work I *should* probably be doing before uploading something as a pull request...

**Comment by tjhei** [comment]
> I find it awkward to let the tests run on my laptop, because it takes quite a long time and also because so many tests fail on my local setup.

I am not talking about the tests. My point is that we should check if benchmarks/* still work with your changes as they are not running on the tester. Yes, it takes a while to run them but I think it is necessary. Let me know and I can do it...

**Comment by bangerth** [comment]
Ah, fair. I have to admit that I don't know how that works. If you have a few cycles left-over while talking to someone, I'd appreciate it!

**Comment by tjhei** [comment]
> If you have a few cycles left-over while talking to someone, I'd appreciate it!

FYI, this is done using ``benchmarks/check.sh``. Will run them over night...

**Comment by tjhei** [comment]
There are several things that need to be fixed for the benchmarks, but your changes are not breaking anything. :+1:

**Comment by bangerth** [comment]
OK, thanks for checking. I guess you're willing to fix these things?

**Comment by tjhei** [comment]
> OK, thanks for checking. I guess you're willing to fix these things?

of course, see #3050

**Pull request merged**
