### PR TITLE
Check that FS sediment depth and age do not have chemical composition type

### PR DESCRIPTION
**Pull request by anne-glerum**
Since #5542, masks for compositional fields are no longer needed as the compositional field type is used to compute the volume fractions in the viscoelastic and viscoplastic material models. This PR ensures that two fields that can be used in conjunction with FastScape are not of chemical composition type. Originally, they are masked in get_volumetric_composition_mask(). I think that function be removed, but I've kept it in for now.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [ ] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Review by gassmoeller — COMMENTED** [review]
I agree that this is useful, but I think it needs to go to a different place, because visco_plastic.cc shouldnt depend on the Fastscape plugin (and other material models would want the same check to happen).. I would suggest fastscape.cc, but I do not even see where these fields are used in there. Can you clarify where and how these fields are used?

**Comment by anne-glerum** [comment]
Hi @gassmoeller, the current PR simply makes sure that the lines that are already in visco_plastic.cc (here: https://github.com/geodynamics/aspect/blob/d04495c3439e1cfa003350214414b52ee2cc7ef9/source/material_model/rheology/visco_plastic.cc#L510C1-L521C7) are replaced with something effective now that masks are no longer used.

I see your point about the location of this check though. We have been using these fields to keep track of the age and deposition depth of the sediment. Their value is completely determined by the function boundary conditions specified for them in the input file (and the movement of said boundaries through FastScape). The sediment age is just the model time provided by the Function in years and the depth the reference model height minus the height of the boundary point. Hence, fastscape.cc does not use them anywhere.

**Comment by gassmoeller** [comment]
Hmm, I see the link to where these lines are right now, but in this PR you also add them to another place. Should you not delete them in their previous location?

> We have been using these fields to keep track of the age and deposition depth of the sediment.

Ah, I understand now. You have been using these fields for output purposes in many of your models that use fastscape, but they are in principle independent of both viscoplastic and fastscape and only track sedimentation conditions?

If so, I think there are two options what to do with them:
1. We could move the check into the Fastscape plugin, and document around them that it is useful to track these fields (although not necessary for any function). I would still want to move them into the fastscape plugin, because they are closely related to that one (as indicated by the preprocessor macro around it), but completely independent of viscoplastic.
2. We could delete them completely. I appreciate that it is useful if ASPECT checks that these fields types are correctly set, but they also generate a lot of confusion for readers of the code (like me ^^).

**Comment by gassmoeller** [comment]
Sounds good, if you make the suggested changes I will merge this. If `get_volumetric_composition_mask` is not  used anymore and it is private delete it as well.

**Comment by anne-glerum** [comment]
Alright, I've moved the check to the FastScape plugin. I've also removed setting the masks for the two fields from the get_volumetric_composition_mask function. This function is not used anywhere in the code, but it is not a private function, so I've left it in. The material model visco_plastic was the only one to call the function, and it no longer does.

**Review by gassmoeller — APPROVED** [review]
Thanks, looks good!

**Pull request merged**
