### PR TITLE
Instantiate particles for spacedim

### PR DESCRIPTION
**Pull request by gassmoeller**
This is the first step towards addressing the comments and discussions of dealii/dealii#4729 inside of ASPECT to then move parts of the particle implementation into deal.II

This PR allows for particles where dim != spacedim, which never happens in ASPECT.

### CODE REVIEW

**Comment by bangerth** [comment]
Looks good to me. Wait for the tester, then merge.

**Comment by gassmoeller** [comment]
I think the failing test on master is broken, because it does not use particles at all. I have opened #1881 to check for that.

**Comment by gassmoeller** [comment]
Master is fixed and I rebased. This is ready to merge if the tester is happy.

**Comment by bangerth** [comment]
See #1897.

**Pull request merged**
