### PR TITLE
Switch tester to 9.3.2

### PR DESCRIPTION
**Pull request by tjhei**
Update docker image for Jenkins to 9.3.2

TODO: update github actions once new ubuntu packages are released.

### CODE REVIEW

**Comment by tjhei** [comment]
@gassmoeller could you please generate the new image? I would like to move the testers to 9.3.2 so that I can use the bugfixes relevant for mesh deformation.

**Comment by gassmoeller** [comment]
I started the build, will let you know when it is done and pushed. Can you also update `contrib/docker/tester/build.sh` to tag the image with the new version?

**Comment by gassmoeller** [comment]
The new image is build and pushed. Let's see what the tester says.

/rebuild

**Comment by tjhei** [comment]
"Found deal.II version 9.3.2". :+1:

**Comment by tjhei** [comment]
Maybe we should wait for the new ubuntu packages so that we can update the github testers as well. Should only take a couple of days, hopefully.

**Comment by bangerth** [comment]
What should we do here? It looks good to me.

**Comment by tjhei** [comment]
Ubuntu packages are not updated to 9.3.2 so we can not update the github actions without installing manually.

@gassmoeller Should we consider switching github actions to use our own image?

**Comment by tjhei** [comment]
Updated to 9.3.2. If everything passes, we can merge this.

**Pull request merged**
