### PR TITLE
Modified assembly.cc so if is_compressible is false, then ASPECT solves the incompressible Boussinesq Equations

### PR DESCRIPTION
**Pull request by egpuckett**
In other words if is_compressible is false, then the the material derivative of the temperature 

```DT / Dt```

in the energy equation is multiplied by
 
```reference_rho * c_P```

rather than 

```reference_rho * ( 1 - alpha *( T - T_0) ) *  c_P```

as per the following email of December 2, 2015 from Magali, Gerry 

> Dear Wolfgang and Timo,

> Greeting from Team Aspect at UC Davis (Louise, Gerry, Magali, Scott, Harsha, and Hiro)! 

> We finally have several students and faculty working on projects related to Aspect here. This means that students are reading the manual and asking questions. A question concerning the first cookbook, 6.2.1, has lead us to exploring the form of the equations within the code.  We are ready to do a pull request to modify the relevant lines in assembly.cc, but we thought it would be good to send an e-mail first with some background information explaining the reason for the modifications, since this a core part of the code.

> In particular, we have been looking at the form of the equations for “incompressible" computations. For mantle convection incompressible usually starts with the Boussinesq Approximation in which the variations in density only appear in the buoyancy term in the momentum equation, while only the reference density appears in the energy equation.  Please see attached documents, which include annotated version of relevant parts of the manual and explanatory text and the summary pages of equation from Schubert, Turcotte and Olson (2001).

> We believe the form of the energy equation currently used in Aspect does not include an option for the incompressible Boussinesq approximation. Specifically, there is no option to use only the reference density from the material model rather than the density being calculated at each point. Therefore, users who assume they are doing an "incompressible" calculation will  have errors due to a slightly different density value in the energy equation.

> We have also completed some computations to determine if this has any real affect on the results. The good news is that the error introduced is small (< 1%) if variations in density are small (e.g., only depend on thermal expansion, and an earth-like value on the order of 1e-5 1/K is used). However, in calculations in which the thermal expansion is 1e-4 1/K, we found a difference in heat flux on the order of 4%.  For these tests, we did dimensional computations of Blankenbach (1989) benchmarks 1a) and 1b) of isoviscous convection in a square box (1000 km x 1000 km) with "earth-like" values for parameters using the simple.cc material model. We compared the heat flux both with and without the "correction" to the energy equation.  

>  These tests also confirm a related "issue" with the current form of the equations, which is that you can not really do a proper non-dimensional form of the "incompressible" equations that depends only on the Rayleigh number, because the thermal expansion term appears in the energy equation; e.g., see Cookbook 6.2.1.  By this I mean, that I can do two different computations with the same Rayleigh number (which should give me identical results) but if I've changed thermal expansion in one of the runs (together with the reference viscosity), I get a different result for the heat flux.  Again, this error is only apparent for thermal expansion greater than or equal to 1e-4 (4%) and for smaller values, the error is less than 1%. Two tables summarizing the results of the tests are attached.

> The good news is that the differences are small and the correction is easy to make. We will go ahead and submit a pull request, so you can see the proposed changes. We would also be happy to discuss this more by e-mail or over coffee or beer at AGU if there are any questions.

>Sincerely,

> Magali, Gerry, Louise, Harsha, Scott, and Hiro

### CODE REVIEW

**Comment by gassmoeller** [comment]
Hi Gerry,
thanks for raising this issue and proposing a solution. We discussed problems around the implementation of consistent approximations a few times in the past (see for example #98,#166, #212, #653) but never had enough pressure to find an accurate solution covering all cases. Still I agree it is important to finally make this consistent and documented. One problem we encountered in the past was the somewhat in-between definition of the extended Boussinuesq approximation (density profile and heating terms in the energy equation, but no compressibility in the Stokes equation, which would not be covered by your current fix). This made it complicated to find a solution covering BA, EBA, possibly TALA, and the use of the full temperature- and pressure-dependent density in buoyancy term and energy equation. Maybe we should just decide to interpret `is_compressible` as an `uses_BA`, and only allow the BA you describe, or the full density (e.g. no radial reference density profiles, as I tried in #212). Anyway, we should definitely discuss this at AGU, and make a decision about which way to go. @tjhei, @bangerth, what do you think?

**Comment by ian-r-rose** [comment]
Thanks for bringing this up, Gerry.
My preference for the overall approach to this is to have a top-level parameter which selects from
* Boussinesq
* Extended Boussinesq
* Truncated anelastic
* Full anelastic

There can then be a validation step which checks whether the material model is consistent with the given approximation (I think just whether it defines a compressibility, but perhaps I am forgetting another parameter?).

As Rene has pointed out, we need to be very careful with the concept of a reference state, since most of these approximations involve subtracting one off of the solution. We will have to make sure that these approximations are all possible to do with the full pressure and density.

**Comment by icherkashin** [comment]
I just noticed a typo in the comments: instead of `referencr rho` it should be `reference_rho`. I'm not certain how I could edit anything in this pull request, so I would like to draw Prof. Puckett's or Harsha's attention to this here so they could fix it.

https://github.com/geodynamics/aspect/pull/680/files#diff-08f9a13515fd055c1c636c3a242b8da6R638

**Comment by tjhei** [comment]
Thanks for bringing this up! The issue is not forgotten, but we still need to discuss how to go forward with this. @jdannberg @gassmoeller @bangerth and I had another discussion about it this week, and I think we are getting closer.

**Comment by egpuckett** [comment]
On 1/16/2016 3:43 PM, Timo Heister wrote:
>
> Thanks for bringing this up! The issue is not forgotten, but we still 
> need to discuss how to go forward with this. @jdannberg 
> <https://github.com/jdannberg> @gassmoeller 
> <https://github.com/gassmoeller> @bangerth 
> <https://github.com/bangerth> and I had another discussion about it 
> this week, and I think we are getting closer.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/geodynamics/aspect/pull/680#issuecomment-172274281>.
>
Hi Timo,

Thanks for keeping me in the loop.

Happy New Year,

- Gerry

-- 
“Keep away from people who try to belittle your ambitions. Small people 
always do that, but the really great make you feel that you, too, can 
become great.” - Mark Twain

**Comment by egpuckett** [comment]
Would you like me to close this pull request, since  need to discuss how to go forward with this. @jdannberg,  @gassmoeller,  @bangerth and @tjhei are working on an alternative approach to implementing the 'basic' Boussinesq Approximation?

**Comment by bangerth** [comment]
Yes, let's close it. We're going to get to it, but another way.

**Pull request closed without merging**
