### PR TITLE
fix sign of MassConservation::implicit_reference_density_profile

### PR DESCRIPTION
**Pull request by tjhei**
Fix wrong sign in the implicit formulation (the comment in the function
even had the sign correct). This makes the TanGurnis benchmarks give the
same results whether you use the explicit or the implicit version.

### CODE REVIEW

**Comment by tjhei** [comment]
note: this hopefully breaks some tests that I will then fix later.

**Comment by bangerth** [comment]
Probably not what you had in mind, but it does break the indentation check :-)

OK if it passes with changes to the tests. If it doesn't require changes to tests, could you add some test that is affected?

**Comment by tjhei** [comment]
Well, the good news is that this changes ``tests/tangurnis_tala_implicit``, which now produces the same heating terms. :v:

**Comment by gassmoeller** [comment]
It seems this is good to go? Looks reasonable to me, so I will pull the trigger.

**Pull request merged**
