### PR TITLE
Remove trailing comma in some postprocessors

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by bangerth** [comment]
OK to merge if it passes the tester. Do other screen output strings end in a period or are just open at the end?

**Comment by tjhei** [comment]
> Do other screen output strings end in a period or are just open at the end?

Yes, I found some more.

**Comment by tjhei** [comment]
> OK to merge if it passes the tester.

Interestingly, no tests need to be adapted because numdiff filters the commas. ;-)

**Comment by bangerth** [comment]
Yes, numdiff does some weird stuff...

**Comment by bangerth** [comment]
Still ok to merge if the tester is ok.

**Pull request merged**
