### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by gassmoeller**
Small follow-up to #4609.

### CODE REVIEW

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
I guess @tjhei was just too darn slow to fix it himself? ;-)

**Comment by gassmoeller** [comment]
I needed to get a PR for myself and this was the easiest way to do it :smile:

**Comment by bangerth** [comment]
There, you're on the board now!

**Comment by tjhei** [comment]
Haha! Glad I could help.

**Pull request merged**
