### PR TITLE
Speedup tests

### PR DESCRIPTION
**Pull request by gassmoeller**
While waiting for the tester to finish several times today I took a look on our testsuite and noticed that a small number of tests creates most of the load on the tester. I tried to simplify them without changing their purpose to speed up the tester return time. This PR can wait for a bit (definitely after merging #1456), but I would like to check already how much time I saved. This might be pretty useful for the hackathon.

### CODE REVIEW

**Comment by tjhei** [comment]
Nice. I only see a small improvement on the tester: 23 vs 25 minutes.

Depth averages are also quite slow in debug mode in 3d, so disabling those where unnecessary is also good.

**Comment by gassmoeller** [comment]
Which times did you compare? The ctest timing output suggests a change from 520 to 414 second for aspect-8.5-gcc-hd (compared between this PR and #1456), but I do not know if there there is more time spent around the ctest call (starting the container etc).

**Comment by tjhei** [comment]
> Which times did you compare?

The total turn-around (checkout+compile+test) but we both get to the conclusion that this saves 1-2 minutes.

**Comment by gassmoeller** [comment]
Bummer, I forgot about the compile time. I guess then it is not really worth trying to reduce the test time further, if it only makes up 40% of the total time anyway.

**Comment by tjhei** [comment]
can you rebase to master please?

**Comment by tjhei** [comment]
> if it only makes up 40% of the total time anyway.

Yeah, I am not sure why compilation is that slow. Maybe we should look into that sometimes.

**Comment by tjhei** [comment]
> compilation is that slow

natively: 1m59s
in virtualbox/docker: 3m20s

so we should have ~10 minutes total and not 23 minutes. I think I did something stupid in the testing script. Will report back tomorrow.

**Comment by gassmoeller** [comment]
Ok that sound like there is significant room for improvement on the tester. But you tempted me to do something about our normal compilation time anyway. I had a look at our compile time (which I think is far too long to recompile comfortably even on a i7 45W laptop CPU), and I think I found a nice improvement. Will open a separate PR for that.

**Comment by bangerth** [comment]
I think the things proposed here are independently useful.

**Comment by tjhei** [comment]
can you rebase and check why the free surface test is breaking?

**Comment by gassmoeller** [comment]
Finally found the problem, during my earlier update the output files were empty (not removed, but no content), and in this case the test failed without a reasonable error message. This PR should be good to go.

**Comment by tjhei** [comment]
would you mind rebasing to the current master? I just want to make sure we have another clean run with the testers.

**Pull request merged**
