### PR TITLE
Move test data files to tests/data/

### PR DESCRIPTION
**Pull request by tjhei**
as discussed in #1329

### CODE REVIEW

**Comment by tjhei** [comment]
WIP. There are likely other tests that need to be adapted.

**Comment by bangerth** [comment]
It fails a bunch of tests, but if you can make them work, then this is ok with me.

Can you please also add a changelog entry that explains where these files have been moved?

**Comment by gassmoeller** [comment]
This is not something I would start a fight over, but I would say I prefer the old file locations for two reasons:
- In the current system it is easier for people to figure out where new data files have to go, they do not need to understand which files to put into data/ and which into tests/data.
- I feel it useful to have test data files in the data/ folder, because they teach people how to format their real data files. If they are hidden in tests/data people might never see them and do not know how to look up the format. I do not think there is the danger of mistakenly using them in real models, since they are named `test...something`.

I therefore do not really see a benefit of moving the test data into the tests/ directory, only drawbacks. If you are convinced it is an improvement feel free to go ahead, I just wanted to raise my concerns.

**Comment by jdannberg** [comment]
Another point I just noticed right now: The default option for the input file location (for many plugins) is currently also the test file in the data folder. We would have to change that to the test folder (where we moved these files to), but then it is not as intuitive how to specify the file location or where these files should be located.

**Comment by tjhei** [comment]
Yeah, not ideal. I am okay with leaving things as is.

**Comment by bangerth** [comment]
Looks like a majority has been found then.

**Pull request closed without merging**
