### PR TITLE
adjust copyright

### PR DESCRIPTION
**Pull request by tjhei**
Do not merge yet, I have to rerun after the other open PRs are merged.

This is from the release-tasklist:
```
find . -name "*.h" -o -name "*.cc" -print | while read file;do sed -i '0,/^.*Copyright.*/{s/^.*Copyright.*/  Copyright (C) 2011 - 2016 by the authors of the ASPECT code./}' $file; done
```

Is this sensible?

### CODE REVIEW

**Comment by bangerth** [comment]
Why not use `contrib/utilities/update_copyright` from deal.II? Should do the same.

**Comment by tjhei** [comment]
No, it is not the same because here we change every date to "2011 - 2016". That was what I wanted to discuss.

**Comment by bangerth** [comment]
Ah, I see. But then you're lying -- some of these files we may not even have had in 2011.

**Comment by tjhei** [comment]
Yes, that is why I want to discuss this. :-)

Are you suggesting to use the deal.II script instead? What about the fact that we are "lying" already because of the last time we ran it (for 1.3)?

**Comment by jperryhouts** [comment]
I found a discussion of this topic here: http://programmers.stackexchange.com/questions/124687/copyright-statements-in-source-code

The first response seems pretty legit.

**Comment by jperryhouts** [comment]
What if we added something to the deal.ii script to also list the first occurrence of the file in the git repository?

    first_year=`git log --date=short --format="format:%cd %s" $i | \
             tail -n 1 | \
             perl -p -e 's/^(\d\d\d\d)-.*/\1/g;'`

or something...

**Comment by bangerth** [comment]
> Are you suggesting to use the deal.II script instead? What about the fact that
> we are "lying" already because of the last time we ran it (for 1.3)?
Can you explain? Doesn't the script only update the copyright of a file to the 
current year if the file had been modified in the current year? Isn't this 
exactly what we want? (I suppose that I am simply dense and don't quite 
understand the angle you're coming at this problem from.)

**Comment by jperryhouts** [comment]
Oh, I was just suggesting that we could update the copyright notices to the actual first and last years it was worked on by using the git logs (to fix the ones Timo mentioned that were changed to 2011 - ... during the 1.3 release).

And the stackexchange thing just mentions that the copyright notice should just list the years in which the file was actually modified. Not that any of it really matters, the copyright holds whether or not you put that little message in each of the files. :)

**Comment by tjhei** [comment]
> Can you explain? 

The script in the ASPECT release task (pasted above) replaces every statement _unconditionally_ with "2011-2016". We have used this in the past, so nearly every file has "2011-2015" right now (see diffs here). 

The options are:
1. Apply the script as is (like this PR does), every file will have "2011-2016".
2. Use the deal.II script: files will have "2011-2015" or "2011-2016" (if edited recently).
3. Do something fancy to find out "X-Y" where X is the first time the file got added and "Y" is the last edit date (see Jonathan's comment).

I don't care what we do, but I wanted to at least mention it.

**Comment by ljhwang** [comment]
To muddle the picture, this is what GNU says:

For software with several releases over multiple years, it's okay to use a range (“2008-2010”) instead of listing individual years (“2008, 2009, 2010”) if and only if every year in the range, inclusive, really is a “copyrightable” year that would be listed individually; and you make an explicit statement in your documentation about this usage.

http://www.gnu.org/licenses/gpl-howto.en.html

**Comment by jperryhouts** [comment]
years=`echo -e "\n$(git log --format="format:%cD" $i)" | \
        awk '{if($1) print $4}' | sort | uniq | sed ':a;N;s/\n/, /;ta'`
    
    echo "Copyright (C) $years by the authors of the ASPECT code."

**Comment by bangerth** [comment]
On 04/30/2016 03:43 PM, Timo Heister wrote:
> The script in the ASPECT release task (pasted above) replaces every statement
> /unconditionally/ with "2011-2016". We have used this in the past, so nearly
> every file has "2011-2015" right now (see diffs here).

Ah, thanks for the explanation. I hadn't realized this.

**Comment by bangerth** [comment]
Let's ignore the GNU guidelines. These folks are seriously pedantic.

**Comment by tjhei** [comment]
> Let's ignore the GNU guidelines. These folks are seriously pedantic.

so, what do you suggest?

(gosh, what did I start with here)

**Comment by tjhei** [comment]
PR updated to output the deal.II script makes.

**Comment by bangerth** [comment]
My suggestion would have been to just use `firstyear - lastyear` where the two years correspond to the first appearance of the file in the git log, and the last year it was modified, respectively.

**Comment by bangerth** [comment]
I approve this patch but don't want to step on #848. How do you want to proceed?

**Comment by tjhei** [comment]
I am fine with either solution. The problem is so inconsequential anyways. So?

**Comment by jperryhouts** [comment]
> I approve this patch but don't want to step on #848. How do you want to proceed?

Don't worry about stepping on the other one; it wasn't much effort, and regex golf is fun anyway. If this is the preferred option, then go with it! As Timo points out, it's all very inconsequential. :)

**Pull request merged**
