### PR TITLE
Update the World builder to version 0.6

### PR DESCRIPTION
**Pull request by MFraters**
A new version of the world builder will be released soon (hopefully, see https://github.com/GeodynamicWorldBuilder/WorldBuilder/issues/670 for todo's), so it is also time to start the review process to get it into aspect. This pull request will still be update until the final release. 

I know @tjhei and @gassmoeller looked into improving the cmake system for building, but I don't know how that discussion ended. Is the current form oke, or are changes needed? Note that how the cmake currently works in aspect is that is gwb version >= 0.6, it will use the new system.

### CODE REVIEW

**Comment by tjhei** [comment]
I have a bunch of changes on ASPECT and GWB that are needed to fix the DebugRelease  build. Needs cleaning up first, though.

**Comment by MFraters** [comment]
This pull request is now ready for review. Before making the world builder 0.6 release, I would like preliminary approval on this pull request that this is in principle good to merge. 

Once I have that, I will remove the -pre from the version numbers and add the new zenodo doi and make the release. When that is done, I will update this pull request again with the released version.

**Comment by gassmoeller** [comment]
This time the tester errors are a little more clear. Seems like something goes wrong in DebugRelease mode with linking to WB. Have you checked if this works locally for you?

**Comment by MFraters** [comment]
Fixed it. It looks good for review now :)

**Review by gassmoeller — APPROVED** [review]
Looks good to me. I didnt look at the content of the world builder directory, but that will only be a copy of the world builder release eventually, right? The changes to ASPECT's CMakeLists look ok.

**Comment by MFraters** [comment]
> Looks good to me. I didnt look at the content of the world builder directory, but that will only be a copy of the world builder release eventually, right? The changes to ASPECT's CMakeLists look ok.

Thanks. Yes, that that is correct.

**Comment by MFraters** [comment]
The world builder 0.6.0 release has been made and this pull request is updated with the released version.

**Comment by tjhei** [comment]
Why does ci.tjhei.info fail?

**Comment by tjhei** [comment]
```
ld: file not found: -lWorldBuilder
```
This looks like some of the CMake changes I made did not work. Do you want me to take a closer look?

**Comment by MFraters** [comment]
oke, I had to experiment a bit, because I couldn't reproduce it locally, but it seems fixed now.

**Comment by MFraters** [comment]
Is there anything which still need to happen here? I think it now works as intended and it should be ready to merge.

**Review by gassmoeller — APPROVED** [review]
I think this is good to go, we probably just forgot that the PR is still open.

**Pull request merged**
