### PR TITLE
Add logic to bypass undesired coarsen/refine.

### PR DESCRIPTION
**Pull request by spco**
I've written this in such a way that if we do want to cancel all coarsens or refines, then it still only loops through active cells once. It might be more readable to keep the clearing of all flags separate from the clearing of min/max levels, which was there before. What are your thoughts?

### CODE REVIEW

**Comment by bangerth** [comment]
@spco -- please squash/fixup the two commits.

The patch looks good. First to see if the tester has succeeded, please merge!

**Comment by spco** [comment]
fixes #935

**Comment by bangerth** [comment]
This seems to break 7 tests. Can you take a look at the diffs offered by the tester and check whether they're expected? If so, please download the patch file and apply to this pull request.

**Comment by gassmoeller** [comment]
The tests are fixed now, but dynamic_topography2 has become much larger than before (28000 lines). Could you spend a few minutes and check if you can reduce the refinement level of the test by 2 or so, and still test the behaviour? From the description of the test it only relies on the fact that there are differently sized cells at the surface. You will probably need to change the output type to vtu on your computer to check that, then switch back to gnuplot to update the test output. Talk to me, if you do not want to wait until the tester creates the diff (you can run the test locally and replace the reference result on your machine).

**Comment by spco** [comment]
Reducing the global refinement by one level seems to capture everything, and has output of 8000 lines. Reducing by 2 seems to stop the solution being resolved, so it's probably not great to drop 2 levels. Come see the plots if that's of interest, otherwise I will just reduce by one and recommit?

**Comment by spco** [comment]
This looks good to merge unless anyone has more comments.

**Comment by bangerth** [comment]
@spco -- for my own education, can you explain why that one test changed so dramatically? Was this one were the refinement fraction was 1 but not all cells were refined? I don't quite understand how the number of cells could have become so much larger.

**Comment by spco** [comment]
The test runs 3 rounds of adaptive refinement on a stationary problem. This previously had cell numbers 4096, 1126, 502 (definitely not respecting the coarsening fraction = 0) while the patch has cell numbers 1024, 1126, 1126 (as we start with one level lower global refinement).

**Comment by spco** [comment]
For reference

> subsection Mesh refinement
  set Initial adaptive refinement        = 2
  set Initial global refinement          = 6
  set Refinement fraction                = 0.5
  set Coarsening fraction                = 0.00
  set Strategy                           = thermal energy density
end

**Comment by bangerth** [comment]
Great, thanks for the explanation!

**Pull request merged**
