### PR TITLE
Remove deal.II compatibility fix

### PR DESCRIPTION
**Pull request by tjhei**
Removed a not longer necessary compatibility fix for deal.II 8.5.

### CODE REVIEW

**Comment by bangerth** [comment]
/rebuild

Stealing work from the poor? ;-)

**Comment by tjhei** [comment]
> Stealing work from the poor? ;-)

this was Rene's demo, I think.

**Comment by gassmoeller** [comment]
yes this was me for demonstration purposes.

**Comment by tjhei** [comment]
related to #2921

**Pull request merged**
