### PR TITLE
Update documentation of viscous prefactors in visco_plastic

### PR DESCRIPTION
**Pull request by naliboff**
Addresses #2123. 
@sibiaoliu - Does this clarify the prefactor term? If more documentation is needed, let me know!

### CODE REVIEW

**Comment by bangerth** [comment]
If there is disagreement in the literature on how exactly to define an exponent (with positive or negative signs), would it make sense to point this out in the documentation?

**Comment by naliboff** [comment]
Yes, definitely worth pointing this out in the documentation. I've added a brief comment indicating that the grain size exponent should always be defined as positive and to carefully check how viscous flow law terms are defined in previous studies.

**Comment by naliboff** [comment]
As other material models also use similar flow laws, perhaps it would be worth noting in the manual?

**Comment by bangerth** [comment]
Thanks for the extra text!

You're right that in general, we ought to document these sorts of deviations between formulations used in the literature. If you come across a place that could use a similar sentence, feel free to add it!

**Comment by jdannberg** [comment]
Thanks for adding this, @naliboff! 
Just one small thing: I noticed the spaces at the end of the documentation text are missing (so in the manual pdf, this will look like for example "useslightly" instead of "use slightly"). If you have time, maybe you could fix this? Otherwise I'll make another pull request later today. 

And I guess at some point we should also make similar changes to the diffusion dislocation model (as it uses the same formulation).

**Comment by naliboff** [comment]
@jdannberg - Thanks for catching thtat! I'll add the spaces and add a few words to the diffusion dislocation model as well. Should I check the grain-size dependent material model as well?

**Comment by jdannberg** [comment]
It seems to be correct in the `grain_size` material model (which also makes sense, because it does not use code from the diffusion dislocation model).

**Comment by naliboff** [comment]
See #2128 for spacing fix in `visco_plastic` and additional documentation and formatting in `diffusion_dislocation`.

**Pull request merged**
