### PR TITLE
Fix gmg only normal flux

### LINKED ISSUE #4282: Error in multigrid
With current master, I get an index error in the multigrid using the input files that @alarshi sent me a while ago. The error is
```
--------------------------------------------------------
An error occurred in line <480> of file </home/bangerth/p/deal.II/1/install/include/deal.II/multigrid/mg_constrained_dofs.h> in function
    const dealii::IndexSet& dealii::MGConstrainedDoFs::get_boundary_indices(unsigned int) const
The violated condition was: 
    ::dealii::deal_II_exceptions::internals::compare_less_than(level, boundary_indices.size())
Additional information: 
    Index 0 is not in the half-open range [0,0). In the current case, this
    half-open range is in fact empty, suggesting that you are accessing an
    element of an empty collection such as a vector that has not been set
    to the correct size.

Stacktrace:
-----------
#0  ./aspect: dealii::MGConstrainedDoFs::get_boundary_indices(unsigned int) const
#1  ./aspect: aspect::StokesMatrixFreeHandlerImplementation<3, 2>::setup_dofs()
#2  ./aspect: aspect::Simulator<3>::setup_dofs()
#3  ./aspect: aspect::Simulator<3>::run()
#4  ./aspect: void run_simulator<3>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool)
#5  ./aspect: main
--------------------------------------------------------
```
and it happens here:
```
    // GMG matrices
    {
      const unsigned int n_levels = sim.triangulation.n_global_levels();

      // ABlock GMG
      mg_matrices_A_block.clear_elements();
      mg_matrices_A_block.resize(0, n_levels-1);

      for (unsigned int level=0; level<n_levels; ++level)
        {
          IndexSet relevant_dofs;
          DoFTools::extract_locally_relevant_level_dofs(dof_handler_v, level, relevant_dofs);
          AffineConstraints<double> level_constraints;
          level_constraints.reinit(relevant_dofs);
          level_constraints.add_lines(mg_constrained_dofs_A_block.get_boundary_indices(level)); /// ************** this line
```
The problem is that `level=0` but the `MGConstrainedDoFs::boundary_indices` is an empty array.

Do you need the input files, or do you know where to poke? The input files are large, but I could see whether I can compress them and attach here.

### PR DESCRIPTION
**Pull request by tjhei**
GMG would crash/assert in

const dealii::IndexSet&
dealii::MGConstrainedDoFs::get_boundary_indices(unsigned int) const

when no prescribed/fixed boundary conditions are set. Bug was introduced
in #4251

fixes #4282

### CODE REVIEW

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
Thanks!

/rebuild

**Comment by bangerth** [comment]
You'll have to update the test output.

**Comment by tjhei** [comment]
fixed!

**Comment by bangerth** [comment]
One of the checks (continuous-integration/jenkins/pr-merge) seems to be stuck. I'm taking the liberty to merge anyway.

**Pull request merged**
