### PR TITLE
Use mapping for point values.

### LINKED ISSUE #1170: Use mapping in point value postprocessor
As pointed out in #1169, `source/postprocess/point_value.cc` contains this code:
```
              VectorTools::point_value(this->get_dof_handler(),
                                       this->get_solution(),
                                       evaluation_points[p],
                                       current_point_values[p]);
```
This is wrong -- we need to use the `mapping` here.

### PR DESCRIPTION
**Pull request by bangerth**
This should fix #1170. I have not tried to run the testsuite on my poor laptop. Let us
see what Timo's tester reports.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Seems all current point_value tests use box geometry models that is why none catch the bug. Care to add one with spherical geometry?

**Comment by bangerth** [comment]
Test and changelog entry added.

**Comment by bangerth** [comment]
Rebased and updated the test results with those from the tester.

**Comment by gassmoeller** [comment]
Looks good. Thanks!

**Pull request merged**
