### PR TITLE
fix manual.bib formatting

### PR DESCRIPTION
**Pull request by tjhei**
fixes #2254

### CODE REVIEW

**Comment by tjhei** [comment]
@bangerth next time please compile the manual when you change the .bib? ;-)

**Comment by bangerth** [comment]
Hm, that's a legitimate complaint. Sorry about that.

**Comment by bangerth** [comment]
But it can't have been #2254 because that didn't even touch this file. Rather, this came in through your #2239 :-)

**Comment by tjhei** [comment]
> But it can't have been #2254 because that didn't even touch this file.

oh, you just modified cite.html! We should unify the entries. Patch incoming.

**Pull request merged**
