### PR TITLE
set required ASPECT version in plugin files

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by tjhei** [comment]
@gassmoeller turns out I am not trusted. ;-)

**Comment by gassmoeller** [comment]
Oh, did you check if I put in the correct email address?

**Comment by tjhei** [comment]
> Oh, did you check if I put in the correct email address?

I don't know. Maybe we should print the email address before bailing out?

I just triggered a trusted build manually...

**Comment by tjhei** [comment]
> Maybe we should print the email address before bailing out?

see #2248

**Pull request merged**
