### PR TITLE
Modify cookbooks to have different output directories

### PR DESCRIPTION
**Pull request by hlokavarapu**
Resolve issue/enhancement #1482 . Set the output directory to the format `output-<cookbookname>. For parameter files without the variable output directory, I added the appropriate variable and value to the parameter file.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Could you take a look if this affects the manual or any parameter file parts that are in there?

**Comment by hlokavarapu** [comment]
I double checked that the manual compiles successfully, @gassmoeller . However, within the manual, specifically in the cookbooks section, the parameter "set Output directory" is out-of-date.

**Comment by gassmoeller** [comment]
Would it be much work to update that one? Just search for the phrase and replace the content?

**Comment by bangerth** [comment]
Where in the manual is the place still wrong? If this is in one of the code snippets shown there, then you may have to adjust the code snippets in the `doc/manual/cookbooks/` subdirectories the same way you adjusted the original cookbook input files.

**Comment by hlokavarapu** [comment]
Yeah, I don't mind looking into this. In the manual, in sec. 5.2.1, where the **input file** is written out as

```
# At the top, we define the number of space dimensions we would like to
# work in:
set Dimension = 2
# There are several global variables that have to do with what
# time system we want to work in and what the end time is. We
# also designate an output directory.
set Use years in output instead of seconds = false
set End time = 0.5
set Output directory = output
# Then there are variables that describe the tolerance of
```
The parameter value of Output directory does not reflect the file cookbooks/convection-box.prm

**Comment by bangerth** [comment]
This snippet comes from `doc/manual/cookbooks/convection-box/box.prm`. You'll have to adjust that snippet (and others in that subdirectory that now no longer match).

**Comment by hlokavarapu** [comment]
Alright, I have refactored all instances of "set Output directory" for all cookbooks in the manual.

**Comment by gassmoeller** [comment]
Thanks!

**Pull request merged**
