### PR TITLE
Update README maintainer and developer lists

### PR DESCRIPTION
**Pull request by naliboff**
This PR updates the developer and maintainer lists in the README file. Are their other similar lists that should be updated?

Also, can someone with the right website permissions (@gassmoeller, @tjhei?) provide @bobmyhill the correct settings for merging PRs, running tester, etc?

* [X] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).

### CODE REVIEW

**Comment by tjhei** [comment]
what about AUTHORS.md?

**Comment by naliboff** [comment]
@tjhei - right :-). I update the commit to include `AUTHORS.md`.

**Comment by tjhei** [comment]
Thanks. Should we remove the redundancy by deleting the info from README and reference AUTHORS instead?

**Comment by MFraters** [comment]
Since this is only intended as an update, I would be in favour of merging this now and think about restructuring in a different pull request if that is what we want.

**Review by tjhei — APPROVED** [review]

**Pull request merged**
