### PR TITLE
unit_tests: utility to compare std::vectors

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by tjhei** [comment]
@pmbremner take a look

**Comment by bangerth** [comment]
That's one way to create patches -- add useless functionality ;-)

**Comment by tjhei** [comment]
> That's one way to create patches -- add useless functionality ;-)

What about adding empty lines?

**Comment by bangerth** [comment]
On 06/25/2018 06:46 PM, Timo Heister wrote:
> What about adding empty lines?

Not saying I'm beyond these tactics ;-)

**Pull request merged**
