### PR TITLE
Remove project to Q1 option for material averaging in the Elasticity rheology

### PR DESCRIPTION
**Pull request by anne-glerum**
There are several reasons why the Material Averaging options project to Q1  and project to Q1 viscosity only cannot be used within elasticity.cc (see changed comments). Therefore AssertThrow that these averagings are not used.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [ ] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Review by gassmoeller — APPROVED** [review]
Just for reference: One of the reasons for this limitation is #698.

**Comment by anne-glerum** [comment]
I had to change the MaterialAveraging for 5 tests, I set it 'harmonic averaging viscosity only'. Two tests then had their results changed, the viscoelastic_bending_beam_gmg quite significantly.

**Comment by gassmoeller** [comment]
Are you ok with the changes to the tests? I can certainly merge, it is not unexpected that the output changes if the averaging changes.

**Comment by anne-glerum** [comment]
Yes, I'm fine with it. The bending beam is quite sensitive to the averaging.

**Comment by anne-glerum** [comment]
@gassmoeller All testers are happy now.

**Review by gassmoeller — APPROVED** [review]
Nice! Good to go.

**Pull request merged**
