### PR TITLE
Fix run-time parameters for manual

### PR DESCRIPTION
**Pull request by gassmoeller**
I tried to update the runtime parameters in the manual for a colleague and found a bunch of latex errors that we did not catch during review. Would it be possible to include a check on the tester for successful update of the parameter section and consequent creation of the manual? This could also be done for the manual that is linked online. Currently, we have an up-to-date manual with a parameters section that is at the pre-hackathon state.

### CODE REVIEW

**Comment by bangerth** [comment]
Some of the changes here are not backward compatible, but I decided to merge anyway because these were recent additions so the number of people affected is likely small.

**Comment by bangerth** [comment]
As for the question you asked: I think we had come to conclude that just creating `parameters.tex` is a big enough hassle that we didn't want to deal with it for each patch.

I'd be ok with making such a change, but I don't feel particularly strongly about it -- we have simply been doing it on a semi-periodic basis, and it's part of the release tasklist. @tjhei ?

**Comment by tjhei** [comment]
I agree 100%.

**Comment by gassmoeller** [comment]
Ok. I can live with that. I was just surprised that we offer a manual, which states "generated September 27, 2015", but the parameter list inside is at the state of May 24. But I can imagine it is a lot of trouble to update or test the successful generation automatically. I guess it is ok, since this is only the development version.

**Comment by bangerth** [comment]
It's probably not terribly difficult to add this to the Travis scripts to check.

@gassmoeller : What are the commands one needs to execute to create the `parameters.tex` file?
@tjhei : I can't seem to find where we configure the commands we run on Travis. Do you remember?

**Comment by gassmoeller** [comment]
One needs to run ./update_parameters.sh in the doc/ directory. The script assumes that an executable exists in `../` i.e. an in-source build. After that `make manual.pdf` in the doc/ folder should succeed if all parameters are named correctly.

**Comment by tjhei** [comment]
> I was just surprised that we offer a manual ...

should be fixed tomorrow. :-)

> @tjhei : I can't seem to find where we configure the commands we run on Travis. Do you remember?

Travis? We are not using Travis for ASPECT. You mean how I generate http://www.math.clemson.edu/~heister/manual.pdf ? This is just a cronjob on my machine that does ```git fetch; make manual.pdf```. The code for that is not online.
 
Or do you mean the commit checks? This is here: https://github.com/tjhei/gitautotester/tree/officialtester 
I already experimented with compiling the documentation, but I disabled it right now (see the "exit 0") because my virtual machine doesn't have the required tex packages: see https://github.com/tjhei/gitautotester/blob/officialtester/test.sh

Or do you mean deal.II? https://github.com/dealii/dealii/blob/master/.travis.yml

**Comment by bangerth** [comment]
On 09/28/2015 10:06 AM, Rene Gassmöller wrote:
> One needs to run ./update_parameters.sh in the doc/ directory. The
> script assumes that an executable exists in |../| i.e. an in-source
> build. After that |make manual.pdf| in the doc/ folder should succeed if
> all parameters are named correctly.

It might almost be simple enough to periodically run this as part of a 
cron job that could then also submit a pull request...

**Comment by bangerth** [comment]
> Or do you mean the commit checks? This is here:
> https://github.com/tjhei/gitautotester/tree/officialtester

That's what I had in mind.


> Or do you mean deal.II?
> https://github.com/dealii/dealii/blob/master/.travis.yml
We could presumably set something like this up for ASPECT as well.

**Comment by tjhei** [comment]
I will create a "manual cronjob" (recurring monthly reminder in my calendar) for now. ;-)

**Comment by bangerth** [comment]
:-)

**Pull request merged**
