### PR TITLE
use this->introspection().polynomial_degree.velocities  when refer to the degree of velocity polynomial basis

### PR DESCRIPTION
**Pull request by yinghe616**
This patch will address #1582

### CODE REVIEW

**Comment by yinghe616** [comment]
@gassmoeller do you know why this error happens? I thought the new changes should either affect most of the tests or not affect any at all...

**Comment by yinghe616** [comment]
By looking at other PRs that all failed at the same test, I think the conflict was due to Shangxin's test example was added before the new change of dynamic_topography.cc, and the new output results was not updated after that.

**Comment by bangerth** [comment]
Can you just do
```
  git checkout master
  git pull upstream master
  git checkout YOURBRANCH
  git rebase master
  git push -f origin YOURBRANCH
```
? This way you should get all recent changes, and it forces the tester to run again.

**Comment by yinghe616** [comment]
I did rebase before, so my branch  should be up to date with the more recent upstream. But anyhow I pushed it again and  forced the tester to rerun.

**Pull request merged**
