### PR TITLE
Add position vector

### LINKED ISSUE #521: viscous_dissipation_statistics does not set in.position
The viscous dissipation statistics does not set the material model input position. This is only problematic if the material model uses the position, but still we should fix this at some point. Maybe the whole postprocessor is obsolete, since the new heating_statistics postprocessor generates the same output with all the other heating terms as well.

### PR DESCRIPTION
**Pull request by bangerth**
Fixes #521 by also providing a position vector for a postprocessor.

Also update the description text of the postprocessor.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Yes this fixes the problem. Since it is a really rare case, I think the effort to create a test is too large. Especially since these sort of problems should be prevented, when we move these initializations into the constructor of MaterialModelInputs in the near future.

**Comment by gassmoeller** [comment]
I think this is ready to merge.

**Comment by tjhei** [comment]
So why did the floating point exceptions not trigger here? Or is it because this postprocessor is not tested with a material that uses the position?

**Comment by gassmoeller** [comment]
I guess no material model uses the position  to calculate anything that is of interest for this postprocessor (although I am not sure what depth-dependent does, it should use the position to calculate the viscosity). In the case I noticed this, I got a floating point exception. But this case is far too complicated to change it into a test.

**Pull request merged**
