### PR TITLE
nsinker: set pressure scaling to 1.0

### PR DESCRIPTION
**Pull request by tjhei**
using #5761

### CODE REVIEW

**Review by gassmoeller — COMMENTED** [review]
Are there nsinker tests? Do they use the new pressure scaling?

**Comment by tjhei** [comment]
> Are there nsinker tests? Do they use the new pressure scaling?

Yes. Yes, they should. I am waiting for the tester to tell me how to update... :-)

**Comment by tjhei** [comment]
Fascinating. It looks like no test is affected by it. This is probably because the tests are too coarse to trigger it.

**Review by gassmoeller — APPROVED** [review]
As long as there are tests I am ok. If the change in pressure scaling is small enough to not affect the tests that is alright.

**Comment by tjhei** [comment]
> If the change in pressure scaling is small enough to not affect the tests that is alright.

The pressure scaling in nsinker is around 10 when I checked. Maybe on coarse meshes it is even less.

**Pull request merged**
