### PR TITLE
Update gravitational constant

### PR DESCRIPTION
**Pull request by pmbremner**
Updated the gravitational constant to match the recommended value from CODATA.

The published value (with standard error in parenthesis) and the reference were added to the comments.

This change aids gravity comparisons of benchmarks with published studies.

Pull Request Checklist. Please read and check each box with an X. Delete any part not applicable. Ask on the [forum](https://community.geodynamics.org/c/aspect) if you need help with any step.

*Describe what you did in this PR and why you did it.*

### Before your first pull request:

* [x] I have read the guidelines in our [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) document.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).

### CODE REVIEW

**Review by bangerth — APPROVED** [review]
I would love us to be able to run simulations where this is the limiting factor on the accuracy of results :-)

**Comment by tjhei** [comment]
Well, it does matter for a few tests, apparently. 😉

**Comment by bangerth** [comment]
It turns out that a number of tests are apparently sensitive enough to actually fail now:
```
	241 - dynamic_core (Failed)
	278 - geoid (Failed)
	279 - geoid_no_topo (Failed)
	280 - geoid_visualization (Failed)
	302 - gravity_point_values_list (Failed)
	303 - gravity_point_values_map (Failed)
	304 - gravity_point_values_spiral (Failed)
	716 - spectral_comparison (Failed)
```
Would you mind updating the test outputs?

**Comment by pmbremner** [comment]
I'll start working on these

**Comment by pmbremner** [comment]
The above commits should cover all the files from the failed tests

**Comment by bangerth** [comment]
Let's see what the tester says. I only spot checked, but is your sense also that the changes are marginal and likely correct?

**Comment by pmbremner** [comment]
I believe they are correct. Some values differ by more then a marginal amount, though, such as sin and cos coefficients. But summary values were the same or nearly the same, such as CMB heat flux in dynamic_core

**Comment by bangerth** [comment]
OK, good to merge once the checks come back green!

**Comment by pmbremner** [comment]
Hmm, are the tests still failing? I must need to do something more

**Comment by tjhei** [comment]
Did you apply changes-test-results.diff as explained in the pdf manual?

**Comment by pmbremner** [comment]
The diff file has now been applied. Rene helped me apply it and to squash the commits. Hopefully this fixes it

**Review by gassmoeller — APPROVED** [review]
Looks good now.

**Pull request merged**
