### PR TITLE
Issue 2416 - Added copyright statement to 4 :.cc cookbook files that …

### LINKED ISSUE #2416: Add copyright headers to cookbook .cc files
As mentioned in #2394, it turns out that we have never added the usual copyright headers to the .cc files of cookbooks. We should fix this.

### PR DESCRIPTION
**Pull request by ljhwang**
Fixes #2416 - Added copyright statement to 4 .cc cookbook files that did not have copyright header.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Looks good, ready to merge if the tester is happy. This fixes #2416.

**Comment by tjhei** [comment]
are we okay with 2011-2018?

**Comment by bangerth** [comment]
I wouldn't worry about the years -- these files are all copies in some sense from something earlier, so I don't think 2011-2018 is technically incorrect.

The original text had some nice line breaks that make things easier to read:
```
/*
  Copyright (C) 2011 - 2018 by the authors of the ASPECT code.

  This file is part of ASPECT.

  ASPECT is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2, or (at your option)
  any later version.

  ASPECT is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with ASPECT; see the file LICENSE.  If not see
  <http://www.gnu.org/licenses/>.
*/
```

**Pull request merged**
