### PR TITLE
Ascii_Velocity

### PR DESCRIPTION
**Pull request by scotttarlow**
Allows user to prescribe a velocity solution based on an ascii file.

### CODE REVIEW

**Comment by bangerth** [comment]
Can you please fix the indentation? The correct style can be seen here: http://www.math.clemson.edu/~heister/aspect-astyler-logs/31cddbc00b20ed4be04c6a1b98e4b184e68193d2/log

Or you could install the astyle program (ask anyone around here how to do that).

**Comment by bangerth** [comment]
The indentation still fails :-(

**Comment by gassmoeller** [comment]
ok ready to merge.

**Comment by bangerth** [comment]
@scotttarlow : as a follow-up, can I ask you to
* add an entry to changes.h
* rename the files "Ascii_data.*" to "ascii_data.*" (all lower-case)

You'll have to do this with a separate pull request.

**Comment by bangerth** [comment]
Ah, forget about the naming issue -- that's already in #494. But the changes.h entry would be useful.

**Pull request merged**
