### PR TITLE
Log particle advection and update

### PR DESCRIPTION
**Pull request by gassmoeller**
This logs the point in time when particle advection and update actually happen, just like we do for compositional fields. This will change about every output, but I think it is worth it, because it clarifies that even when particles are listed as postprocessor their advection happens with the compositional fields.

### CODE REVIEW

**Review by tjhei — APPROVED** [review]
Is it obvious what solving particles means? I would have called it "advecting particles..." or something similar.

**Review by bangerth — COMMENTED** [review]
Like @tjhei I think this would read better if you said "Advecting particles..."

**Comment by gassmoeller** [comment]
"Advecting particles ... " was actually what I had in a first version of this PR, but then I thought "Solving" is more similar to the other fields. Anyway, I agree Advecting is better. I have updated the code and will update the tests when the tester is done.

**Comment by tjhei** [comment]
That is weird. I have to investigate if it is one of the machines. If the build doesn't complete in 30 minutes when it normally takes 5 minutes, the tests won't complete either. We can still build much faster, as you can see:
https://ci.tjhei.info/job/aspect/job/main/

**Review by tjhei — APPROVED** [review]

**Pull request merged**
