### PR TITLE
Depth dependent

### PR DESCRIPTION
**Pull request by maxrudolph**
Add depth-dependent version of Simple material model and simple, 2d cartesian periodic box test case using the new "depth dependent simple" model.

### CODE REVIEW

**Comment by tjhei** [comment]
Should we change this to use the "new" ```MaterialModel::execute``` format? What do others think? /run-tests

**Comment by maxrudolph** [comment]
Yes, I think that migrating this to the new MaterialModel::execute format makes sense.
Having thought about this a bit more, I think that it would be preferable to add this depth-dependence to Simple. A depth-dependent and temperature-dependent flow law is still very simple relative to the more complicated flow laws. Making this change to Simple instead of adding a new Material model would also keep the code base more compact and would make future changes to the MaterialModel interface affect fewer Material models. Thoughts?

**Comment by bangerth** [comment]
I still think that making "Simple" more complicated is the wrong direction. But am willing to listen.

**Comment by maxrudolph** [comment]
Closing this pull request.

**Pull request closed without merging**
