### PR TITLE
add advection benchmarks

### PR DESCRIPTION
**Pull request by tjhei**
Add a few new benchmarks:
rotate-compare2

drop-compare-end

### CODE REVIEW

**Comment by tjhei** [comment]
Do you want me to put pictures/videos somewhere? Manual?

**Comment by tjhei** [comment]
> Maybe just add them to the benchmarks/ folder for now, until we know what to write?

Yes, I agree. There also other smaller modifications to SUPG that might change the results...

**Comment by gassmoeller** [comment]
Then feel free to merge once you have added the images.

**Comment by bangerth** [comment]
I'm removing the 'ready to merge' label again since @gassmoeller wanted changes to happen before it should be merged.

**Comment by tjhei** [comment]
I added a short section in the manual. I will create a separate PR for the documentation of EV/SUPG later, but I decided to create the section already.

**Pull request merged**
