### PR TITLE
fix gravity test.

### PR DESCRIPTION
**Pull request by MFraters**
The tester in #3745 fails because of a difference in the tester output in an unrelated file/test. This fixes the test reference output.

### CODE REVIEW

**Comment by tjhei** [comment]
oh no, I think I broke master by merging #3731 before the tester finished. :-(

**Comment by MFraters** [comment]
> oh no, I think I broke master by merging #3731 before the tester finished. :-(

ah, I guess that's why two of the testers are now set as required? :P

**Comment by tjhei** [comment]
> ah, I guess that's why two of the testers are now set as required? :P

yes, a mistake that is easy to make...

**Comment by gassmoeller** [comment]
Tests have finished.

**Pull request merged**
