### PR TITLE
Do initial global refinement correctly in parallel

### PR DESCRIPTION
**Pull request by jdannberg**
### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [x] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Comment by jdannberg** [comment]
See #4507.

**Review by bangerth — COMMENTED** [review]
This is probably not wrong, but it shouldn't make a difference. Or does it for you?

At least in principle, deal.II shouldn't care about what flags are or aren't set on anything other than locally owned cells. The only place I can think of is the mesh smoothing algorithm, but I don't recall what it does in parallel computations -- I'm pretty sure it doesn't import neighboring cells's information, so it's possible that whether or not you set something on a ghost cell makes a difference there.

**Comment by tjhei** [comment]
It does make a difference because of mesh smoothing.
I think we need a different solution, though. We should do the same communication step we do in the normal refinement.

**Comment by bangerth** [comment]
I agree that we should probably do that, but it doesn't change the fact that mesh refinement might depend on the number of processes because the `prepare_coarsening_and_refinement()` function doesn't do this every time it does a sweep over all cells to do the smoothing. We should do it there as well.

But I would accept a patch along the lines you mention. I would change the return type of the `pack()` function to `unsigned char`, though. (Or `std::uint8_t` if you like that better.)

**Comment by bangerth** [comment]
What do we do with the current patch? I think it's useful if only because it reduces the amount of work by a marginal amount. I'm tempted to merge, but it might be incompatible (despite the tests succeeding) so I thought I'd give others the chance to object.

**Review by bangerth — APPROVED** [review]

**Comment by tjhei** [comment]
This patch might change the refinement in some situations, but I would argue that the old behavior is broken. I agree with merging and i will follow up with the other suggestion.

**Comment by tjhei** [comment]
Actually, we should add a test as the current change did not change any of the existing ones. @jdannberg do you have something that you could use?

**Comment by jdannberg** [comment]
I have added a slightly modified version of the test case that Anne sent. The image below shows the difference between the new version (left) and the current master (right) run with 8 processors on my laptop. The minimum/maximum refinement function only depend on the vertical coordinate direction, so the image on the right shows the problem that Anne mentioned. 

(I was on vacation last week and just came back to this today.)

mesh

**Review by tjhei — APPROVED** [review]
awesome, thank you.

**Pull request merged**
