### PR TITLE
Document more clearly what we mean by 'depth' in the geometry models.

### LINKED ISSUE #643: Depth of geometry models with free surface not consistent after first time step
The way the depth is currently calculated in all the geometry models is after the first time step only correct if the free surface is not used. When the free surface is used, the topography is not accounted for, resulting in a incorrect depth. This may be relevant for for example depth dependent material models and depth dependent mesh refinement. 

The challenge in fixing this problem is that the change of the geometry has to be calculated and interpolated. There are several solutions possible, and I am wondering what your thoughts on this matter are. 

The first solution would be to place al responsibility with the geometry models. It is possible that they like the topography post-processor loop over all the surface elements and interpolate the topography between those points to calculate the correct depth.

A second solution can be to share the responsibility between the geometry model and the free surface code. The free surface code would calculate and interpolate it (or do something fancy with a manifold as mentioned in https://github.com/geodynamics/aspect/issues/369) and the geometry model only has to ask what the topography component of the depth is and account for it.

Personally I think the second option is the preferred one since it prevents a lot of code duplication, safes a lot of computation if the free surface code computes the topography once everytime the free surface is updated and keeps the geometry models clean. Or is there a better/simpler way?

Here is a picture of the problem (to make this I needed to comment out the asserts in the box geometry model, because when I ask for depth, it can't deal with a negative depth).

depth_problem

### PR DESCRIPTION
**Pull request by bangerth**
Fixes #643.

### CODE REVIEW

**Comment by tjhei** [comment]
I don't really like the fact that you are copy&pasting the same blob over and over. This will get out of sync especially because plugins will be copied by others. I would a) just put it in the base class or b) use ```@copydoc```.

**Comment by bangerth** [comment]
You didn't read it right -- the second paragraph of each class is actually different. Otherwise the right solution would have been to not have a comment at all in the derived classes, which implies that doxygen takes the comment from the base class.

**Comment by tjhei** [comment]
Yes, I saw that, but you are still copying ~20 lines of text that will get copied around by other people. You could do
```
/**
 * @copy_doc Interface::depth()
 *
 * Here is something else I want to say for this specific function.
 */
```

**Comment by bangerth** [comment]
Fair enough. How about this version (which only documents the differences, rather than first copying a long generic blob and then adding a single sentence)?

**Pull request merged**
