### PR TITLE
Improve seismic anomalies

### PR DESCRIPTION
**Pull request by bobmyhill**
Added reference profile scheme to the seismic anomalies postprocessor, which provides a percentage anomaly relative to the Vp and Vs calculated by evaluating the material model at the P-T conditions given by adiabatic conditions.

### CODE REVIEW

**Comment by tjhei** [comment]
please fix the compile bug, Bob.

**Comment by bobmyhill** [comment]
Ooops, sorry, I have no idea how I stripped out those }s :/

**Comment by tjhei** [comment]
please rebase to master and apply the patch to fix the test output

**Pull request merged**
