### PR TITLE
Remove cxx11 includes

### PR DESCRIPTION
**Pull request by gassmoeller**
One step towards #2375. This is work in progress, I need to go over the code and look for broken indentation, I just want to see if tests fail as well.

### CODE REVIEW

**Comment by bangerth** [comment]
You've got conflicts that need to be resolved.

**Comment by bangerth** [comment]
You'll have to fix this:
```
/home/dealii/source/tests/latent_heat_enthalpy.cc
/home/dealii/source/tests/latent_heat_enthalpy.cc:30:41: fatal error: deal.II/base/std/unique_ptr.h: No such file or directory
 #include <deal.II/base/std/unique_ptr.h>
                                         ^
```

**Comment by gassmoeller** [comment]
Lets postpone this PR to after the hackathon, it is too disruptive for anyone developing new plugins at the moment.

**Comment by gassmoeller** [comment]
Rebased and should be ready to go if the testers are happy.

**Pull request merged**
