### PR TITLE
make FPE optional

### PR DESCRIPTION
**Pull request by tjhei**
- add cmake parameter for toggling FPE exceptions
- FPE checks are turned off by default
- update write_config to include more flags

### CODE REVIEW

**Comment by tjhei** [comment]
@bangerth Do I remember correctly that you preferred the default to be OFF? I think ON is a better default, because any option that might help find bugs during development is a good idea.

Anybody else got an opinion on it?

**Comment by tjhei** [comment]
alternative suggestion:
- enable by default (debug mode only of course)
- disable on intel

**Comment by bangerth** [comment]
Let's enable it by default but disable on the Intel compiler.

**Comment by tjhei** [comment]
Okay, this disabled them on intel. Note that they work for me with intel 15 as mentioned in #500 though.

**Comment by bangerth** [comment]
Want to disable it only for earlier versions of icc? She was using icc 13.something.

**Comment by bangerth** [comment]
I'm merging this for now so that it returns everyone to a working state. Follow-up patches to limit disabling this for ICC only for versions prior to 15 welcome :-)

**Comment by tjhei** [comment]
I have to admit that I don't care about having this enabled for old intel compilers, especially because I am unable to test this without a big hassle.

**Comment by bangerth** [comment]
Right. That's why I said "disable for icc < 15, enable for everyone else".

**Pull request merged**
