### PR TITLE
Fix code block markup.

### PR DESCRIPTION
**Pull request by bangerth**
See the correct syntax in quickref.md, and confirmed by @cmills1095 .

/rebuild

### CODE REVIEW

**Review by tjhei — APPROVED** [review]
OK!

**Comment by tjhei** [comment]
let's wait for #4661

**Comment by bangerth** [comment]
Rebased.

**Comment by bangerth** [comment]
I've also pushed a second commit that does the same markup change for ksh/gnuplot/prmfile. The latter two may not be configured so far, but we can get to that at some point.

**Comment by bangerth** [comment]
Ugh, this triggers an internal error in sphinx. What do we do about that?

**Comment by gassmoeller** [comment]
My guess would be Sphinx just doesnt know some of these other file formats. Can we merge the c++ separately and figure out which of the other formats work? If I followed this thread correctly (https://stackoverflow.com/questions/11315504/sphinx-list-of-supported-languages-for-highlighting) this is the list of supported languages: https://pygments.org/languages/

**Comment by bangerth** [comment]
See also #4669.

**Comment by bangerth** [comment]
But yes, sure. I dropped the second commit, let's see whether that helps.

**Review by gassmoeller — APPROVED** [review]

**Pull request merged**
