### PR TITLE
Make sure we get a reasonable exception when using volume of fluid in 3d

### PR DESCRIPTION
**Pull request by bangerth**
As mentioned in #3186 (and #835), the volume of fluid method isn't implemented in 3d right now. Make sure we get an error message at the earliest possible place about this.

@class4kayaker , @egpuckett -- FYI.

### CODE REVIEW

**Comment by egpuckett** [comment]
Hi @bangerth Did you notice that some checks didn't pass: 

jenkins.tjhei.info/pr-head — This commit cannot be built

**Comment by tjhei** [comment]
> jenkins.tjhei.info/pr-head — This commit cannot be built

this is fixed now. Hiccup on my tester.

**Comment by bangerth** [comment]
Seems to pass the tester now.

**Comment by egpuckett** [comment]
OK, As you know I can't merge this.

**Pull request merged**
