### PR TITLE
Remove unnecessary particle backups

### LINKED ISSUE #4019: ParticleHandler is  backed up twice
The ParticleHandler is backed up in start_timestep(), but when an iterative Advection scheme is used, they are again backed up at the start of the iterations, to be restored after each Advection solve. This second backup can be removed.

### PR DESCRIPTION
**Pull request by gassmoeller**
This should fix #4019. @anne-glerum do you have a test case? It seems we have no test at the moment for an iterated solver scheme and particles.

### CODE REVIEW

**Comment by anne-glerum** [comment]
Great! I have a test case somewhere, shall I make a separate PR for it?

**Comment by gassmoeller** [comment]
You should have permissions to checkout this branch and directly push to it (because you are maintainer and this is an open PR). So feel free to directly add it to this PR (or you can also make a PR against my branch).

**Review by bangerth — COMMENTED** [review]
Given that it passes the tests, this looks reasonable to me.

**Comment by gassmoeller** [comment]
I would like to wait for a test, because I do not think we are currently testing the iterated schemes with particles.

**Comment by anne-glerum** [comment]
OK, I've added a test and checked that for higher resolution it gives the same results as for the single Advection, iterated Stokes scheme and as for a field instead of particles. 

I had to adapt the test a little bit as compared to the single Advection scheme test that is already there,  because the sudden high velocity prescribed threw off the temperature solver in the second nonlinear iteration.

 As a side-note, we have been using the iterated Advection with particles in large setups as well.

**Comment by gassmoeller** [comment]
Excellent, thanks! Could you replace the output files of the test with gnupot output to make them readable? Otherwise ready.

**Comment by gassmoeller** [comment]
Thanks! Can someone else approve and merge? Since I opened the PR I can not approve.

**Pull request merged**
