### PR TITLE
add harmonic averaging to inclusion benchmark

### PR DESCRIPTION
**Pull request by bjs2**
- add harmonic averaging to the current list of averaging schemes (none, arithmetic, geometric) in the inclusion benchmark
- compared to other averaging schemes, harmonic averaging seems to reduce both velocity and pressure L2 errors
- https://docs.google.com/spreadsheets/d/1GYPWl4UOe-Jc5AkVqDX6PDQmL73YU-0S9rwBi7S-Ce0/edit?usp=sharing

### CODE REVIEW

**Comment by bangerth** [comment]
Is this script used anywhere, and are its results discussed anywhere?

**Comment by bjs2** [comment]
Yes, in both cases. See #788. Timo and I had run some tests on the inclusion benchmark with different averaging schemes, using this script. The script itself is just a nice way of going through the global and adaptive refinements without running through all of them separately. We also discussed its results as a group the other day.

**Comment by bangerth** [comment]
OK, thanks for the link to #788. I simply meant to ask whether we reference this script somewhere in the manual, for example, and need to update that description. But it doesn't seem to be the case, so all is good!

**Comment by bjs2** [comment]
Ah, I see. Do you think the script should be mentioned in the manual?

**Comment by bangerth** [comment]
If it wasn't, I don't see a pressing need to change the status quo.

**Comment by bjs2** [comment]
True

**Pull request merged**
