### PR TITLE
Add a read check for the Ascii data plugin

### PR DESCRIPTION
**Pull request by gassmoeller**
I repeatedly created data files that do not work with the current Ascii data plugin, and in its current form this does only create completely uninformative floating point exceptions. This PR at least improves the error message.

### CODE REVIEW

**Comment by tjhei** [comment]
Looks good. you can merge if all tests pass.

**Comment by bangerth** [comment]
Nice. We always said "more cow bell", but I think "more error checks" is the better approach.

**Comment by gassmoeller** [comment]
I had to look up "more cow bell", but yes :smile:

**Comment by bangerth** [comment]
Yes, I suspected that I could get you with this. But it's an easy-to-find staple of American pop culture, even though it's already 15+ years old.

**Comment by bangerth** [comment]
Welcome to 'merica!

**Pull request merged**
