### PR TITLE
Add results of manual generation to gitignore

### PR DESCRIPTION
**Pull request by class4kayaker**
This pull request adds the files automatically generated by running the Makefile in the documentation directory to .gitignore.

### CODE REVIEW

**Comment by tjhei** [comment]
I agree with adding manual.pdf, but aren't the .prm.out files part of the repo? I guess we can always regenerate them, so maybe we should remove all existing ones.

**Comment by class4kayaker** [comment]
I was ignoring the ones that were automatically generated when creating the manual, as that seems like a more reasonable approach. My thoughts were that if it is entirely automatically generated, then only what it is generated from should be included in the repository, to help reduce the number of non-local alterations later. I just checked, and what you stated does seem to be the existing convention. I can either change this to add the .prm.out file to the repo, or also remove all of the other .prm.out files in the same commit. Which would be the better approach?

**Comment by class4kayaker** [comment]
More in depth investigation shows that the file that is required is manual/cookbooks/finite_strain/finite_strain.prm.out, and that it is the raw file without the modifications that are in all of the other .prm.out files. I have therefore moved the file to .prm and removed the other .prm.out files.

**Comment by tjhei** [comment]
> More in depth investigation shows that the file that is required is manual/cookbooks/finite_strain/finite_strain.prm.out, and that it is the raw file without the modifications that are in all of the other .prm.out files. I have therefore moved the file to .prm and removed the other .prm.out files.

Yes, I agree.

Good work, thank you! :+1:

**Pull request merged**
