### PR TITLE
Add option to use 'geodynamic strain rate invariant' in visco plastic material model

### PR DESCRIPTION
**Pull request by naliboff**
The strain rate invariant commonly used in geodynamic simulations is distinct from the invariant calculated in deal.II.  This pull request gives users the option to use either form of the strain rate invariant in the visco_plastic material model.  

A number of the default values in the material model have also been updated so that the viscosity is not temperature, pressure or strain-rate dependent (i.e. linear viscous).  

Perhaps a new post-processor option should also be included in this pull request?

### CODE REVIEW

**Comment by gassmoeller** [comment]
Math could be so simple if everybody would agree to the same definitions :smile:. Thanks for bringing this up anyway. I have read myself a bit into the moment invariant vs. principle invariant discussion, but I still have some questions before going forward with this PR:
- from the description of the Drucker Prager material model (presumably written by @anne-glerum?), and a quick look into 'The finite element method: Solid mechanics' (Zienkiewicz & Taylor, google books) it seems like the two definitions for the second invariant should only differ by a minus sign. If this is true the change you implemented should not have any effect. I have not checked if our implementation turns out that way, could you do that? If they do differ: does the geodynamics community really use another (third) different definition for the second invariant? Do you maybe have a reference for that? I tried to check in CitcomS's code, and it looks to me like they use the moment invariant.
- In case we indeed have to go over this again, we probably need to add options to the strain rate and stress visualization output postprocessors, and also the drucker prager and diffusion dislocation material models. In particular, this would mean that using published coefficients is dangerous, if the definition of the strain rate used to fit them differs from ours. So lets make certain we are sure about the necessity of the change before creating a mess by using different definitions.

**Comment by naliboff** [comment]
@gassmoeller - Bah! You are absolutely right, the two methods give identical values.  As long as tensor components [0][0] and [1][1] are equal in magnitude and opposite in value, as they should be for the deviatoric strain rate, this will hold true. Shall I just delete the pull request or is it useful to keep it up as a reminder of the discussion?

**Comment by gassmoeller** [comment]
Could you quickly check if they are also the same for 3D? I have not checked that. If they are identical then feel free to delete the PR, it is archived on github anyway (in the list of closed PRs), so if the discussion comes up again we can always come back here.

**Comment by naliboff** [comment]
They are indeed the same for 3D, I will go ahead and delete the PR.  Sorry for the false flag!

**Comment by gassmoeller** [comment]
No problem at all. Better to raise issues then to keep bugs in the code.

**Pull request closed without merging**
