### PR TITLE
[WIP] Add test for resuming free surface.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Test for resuming free surface computations. Like #616, we should not merge until issues about bitwise reproducibility are resolved.

### CODE REVIEW

**Comment by tjhei** [comment]
which means waiting for the next trilinos release :-)

**Comment by ian-r-rose** [comment]
Or whatever is appropriate :-)

I could change it so it only requires numdiff comparisons.

**Comment by tjhei** [comment]
@ian-r-rose can you please rebase and test?

**Comment by ian-r-rose** [comment]
Can you force the tests to run?

**Pull request closed without merging**
