### PR TITLE
Remember that Patterns::Integer has *inclusive* bounds.

### PR DESCRIPTION
**Pull request by bangerth**
This is basically #2448, just done in the right place.

### CODE REVIEW

**Comment by tjhei** [comment]
Wait, ASPECT doesn't support 4d computations? :cry:

**Comment by tjhei** [comment]
can you rebase to master please?

**Comment by bangerth** [comment]
Yes.

**Comment by tjhei** [comment]
you rebased to a broken master, can you rebase again?

**Comment by bangerth** [comment]
Done. Let's see what happens.

**Pull request merged**
