### PR TITLE
fix newton assembly performance 3

### PR DESCRIPTION
**Pull request by MFraters**
Testing it again :)

### CODE REVIEW

**Comment by tjhei** [comment]
Looks good. The changes in test output seem minor at first glance. Can you update the test results?

**Comment by MFraters** [comment]
I am still surprised how much of a difference it makes. 

In the code the difference comes down to doing `(grads_phi_u[i] * (deta_deps * grads_phi_u[j])) * strain_rate` which it used to be or `grads_phi_u[i] * ((deta_deps * grads_phi_u[j]) * strain_rate)` which this pull request proposes. Looking at the paper, the second one seems to be more consistent with what we have written down, so I guess this change is fine, and I should indeed update the outputs.

**Comment by gassmoeller** [comment]
Is this ready from your side @MFraters ?

**Comment by MFraters** [comment]
Yes, I think it is ready. I will put a change file entry in a new pull request.

Final result (others are in #2381)
```
+---------------------------------------------+------------+------------+
| Total wallclock time elapsed since start    |      69.1s |            |
|                                             |            |            |
| Section                         | no. calls |  wall time | % of total |
+---------------------------------+-----------+------------+------------+
| Assemble Stokes system          |         1 |      1.35s |         2% |
| Assemble Stokes system Newton   |         4 |      8.95s |        13% |
| Assemble Stokes system Picard   |         3 |      4.09s |       5.9% |
| Assemble Stokes system rhs      |         6 |      4.49s |       6.5% |
| Assemble temperature system     |         7 |      10.9s |        16% |
| Build Stokes preconditioner     |         7 |      15.6s |        23% |
| Solve Stokes system             |         7 |        12s |        17% |
| Initialization                  |         1 |       5.3s |       7.7% |
| Postprocessing                  |         1 |      2.25s |       3.3% |
| Setup dof systems               |         1 |     0.779s |       1.1% |
| Setup initial conditions        |         1 |     0.987s |       1.4% |
+---------------------------------+-----------+------------+------------+
```

**Pull request merged**
