### PR TITLE
[WIP] Field types for viscoelasticity and corresponding rheology and EoS modules

### PR DESCRIPTION
**Pull request by bobmyhill**
A rebased version of #4260.
Still under development...

* [ ] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).
* [ ] I have tested my new feature locally to ensure it is correct.
* [ ] I have [created a testcase](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Comment by bobmyhill** [comment]
@MFraters, @naliboff and others: Currently 117 tests are failing. I slightly favour modifying the tests rather than making the compositional field checks more relaxed, but I'm open to other ideas.

	  3 - Picard_compressible (Failed)
	 25 - advect_mesh_vertically (Failed)
	 28 - airy_isostasy (Failed)
	109 - boundary_traction_function_cartesian_free_surface (Failed)
	110 - boundary_traction_function_spherical_free_surface (Failed)
	137 - check_compositional_field_names (Failed)
	157 - chunk_lithostatic_pressure_2d (Failed)
	163 - composite_viscous_outputs (Failed)
	165 - compositing_named_outputs (Failed)
	183 - compositional_heating (Failed)
	184 - compositional_heating_exclude_background (Failed)
	203 - compute-no-normal-flux-constraints (Failed)
	210 - continental_extension (Failed)
	220 - damped_viscoelastic_bending_beam (Failed)
	223 - dc_Picard_compressible (Failed)
	268 - dynamic_friction (Failed)
	275 - elastic_stabilization_time_scale_factor (Failed)
	294 - free_surface_VE_cylinder_2D_loading_fixed_elastic_dt_gmg (Failed)
	306 - free_surface_timestep_repeat (Failed)
	323 - gmg_mesh_deform_adaptive_bug2 (Failed)
	325 - gmg_mesh_deform_ghost_entries (Failed)
	330 - gmg_velocity_boundary_2d_box_no_flux (Failed)
	331 - gmg_velocity_boundary_2d_box_no_normal_flux (Failed)
	332 - gmg_velocity_boundary_2d_chunk_no_flux (Failed)
	333 - gmg_velocity_boundary_2d_chunk_no_normal_flux (Failed)
	334 - gmg_velocity_boundary_3d_box_no_flux (Failed)
	335 - gmg_velocity_boundary_3d_box_no_normal_flux (Failed)
	336 - gmg_velocity_boundary_3d_chunk_no_flux (Failed)
	337 - gmg_velocity_boundary_3d_chunk_no_normal_flux (Failed)
	382 - infill_density_flexure (Failed)
	417 - kinematically_driven_subduction_2d_case1 (Failed)
	430 - lithosphere_boundary_indicator (Failed)
	431 - lithosphere_boundary_indicator_3d (Failed)
	432 - lithosphere_boundary_indicator_3d_periodic (Failed)
	445 - material_model_dependencies_multicomponent (Failed)
	501 - merged_chunks_2D (Failed)
	502 - merged_chunks_3D (Failed)
	512 - multicomponent_arithmetic (Failed)
	514 - multicomponent_geometric (Failed)
	515 - multicomponent_harmonic (Failed)
	516 - multicomponent_max_composition (Failed)
	521 - newton_postprocess_nonlinear (Failed)
	601 - particle_interpolator_bilinear_limiter (Failed)
	638 - particle_property_integrated_strain_invariant (Failed)
	774 - slab_tip_depth (Failed)
	896 - visco_plastic (Failed)
	897 - visco_plastic_additional_plastic_outputs (Failed)
	898 - visco_plastic_adiabat_temperature (Failed)
	899 - visco_plastic_adiabatic_heating_density (Failed)
	900 - visco_plastic_adiabatic_pressure_in_viscous_creep (Failed)
	901 - visco_plastic_complex (Failed)
	902 - visco_plastic_composite (Failed)
	903 - visco_plastic_constant_viscosity_prefactor (Failed)
	904 - visco_plastic_derivatives_2d (Failed)
	905 - visco_plastic_derivatives_3d (Failed)
	906 - visco_plastic_diffusion (Failed)
	907 - visco_plastic_diffusion_dislocation_composite (Failed)
	908 - visco_plastic_dislocation (Failed)
	909 - visco_plastic_frank_kamenetskii (Failed)
	910 - visco_plastic_friction_function (Failed)
	911 - visco_plastic_gerya_2019_vp (Failed)
	912 - visco_plastic_newton_nonlinear_channelflow (Failed)
	913 - visco_plastic_peierls_cutoff_test (Failed)
	914 - visco_plastic_peierls_mei_exact (Failed)
	915 - visco_plastic_peierls_mei_viscosity_approx (Failed)
	916 - visco_plastic_phases (Failed)
	917 - visco_plastic_phases_compositions (Failed)
	918 - visco_plastic_phases_peierls_mei_exact (Failed)
	919 - visco_plastic_phases_plasticity (Failed)
	920 - visco_plastic_phases_viscosity (Failed)
	921 - visco_plastic_phases_viscosity_max_min (Failed)
	922 - visco_plastic_reference_density_profile (Failed)
	923 - visco_plastic_thermal_conductivity (Failed)
	924 - visco_plastic_track_noninitial_plastic_strain (Failed)
	925 - visco_plastic_vep_bending_beam (Failed)
	926 - visco_plastic_vep_brick_extension (Failed)
	927 - visco_plastic_vep_plate_flexure (Failed)
	928 - visco_plastic_vep_simple_shear (Failed)
	929 - visco_plastic_vep_stress_build-up (Failed)
	930 - visco_plastic_vep_stress_build-up_fixed_elastic_time_step (Failed)
	931 - visco_plastic_vep_stress_build-up_stress_averaging (Failed)
	932 - visco_plastic_vep_stress_build-up_yield (Failed)
	933 - visco_plastic_vep_stress_build-up_yield_particles (Failed)
	934 - visco_plastic_viscous_strain_weakening (Failed)
	935 - visco_plastic_yield (Failed)
	936 - visco_plastic_yield_max (Failed)
	937 - visco_plastic_yield_noninitial-plastic-strain_particles (Failed)
	938 - visco_plastic_yield_plastic_damper (Failed)
	939 - visco_plastic_yield_plastic_strain_weakening (Failed)
	940 - visco_plastic_yield_plastic_strain_weakening_particles (Failed)
	941 - visco_plastic_yield_plastic_viscous_strain_healing (Failed)
	942 - visco_plastic_yield_plastic_viscous_strain_weakening (Failed)
	943 - visco_plastic_yield_plastic_viscous_strain_weakening_particles (Failed)
	944 - visco_plastic_yield_strain_weakening (Failed)
	945 - visco_plastic_yield_strain_weakening_compositions (Failed)
	946 - visco_plastic_yield_strain_weakening_defect_corr_stokes (Failed)
	947 - visco_plastic_yield_strain_weakening_full_strain_tensor (Failed)
	948 - visco_plastic_yield_strain_weakening_full_strain_tensor_3d (Failed)
	949 - visco_plastic_yield_strain_weakening_no-advect_no_stokes (Failed)
	950 - visco_plastic_yield_strain_weakening_particles (Failed)
	951 - visco_plastic_yield_total_strain_healing (Failed)
	952 - visco_plastic_yield_viscous_strain_weakening (Failed)
	953 - visco_plastic_yield_viscous_strain_weakening_particles (Failed)
	954 - viscoelastic_bending_beam (Failed)
	955 - viscoelastic_bending_beam_averaging (Failed)
	956 - viscoelastic_bending_beam_gmg (Failed)
	957 - viscoelastic_bending_beam_particles (Failed)
	958 - viscoelastic_bending_beam_principal_stress (Failed)
	959 - viscoelastic_fixed_elastic_time_step (Failed)
	960 - viscoelastic_numerical_elastic_time_step (Failed)
	961 - viscoelastic_numerical_elastic_time_step_particles (Failed)
	962 - viscoelastic_plate_flexure (Failed)
	963 - viscoelastic_sheared_torsion (Failed)
	964 - viscoelastic_stress_averaging (Failed)
	965 - viscoelastic_stress_build-up (Failed)
	966 - viscoelastic_stress_build-up_gmg (Failed)
	967 - viscoelastoplastic_yield_plastic_viscous_strain_weakening (Failed)

**Comment by MFraters** [comment]
with modifying the tests, I assume you mean properly defining the compositional field types? That makes sense to me. 

I do want to note that this change will break any input file is using the visoelastic material model (and visco plastic later or even now looking at the tests) which doesn't have have those parameters defined. That makes it quite a larger breaking change in my mind and maybe something we should wait for for the next major release and be more lenient (considering unspecified as chemical composition) for now. Or am I overstating how much this will break peoples input files?

**Comment by bobmyhill** [comment]
@MFraters thanks for the quick reply. 

Maybe I can keep the changes to the material models, but add some code for later deprecation that assigns the composition types according to the implicit schemes currently in `main`? Then none of the current tests should break, and I can modify a couple of them to make sure everything will still work when the deprecated code blocks are removed?

**Comment by MFraters** [comment]
Yes, that sounds like a good solution to me. Then we need can start enforcing this starting in version 3.0.0. @gassmoeller @tjhei what do you think and do we have a list where we keep track of these kind of things?

**Comment by bobmyhill** [comment]
I just looked through the code, and don't see anywhere where we do this kind of thing. I was thinking of an ASPECT equivalent of `#if DEAL_II_VERSION_GTE(10,0,0)`, but maybe that's not the best way to do this?

**Comment by tjhei** [comment]
I would fix the tests first, then enable a section of code that makes things compatible for now, which we can remove closer to release. Can you create an issue to remove this blob with "milestone ASPECT 3.0"?
Regarding bigger changes, maybe we have enough to aim for a 3.0 release this year where we can break more than this?

**Comment by tjhei** [comment]
> don't see anywhere where we do this kind of thing

We only have ``DEAL_II_DEPRECATED`` do decorate functions that should not be used. There is nothing in ASPECT, so I would suggest you put the code in, mark it with a TODO, and create an issue on GitHub to remind us.

**Comment by bobmyhill** [comment]
Ok, thanks @tjhei, thanks @MFraters.

Have been looking through what I need to do this evening; it's a significantly larger job than it was in 2021. But it's also nice to see that `this->introspection().compositional_index_for_name()` is being used - that makes the work significantly easier. 

Here's my plan of attack:
- Find all occurrences of `this->introspection().get_composition_names()` - I think this covers the majority of places changes have to be made.
- Preserve old functionality if Field Types not set
- Add appropriate code to use Field Types, enforce the correct number of compositional fields in the material model section
- Duplicate selected tests to check old and new functionality, suffix originals with `_old_field_format`.

**Comment by tjhei** [comment]
Before you do too much more work, @bobmyhill , can you let me take another look first? Would it be possible to first merge a simple version of the current PR that just adds the new parameter and functions?

I would imagine we might be able to have the backwards compatible assignment of field types in one central location, for example. (if not field type is set, assign types based on names? Or how would you do the assignment automatically?)

**Comment by bobmyhill** [comment]
@tjhei, yes, I'm happy to make a small PR with just the new parameter and functions added. That is what @MFraters needs, so it might be the best option, even if we can't test it very thoroughly.

The PR currently puts some of the backwards compatibility in one of the Introspection functions, and another bit in elasticity.cc (see the TODOs). That should cover most cases, but I'll wait for the tester to tell me how much I've broken...

**Comment by bobmyhill** [comment]
Oh, another thing; I think "chemical component" is a better name than "chemical composition". Do you agree?

**Comment by naliboff** [comment]
> @tjhei, yes, I'm happy to make a small PR with just the new parameter and functions added. That is what @MFraters needs, so it might be the best option, even if we can't test it very thoroughly.

2nd vote for this approach and then updating this PR (breaking backwards compatibility) closer to the new release. Thank you again for all the work on this PR, it will be a huge improvement to the parameter file interface!

> Oh, another thing; I think "chemical component" is a better name than "chemical composition" for the field type name associated with bulk chemistry. Do you agree?

Yes, I agree "chemical component" makes more sense. What "lithology" or "rock type" also work? My only concern with the word "chemical" is that people may initially confuse with it with tracking specific chemical or mineral components/percentages, but in the end this will be well described in the parameter documentation, cookbooks, manual, etc.

**Comment by gassmoeller** [comment]
@bobmyhill: What is the status of this PR? From what I can see it looks like most of the functionality has been added in other PRs. Is there anything left in this PR or can it be closed?

**Comment by bobmyhill** [comment]
Most of these changes have already been made. Closing this PR.

**Pull request closed without merging**
