### PR TITLE
Move pressure correction into the assembly.

### LINKED ISSUE #298: potential bug: make_pressure_rhs_compatible
It looks to me that we are calling ```make_pressure_rhs_compatible``` more then once:
first in compute_initial_stokes_residual()
and then in solve_stokes(). I assume this breaks the correction as ```int_Gamma u \cdot n ``` is applied twice.  

I would suggest we move the call directly after assemble_stokes_system().

@jdannberg what do you think?

### PR DESCRIPTION
**Pull request by gassmoeller**
This should fix #298 . Lets see what the tester says about the changes. On my machine all of the iterated IMPES tests are working, and I also saw quite a speed-up compared to the old version, although the iteration count stayed constant. I am testing on battery though, so it might be related to throttling.

### CODE REVIEW

**Comment by tjhei** [comment]
Interestingly, none of the outputs changed. Did we have no iterated IMPES test that is compressible?

**Comment by tjhei** [comment]
But thanks for preparing the patch, looks good. :+1:

**Comment by gassmoeller** [comment]
You not only need a compressible iterated impes model to trigger the bug, but additionally you need a normal flux across the boundaries that is not balanced. I think we have no test for that at the moment. I can try to create one, but I am currently at Egu, so it might take a bit. Anyway, I think the only thing that I expect to change is the iteration count for the stokes solver in the first nonlinear iteration.

**Comment by tjhei** [comment]
Well, I think we can live without this test.

**Comment by tjhei** [comment]
Thanks for fixing this.

**Pull request merged**
