### PR TITLE
Reorder restart checks

### PR DESCRIPTION
**Pull request by gassmoeller**
This is an improvement related to #4341 and #4029. It reorders the operations upon resuming from a checkpoint so that:

- We correctly reach a useful assertion before trying to load the solution vector. This prevents the segmentation fault described in the linked issues and instead provides a useful error message (pressure normalization was changed incorrectly, or mesh deformation was not enabled for checkpoint)
- We now allow disabling pressure normalization during restart. We still do not allow to switch from surface to volume normalization or vice-versa since that makes no sense, however #4341 and #4029 showed that there is demand for switching on mesh deformation during a model for which we would like to be able to switch from surface pressure normalization to no normalization.

### CODE REVIEW

**Comment by gassmoeller** [comment]
@erinheilman or @elodie-kendall: Could you take a look at my changes in this PR and let me know if this would help you?

**Comment by tjhei** [comment]
> * We now allow disabling pressure normalization during restart. We still do not allow to switch from surface to volume normalization or vice-versa since that makes no sense,

Does it? We don't use the pressure from a previous time step, so it might be possible to change it freely. Did you try?

**Comment by gassmoeller** [comment]
> Does it? We don't use the pressure from a previous time step, so it might be possible to change it freely. Did you try?

I did not try and it might work, but I guess what I was saying is I cannot imagine an application case where it would be useful to do that. Doesn't mean there is no case out there.

**Comment by elodie-kendall** [comment]
Yes, @erinheilman says this has allowed a change in the P normalisation when switching the boundary condition. Thanks a lot!

**Pull request merged**
