### PR TITLE
Visco-Plastic material model 

### PR DESCRIPTION
**Pull request by naliboff**
A material model that combines viscous flow (diffusion, dislocation or composite creep) with a Drucker Prager yield criterion.  Pull request includes a test input file and associated output.

### CODE REVIEW

**Comment by bangerth** [comment]
Someone will get to your PR later, but for now feel free to reword the commit message of the first of your commits :-) Alternatively, since it seems to cancel the fourth, just drop both.

You have an unusual commit history here, with multiple merges. Which commit actually has the content you want considered? The usual approach to creating pull requests is not via merges, but to just base a branch somewhere on the master branch and let git do the merge when the pull request is accepted. If the starting point is no longer acceptable, then you'd typically do a rebase operation onto the current master, rather than merging master into your branch. Merges are not commonly done into a feature branch.

**Comment by naliboff** [comment]
Bah, I didn't realize my full commit history was pulled as well, just the file changes!  Bad day with git on the 5th, I'll go back and reword some commits.   Commit history and merges - I typically merge various branches with the master fairly frequently as a way to keep the branches up to date.  I can see how this creates all sorts of confusion in the commit history.  I'll follow the method you outlined (allowing git to handle the branch merge through pull request) from here on.  Sorry for the confusion!

**Comment by naliboff** [comment]
commit 2be77ce contains all of the relevant content

**Comment by naliboff** [comment]
Hmm, using merge is making things a bit tricky to modify coherently.  I'm going to close this pull request and re-issue it via a clean fork.  Easier to start over than fix the old bad merge/commit habits.

**Comment by bangerth** [comment]
As long as you are working on your own repository, the right way to merge newer mainline development into your own branch is to use git's "rebase" feature. This keeps your own commit history free of merge commits, yet gets you all of the recent changes. The internet will have a number of tutorials on how to rebase things.

**Comment by naliboff** [comment]
Yep, makes perfect sense.  Thanks again for the clarification and sorry for the confusion/mess.  Re-doing a pull request with a clean fork later today.

**Pull request closed without merging**
