### PR TITLE
Clarified documentation for reaction term

### PR DESCRIPTION
**Pull request by rrgrove6**

### CODE REVIEW

**Comment by tjhei** [comment]
@bangerth ? (I am biased here)

**Comment by gassmoeller** [comment]
Just saw that I need to stop clicking on single commits and instead comment on the whole pull request. Anyway, apart from the one sentence I commented on, I think the new explanation is less misleading.

**Comment by tjhei** [comment]
Agreed, Rene. @rrgrove6 can you change the sentence please?

**Comment by bangerth** [comment]
I think this looks good. Thanks for taking the time to clarify documentation -- we get these kinds of patches far too rarely and they are really appreciated!

**Pull request merged**
