### PR TITLE
GWB: disable fortran wrappers

### PR DESCRIPTION
**Pull request by tjhei**
we are not using them anyways

### CODE REVIEW

**Review by bangerth — APPROVED** [review]
I like it!

**Comment by bangerth** [comment]
Huh, except it doesn't work:
```
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_Fortran_COMPILE_OBJECT
```

**Comment by bangerth** [comment]
Please squash.

**Comment by tjhei** [comment]
done

**Review by MFraters — APPROVED** [review]

**Pull request merged**
