### PR TITLE
require deal.II 8.5.0

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by bangerth** [comment]
I suppose it's going to fail your 8.4.1 tester :-)

**Comment by tjhei** [comment]
> I suppose it's going to fail your 8.4.1 tester :-)

Yes. :-) But I have ``aspect-8.5-gcc-hd`` running. Let's see if it works.

**Comment by gassmoeller** [comment]
Results look good so far. When do you want to pull the trigger? #1452 and #1458 will likely give you conflicts, so maybe before merging them? Also should we stick to one gcc tester for the hackathon, or do you plan to enable the (slower) clang address-sanitizer tester as well? I would vote for keeping one gcc tester for the time of the hackathon, and enable the other one afterwards if necessary.

**Comment by tjhei** [comment]
> When do you want to pull the trigger?

It seems to work correctly so we could make the switch any time. @bangerth any opinion on this?

> Also should we stick to one gcc tester for the hackathon

Probably. This one has a turnaround of ~25mins right now. I think this is good enough for the hackathon. Ultimately I think we might be able to improve it by tuning the tests (see your other PR) and maybe by improving the setup (at the moment it is docker inside virtualbox).

> do you plan to enable the (slower) clang address-sanitizer tester as well? I would vote for keeping one gcc tester for the time of the hackathon, and enable the other one afterwards if necessary.

I have not set up the docker image for the clang sanitizer or the PETSc build yet. If I disable the 8.4 tester, I could run something else on that machine (aspect-8.5-gcc runs on a different machine). That means they could run at the same time.

**Comment by bangerth** [comment]
If we are asking hackathon participants to use deal.II 8.5, then that's what the tester should run as well. So I'm in favor of switching now.

For the hackathon, I think we should reduce the amount of testing to a single tester to improve turn-around. This was a problem last time around, where reviews were faster than the tester could check things, and everything got backed up.

**Comment by tjhei** [comment]
alright, I'll just push the button now and we'll see what happens. ;-)

**Comment by bangerth** [comment]
KABOOM!!!! The University just ended!

**Pull request merged**
