### PR TITLE
Remove detection and driver for parameter GUI.

### LINKED ISSUE #5706: remove parameter-gui?
I vote to remove cmake support for the QT based parameter GUI https://github.com/dealii/parameter_gui. Or is anyone using it?

### PR DESCRIPTION
**Pull request by tjhei**
closes #5706

### CODE REVIEW

**Comment by gassmoeller** [comment]
I would prefer if you could rename this PR. What you are doing is removing the automatic configuration of the ASPECT-GUI as part of the ASPECT build process. It is still possible to compile ASPECT-GUI separately and call it with ASPECT input file. I just want to avoid the perception that ASPECT-GUI is deleted.

**Comment by gassmoeller** [comment]
We agreed to keep this open for a bit until we see how #5697 develops.

**Comment by tjhei** [comment]
> What you are doing is removing the automatic configuration of the ASPECT-GUI as part of the ASPECT build process. It is still possible to compile ASPECT-GUI separately and call it with ASPECT input file.

Not really, I am also deleting ./doc/aspect-gui, the magic bash script that makes the GUI work.

**Comment by bangerth** [comment]
I'll rename to make this clearer. OK to merge from my side.

**Comment by bangerth** [comment]
This might be worth a changelog entry.

**Comment by tjhei** [comment]
changelog entry added. Since we are deleting the bash script that provides the deal.II parameter GUI with the parameter information, I would still think that this PR removes the GUI. I don't know how someone would use it after this PR is merged.

**Comment by gassmoeller** [comment]
You are right, I misinterpreted the PR when I wrote my first comment. Technically the deal.II program is still there, but it requires some special knowledge to run it after this PR is merged.

**Comment by bangerth** [comment]
@tjhei  Out of curiosity, why is it that you want to get rid of this? I don't really care one way or other, but it's a relatively small amount of code, and could at least in principle be useful to some.

**Comment by tjhei** [comment]
Because none of us uses it, so I assume it will stop working correctly (maybe it has already). We advertise it in the manual even though we know better ways to edit .prm files and that could lead people down a wrong path.
I think it is the same situation as the PETSc support, which was a good idea to remove.

**Review by gassmoeller — APPROVED** [review]
I took the liberty of rebasing this PR. I think we should merge this before the release. The VS code plugin is working well, so no need to keep this around.

**Pull request merged**
