### PR TITLE
update tasks/announcement

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by bangerth** [comment]
I wanted to do it from the phone but it says "Pull Requests that have a failing status can’t be merged from a phone" :-)

Feel free to merge if you want, or I'll do it in an hour

**Comment by tjhei** [comment]
I was waiting if I need to do any other announcement changes. Especially because the changelog URL is a guess, currently.

**Comment by bangerth** [comment]
Can I merge this now?

**Comment by tjhei** [comment]
No, wait please.

**Comment by tjhei** [comment]
okay, good to be merged.

**Pull request merged**
