### PR TITLE
Documentation: fix reference to a benchmark

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Review by gassmoeller — APPROVED** [review]

**Comment by gassmoeller** [comment]
You pushed this to the main repo that is why the testers run twice. Make sure to delete the branch afterwards.

**Comment by tjhei** [comment]
> Make sure to delete the branch afterwards.

I will. This happens when I create a PR by clicking the edit button. Super annoying.

**Comment by tjhei** [comment]
Do you understand why this happens?
```
The following tests FAILED:
	800 - stokes_solver_fail_A (Failed)
	801 - stokes_solver_fail_S (Failed)
```

**Comment by tjhei** [comment]
I think I will need to redo the PR from my repo...

**Comment by gassmoeller** [comment]
> I will. This happens when I create a PR by clicking the edit button. Super annoying.

That is weird, and it seems to be different for different users, see e.g. https://github.com/geodynamics/aspect/pull/4695

> Do you understand why this happens?

No idea :man_shrugging:

**Comment by gassmoeller** [comment]
Superseded by #4720.

**Pull request closed without merging**
