### PR TITLE
Added functor to do geometric averaging of viscosities

### PR DESCRIPTION
**Pull request by alarshi**
This PR adds a new functor, FunctorDepthAverageLogViscosity, and another output variable, log_viscosity, to compute and output the arithmetic mean of the log10(viscosity). This is added so that viscosity is averaged using geometric averaging and not arithmetic averaging (i.e., the average of viscosities 1e22, 1e20 is 1e21 and not 5.05e21).

* [X] I have read the guidelines in our [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) document.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [x] I have tested my new feature locally to ensure it is correct.

### CODE REVIEW

**Review by bangerth — APPROVED** [review]

**Comment by bangerth** [comment]
This looks good to me, although it would be nice to have a test for it. Do you think you can quickly adapt an existing test for it?

/rebuild

**Comment by alarshi** [comment]
@bangerth: Thank you for reviewing the PR! 
I added the test case in the latest commit. However, I see that many tests are failing now because the default depth average computes an additional field, ```log_viscosity```, not available in the previous tests. I will ask your help to find out a way to fix all the tests.

**Comment by bangerth** [comment]
That's the same issue @jdannberg had in #4186 :-) I'll find you on wonder.me in a few minutes, but in the meantime, can you rebase on top of the current master?

**Comment by gassmoeller** [comment]
@alarshi you will need to do a rebase to a current master, there are a lot of conflicts, probably because #4203 got merged in the meantime. Find one of us tomorrow if you need help with the conflicts during the rebase.

**Comment by gassmoeller** [comment]
Alright looks like this is ready, please squash the commits into one.

**Comment by alarshi** [comment]
@gassmoeller: Just pushed the squashed commits, thank you :)

**Comment by alarshi** [comment]
@gassmoeller : Hi Rene, this is a PR that uses ```log10(viscosities)``` for computing depth average. I rebased it to the current main, please let me know if there is anything remaining to do. It would be helpful for me if it can be merged in the main aspect.

**Comment by gassmoeller** [comment]
Sorry that I did not get to merge this earlier. I mentioned that the code is ready to go, but you will need to update the test results once more because the main branch has changed since my last comment. Afterwards this is ready to merge (leave me a comment when you have updated the tests).

**Comment by alarshi** [comment]
@gassmoeller : Could you look at it, whenever you get a chance. The test was failing earlier because the implementation of `Depth dependent` material model changed in the meantime, but the tester seems happy now :)

**Review by gassmoeller — APPROVED** [review]
I will merge this, but @alarshi please make a follow up PR with a changelog entry.

**Pull request merged**
