### PR TITLE
Remove an unused function from two geometry models.

### PR DESCRIPTION
**Pull request by bangerth**
In working on #5421, I'm looking at the way the existing geometry models with topography access the manifold. In doing so, I came across the fact that the `Chunk` and `TwoMergedChunks` models have a member function `depth_wrt_topo()`, which seems to be a useful question to ask -- but these functions are not used anywhere and we've generally found that (i) functions that are not used or tested accumulate bugs over time, (ii) if they exist in one model, someone might expect them to exist in other models as well where they may be much more difficult to implement.

For these reasons, this patch simply removes this function from the two models in question.

### CODE REVIEW

**Comment by bangerth** [comment]
These tests currently fail:
```
The following tests FAILED:
	 81 - ascii_data_slice (Failed)
	212 - compute-no-normal-flux-constraints (Failed)
	334 - gmg_mesh_deform_adaptive (Failed)
	335 - gmg_mesh_deform_adaptive_bug (Failed)
	337 - gmg_mesh_deform_function (Failed)
	341 - gmg_no_normal_flux_only (Failed)
	342 - gmg_test_project_q1 (Failed)
	345 - gmg_velocity_boundary_2d_chunk_no_flux (Failed)
	346 - gmg_velocity_boundary_2d_chunk_no_normal_flux (Failed)
	349 - gmg_velocity_boundary_3d_chunk_no_flux (Failed)
	350 - gmg_velocity_boundary_3d_chunk_no_normal_flux (Failed)
	769 - rheology_scaled_profile (Failed)
	789 - shell_2d_gmg (Failed)
	790 - shell_3d_gmg (Failed)
	792 - shell_quarter_BC (Failed)
	793 - shell_quarter_gmg (Failed)
	861 - steinberger_compressible_gmg (Failed)
	920 - tomography_based_plate_motions_cookbook (Failed)
```
I don't know whether they are all multigrid-related (given that the MG tests currently fail with deal.II mainline).

**Review by gassmoeller — COMMENTED** [review]
Yes, good point. We will have to rethink these function anyway since they cannot work with the mesh deformation framework.

Could you add a changelog entry to let users with custom plugins know?

Also @anne-glerum: I think you added these functions. Are they in active use by anyone?

**Comment by gassmoeller** [comment]
All the test failures are multigrid related.

**Comment by bangerth** [comment]
Changelog: So done.

**Review by gassmoeller — APPROVED** [review]
Thank you, looks good.

**Pull request merged**
