### PR TITLE
Output surface stress as a tensor field.

### PR DESCRIPTION
**Pull request by bangerth**
I forgot this in #3703. The changes are equivalent, just to another viz postprocessor.

/rebuild

### CODE REVIEW

**Comment by anne-glerum** [comment]
Thanks! The tester fails, because on the tester the individual stress components do get a postscript indicating the component (e.g. _xx). As I wrote in #4176, I think it's great to have those postscripts. Was there a change in deal.II that they are now outputted?

**Review by anne-glerum — APPROVED** [review]

**Comment by bangerth** [comment]
Yes, the deal.II changes are in https://github.com/dealii/dealii/pull/10803 and https://github.com/dealii/dealii/pull/10806

**Comment by bangerth** [comment]
Ah yes, the tester runs deal.II 9.2 and that still generates different output. Let's try this again.

**Comment by bangerth** [comment]
Ping?

**Comment by anne-glerum** [comment]
Ping! Thanks for updating the test!

**Pull request merged**
