### PR TITLE
Strip comments from Additional shared libraries parameter

### PR DESCRIPTION
**Pull request by jperryhouts**
If you try to re-run aspect from one of the automatically generated prms you run in to some problems. This patch fixes one of them.

### CODE REVIEW

**Comment by tjhei** [comment]
what error are you seeing?

**Comment by jperryhouts** [comment]
Oh, I should have been more clear. The problem is that if you include any additional shared libraries, the output_directory/parameters.prm file gets a tag at the end of any non-default lines that says what the default value would have been (in the case of the Additional shared libraries parameter it looks like "# default:".

So the error you get if you re-run aspect on the parameter file *IF* you also imported additional shared libraries, looks like :

`Could not successfully load shared library <./plugins/material.so # default:>. The operating system reports that the error is this: <./plugins/material.so # default:: cannot open shared object file: No such file or directory>.`

**Comment by jperryhouts** [comment]
...which happens because that line is parsed before the ParameterHandler exists, so comments have not yet been stripped.

**Comment by tjhei** [comment]
Good point! Can you use something like the following instead?
```
diff --git a/source/main.cc b/source/main.cc
index 552d695..f6325e6 100644
--- a/source/main.cc
+++ b/source/main.cc
@@ -84,6 +84,11 @@ get_last_value_of_parameter(const std::string &parameters,
       if ((line.size() < 1) || (line[0] != '='))
         continue;
 
+      // remove comment
+      if (std::string::size_type pos =line.find('#')
+          != std::string::npos)
+        line.erase(pos);
+
       // trim the equals sign at the beginning and possibly following spaces
       // as well as spaces at the end
       line.erase(0, 1);
```

**Comment by jperryhouts** [comment]
For some reason that doesn't want to work. The debugger tells me that the `pos` variable gets the value `1`, rather than whatever `line.find('#')` returns.

I can at least change the last line to `shared_libs.erase (shared_libs.find('#'));` (ie without the last argument in erase()) because apparently that works. Since this only gets run once, the overhead to run `string::find()` twice shouldn't be a big deal. I agree that it looks weird to repeat it like this, though.

For what it's worth, I copied the syntax here from deal.II in source/base/parameter_handler.cc:2565

**Comment by tjhei** [comment]
Oh, I didn't test it. My main point was to move it into ```get_last_value_of_parameter``` because the same problem will happen with the problem dimension.

**Comment by tjhei** [comment]
```
      // remove comment
      std::string::size_type pos =line.find('#');
      if (pos != std::string::npos)
        line.erase(pos);
```

**Comment by jperryhouts** [comment]
Ah, I see. I wasn't paying attention to the whole patch there. Good catch. I updated the patch.

**Comment by tjhei** [comment]
Looks good to me. Jonathan, did you confirm that this makes "dimension" and "additional libraries" work with a comment behind it?

**Comment by jperryhouts** [comment]
Yep, all looks good now. There's still an issue with running these auto-generated .prms, ( #635 ) but this patch is good to go.

**Comment by bangerth** [comment]
The other parameter that is treated specially is `set Dimension = ...`. Wouldn't you have to do the same treatment there as well?

**Comment by jperryhouts** [comment]
That's why Timo suggested to move this to `get_last_value_of_parameter`. This patch handles both cases.

**Comment by bangerth** [comment]
Ah, great, thanks for reminding me of the logic.

**Pull request merged**
