### PR TITLE
fix compiling with newest deal.II master

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by MFraters** [comment]
I ran also into this issue yesterday, but didn't have the time to make a pull request yet. There are two more places which need the same fix: source/simulator/stokes_matrix_free.cc and source/heating_model/compositional_heating.cc

**Comment by tjhei** [comment]
This should be good to go.

**Review by MFraters — APPROVED** [review]
Great, looks good!

**Comment by tjhei** [comment]
(I cherry-picked to 2.5 branch)

**Comment by tjhei** [comment]
broken by https://github.com/dealii/dealii/pull/15401 by the way

**Pull request merged**
