### PR TITLE
GMG mesh displacement: clear user constraints

### PR DESCRIPTION
**Pull request by zjiaqi2018**
Clear the user constraints to avoid cycled constraints in certain cases.

### CODE REVIEW

**Comment by tjhei** [comment]
Let me play with this first. Sadly, this requires 9.5, so the tester won't help.

**Comment by zjiaqi2018** [comment]
ok, I will also test it on my machine.

**Comment by gassmoeller** [comment]
@zjiaqi2018 what is the status of this PR? We now require deal.II 9.5 so testing the change should be easier. If you rebase to the current main branch all the tests should test your change.

**Comment by tjhei** [comment]
I rebased.

**Review by bangerth — APPROVED** [review]
If it works, ok with me...

**Pull request merged**
