### PR TITLE
Add eigenvalues to the outputs of the bingham average particle property

### PR DESCRIPTION
**Pull request by Wang-yijun**
I've added eigenvalues to the outputs of the Bingham average particle property. They will be used in the anisotropic viscosity material model to compute Hill's coefficients. I've changed the size and position of this data accordingly.

### CODE REVIEW

**Comment by MFraters** [comment]
Thanks for the pull request. I think this is the right approach. Can you rebase on the newest master? That should add a tests which you will need to update now.

**Comment by Wang-yijun** [comment]
The cpo_simple_shearbox test passed and I fixed the particle property_information.

**Comment by MFraters** [comment]
I would have expected the new bingham test to be added and that you need to change it. It seems that there is still a merge conflict. Can you rebase again?

**Review by MFraters — APPROVED** [review]
Looks good to me now. Can you get rid of the empty "merge" commits? Otherwise good to merge.

**Review by MFraters — APPROVED** [review]

**Pull request merged**
