### PR TITLE
Subtract mesh velocity before computing whether a boundary experiences in- or outflow for fixed boundary conditions

### PR DESCRIPTION
**Pull request by anne-glerum**
As described in https://github.com/geodynamics/aspect/issues/5994, this PR corrects the velocity that is used to determine whether a boundary is an in- or outflow boundary by subtracting the mesh velocity. Otherwise some boundary parts can be considered inflow boundaries and fixed composition will be prescribed, eventhough no inflow occurs, and vice versa.

I have added a new benchmark prm to test these changes, and can turn that into a test.

I would like input on what to do during the 0th and 1st timestep as I had to set the whole boundary to outflow at t0 and t1, because:

1. The compositional boundary conditions are computed at the beginning of the timestep before mesh deformation.
2. Mesh deformation is first computed at t1, not t0.
3. Stokes and mesh velocity in the benchmark setup are therefore 0 during the evaluation of in/outflow in timestep t0 and t1, and the whole top boundary would become a prescribed field boundary.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [x] I have tested my new feature locally to ensure it is correct.
* [x] I have [created a testcase](https://aspect-documentation.readthedocs.io/en/latest/user/extending/testing/writing-tests.html) for the new feature/benchmark in the [tests/](../blob/main/tests/) directory.
* [ ] I have added a changelog entry in the [doc/modules/changes](../blob/main/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Thanks for the fix Anne! The code looks good, and yes a test made out of this benchmark would be great.

To your questions: I think this is linked to our perennial discussion on whether open boundaries through which no material is flowing at the moment should be considered inflow or outflow boundaries. I think the current state and remaining problems are summarized in #5500  (other relevant issues are #5042, #5481, and in particular also #5479). I am not sure what an optimal solution would look like. Do you think input parameters in the `boundary temperature` and `boundary composition` subsection that allow the user to select how to treat boundaries with no flow at the current time would solve some problems? In #5479 I suggested to make the treatment dependent on whether there is diffusion in the field or not, would that work for this case?

**Comment by anne-glerum** [comment]
Hi Rene, I've added the test. 

I think adding a parameter that specifies how to treat the deforming boundary for zero flow in timestep 0 would be good. With mesh deformation though, it also has to apply in t1, as the mesh velocity will be evaluated to determine in/outflow before mesh velocity has actually been solved for. 

I don't fully understand the diffusive field option. Do you mean that if a field does not undergo natural diffusion, but only numerical because of stabilization, like a standard compositional field, other boundary conditions should apply then for temperature?

**Comment by gassmoeller** [comment]
Could you: 1. Reduce the size of the test by one or two mesh refinement levels to keep the output smaller, and 2. Remove the change to the t0 and t1 and update the test results? Then we can merge the improvement of considering mesh velocities first and deal with the t0 and t1 in another way. 

Maybe we can try to revive #5479 where I tried before to allow the user to select whether to apply boundary conditions on boundaries that have no flow across them. That is not exactly the problem here though, so we will have to think how to fix it completely.

**Review by gassmoeller — APPROVED** [review]
Thanks, this is ready to merge. I took the liberty of squashing your commits and adding a changelog to speed up the merge process ;-).

**Pull request merged**
