### PR TITLE
avoid overloaded initialize() warning

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by bangerth** [comment]
Hm, looks like we shot ourselves in the foot here with our naming convention. Or maybe C++ shot itself in the foot with the semantics chosen for name lookup (which in this case I think are ridiculous).

Anyway, if it tests correctly, please merge.

**Comment by tjhei** [comment]
Yeah, I don't particularly like it either. I don't think we are overriding ```SimulatorAccess::initialize()``` anywhere so we could rename this function. That only leaves the ```AsciiData``` and there we could also either rename the functions (I haven't looked at AsciiData closely, but maybe we could rework it to use composition instead of inheritance).
Thoughts?

**Comment by bangerth** [comment]
Good point. Rename `SimulatorAccess::initialize()` to `SimulatorAccess::initialize_simulator()` for example. That takes care of 3/4 of the problem.

I think the ascii data relationship is really one of is-a, rather than has-a, so inheritance seems appropriate.

**Comment by tjhei** [comment]
okay, how does that look? (assuming the tests will run through)

**Comment by bangerth** [comment]
This looks good. If you don't like the remaining `using` declarations, how about renaming the `ASCIIData::initialize` function to something more descriptive as well?

**Comment by tjhei** [comment]
Yes, I am struggling to find a better name than ```initialize_ascii_data``` though. It does initialization of the data structures and loads the data file.

**Comment by bangerth** [comment]
That name is silly too, given that it simply repeats the class name. Maybe we just need to stick with it and go with what you have right now. Feel free to commit if you want.

**Pull request merged**
