### PR TITLE
constraints: periodic before hanging

### PR DESCRIPTION
**Pull request by tjhei**
This PR is to check if #2779 makes a difference.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Does not seem to make a difference. On the other hand: Do we have a test with hanging nodes along  periodic boundaries in parallel? Maybe it is just untested. I remember we had an issue with DG elements on parallel AMR periodic boundaries, which we disallowed in #2132. Maybe that is related?

**Comment by tjhei** [comment]
> Maybe it is just untested

Likely. It also only happens rarely (specific parallel distribution needs to occur). I just wanted to see if it does make a difference by running the tester.

> I remember we had an issue with DG elements on parallel AMR periodic boundaries

Unlikely as you don't have hanging node constraints with DG.

**Comment by gassmoeller** [comment]
So what do we do? Merge this? Add a test even if we do not know if it was broken before?

**Comment by gassmoeller** [comment]
What is the status on this PR? Anything missing to merge it? Or has the topic been solved in deal.II, and this is a leftover?

**Comment by gassmoeller** [comment]
Should this go into 2.1? We have not seen an effect, but it is a possible bug fix.

**Comment by gassmoeller** [comment]
@tjhei: I will defer this to you. The change does not seem to affect anything, and if we consider this new version to be the correct one, then lets merge it for the release.

**Comment by tjhei** [comment]
Gosh, sorry for ignoring your comment for the last 4 months. One problem is that I am not 100% if this will break anything. I don't think we have great test coverage for parallel, 3d problems. Maybe we should leave this out of 2.1? Not sure. @bangerth ?

**Comment by gassmoeller** [comment]
No problem. Ok, lets leave it out of 2.1. However, then lets at least merge it now. Tests are passing, and if we find any problems with it until the release of 2.2 we have time to fix them.

**Comment by tjhei** [comment]
Agreed!

**Comment by bangerth** [comment]
Apologies for ignoring this for that long. The order only makes sense if:
* You have adaptive mesh refinement
* Some of the hanging nodes are located on the boundary
* Which can only happen in 3d.
In essence, you need to determine whether the value of a hanging node at the boundary is supposed to be 1/2 of the adjacent nodes, or equal to the correct boundary values. In the former case you end up with a continuous solution that violates the boundary conditions; in the latter the solution is discontinuous at refined faces but has the correct boundary values.

If you wanted to check this, you'll have to have a 3d geometry and boundary values that are not part of the solution space.

**Pull request merged**
