### PR TITLE
Specify reaction terms in latent heat material model

### PR DESCRIPTION
**Pull request by naliboff**
This pull request addresses issue #1896, which was originally pointed out by Derek Neuharth (University of Idaho). Specifying the reaction terms in the latent heat material model fixes the assembly error when using compositional fields.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Makes sense. For some reason astyle is not happy, can you take a look?

**Comment by naliboff** [comment]
@gassmoeller - Thanks for taking a look. Odd, I thought I ran astyle the first time around but perhaps not.

**Comment by naliboff** [comment]
Before merging, there are a number of small edits I would like to make in the material model documentation. Should I add those in another commit here, or put them in a separate pull request?

**Comment by tjhei** [comment]
> Before merging, there are a number of small edits I would like to make in the material model documentation. Should I add those in another commit here, or put them in a separate pull request?

Just make a separate PR. This makes things easier to review.

**Comment by bangerth** [comment]
Yes, indeed. If things are logically separate, then they should go into separate pull requests.

**Pull request merged**
