### PR TITLE
Checkpoint resume fixes part 2

### PR DESCRIPTION
**Pull request by tjhei**
- add more tests
- fix bug in restart-resume

Note that the current state is the following:
- PETSc, direct solver: works
- PETSc, iterative solver: works
- Trilinos, direct solver: works
- Trilinos, iterative solver: fails unless I change the AMG parameters to:

    Amg_data.elliptic = false;
    Amg_data.higher_order_elements = false;
    Amg_data.smoother_type = "symmetric block Gauss-Seidel";

### CODE REVIEW

**Comment by tjhei** [comment]
Oh and by "work" I mean bit-wise identical solution vectors are generated.

**Comment by tjhei** [comment]
Note: tester must have crashed again, please don't merge yet.

**Comment by tjhei** [comment]
ready to be merged (and hoping for an idea about AMG).

**Comment by bangerth** [comment]
Nice work. I wished I had something to offer for the AMG problem, but I don't really :-(

**Comment by bangerth** [comment]
(Maybe the problem solves itself once we get to switch to MueLu...)

**Pull request merged**
