### PR TITLE
Fix tangential BCs for GMG

### PR DESCRIPTION
**Pull request by tcclevenger**
From issue https://github.com/geodynamics/aspect/issues/3512, the iteration counts for Stokes would increase when running in parallel on spherical mesh with Tangential boundary. Simple fix: ~~when~~ after constructing the diagonal of the A block operator (used in GMG smoothers), ~~we needed to loop over all owned and ghost cells (previously just looped over owned cells)~~, we need to call `compress()` to exchange contribution from ghosted cells (previously only contributions from owned cells were accounted for).

There is actually already a test (`shell_3d_gmg.prm.dealii_9.2`), but I believe that since it is only on version dealii9.2 it wasn't being run and the high iteration counts were overlooked.

### CODE REVIEW

**Comment by gassmoeller** [comment]
I believe you that this fixes the issue, but can you explain quickly why we need the contributions from ghost cells? As far as I know for AMG we only assemble locally owned cells and that is enough. Is this because the matrix entries for AMG are communicated between neighbors so that the contributions end up in the correct places, and GMG does some local operations without communication?

**Comment by tcclevenger** [comment]
> As far as I know for AMG we only assemble locally owned cells and that is enough. 

Good call, that also holds here. So I rephrase the issue as, I was missing a call to `compress()` at the end of assembly (which communicates the ghost values). So now the fix is just to add `compress()` and keep assembly to only owned cells (which should be cheaper than every processor assembling on ghost cells). Thanks, Rene!

**Comment by tjhei** [comment]
> So now the fix is just to add `compress()`

This means that ghost values had incorrect entries because of the missing call to compress? It might be worth investigating putting NaN into the ghost region when a vector is created in debug mode.

**Pull request merged**
