### PR TITLE
Created multicomponent EoS->Material averaging function 

### PR DESCRIPTION
**Pull request by bobmyhill**
This PR adds a function that does multicomponent EquationOfState property averaging. 
This function is stored in the equation of state interface, in the MaterialModel namespace.

* [x] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).
* [x] I have tested my new feature locally to ensure it is correct.

### CODE REVIEW

**Comment by naliboff** [comment]
@bobmyhill - Awesome! Let me know when you would like a review for this!

**Comment by bobmyhill** [comment]
Hi @naliboff, this is ready for a review now :)

**Review by naliboff — COMMENTED** [review]
@bobmyhill - looks good, thanks for moving this code to a utilities function! Before merging, is your plan to go through the other material models and use this function? I believe this could at least be used in `visco_plastic` that has nearly identical lines of code?

**Comment by bobmyhill** [comment]
Hi @naliboff, yes, that's the intention (in another PR)!

**Review by naliboff — APPROVED** [review]
@bobmyhill - Sounds good, let me know when the other PR is ready for review!

**Comment by jdannberg** [comment]
So @bobmyhill I thought we had discussed yesterday that the averaging is the responsibility of the material model, not of the equation of state, so this functionality should be part of the material model utilities, not of the interface of the equation of state. The equation of state only knows things about individual compositions, and the material model decides how the material properties are computed from that. Could you fix that in a follow-up pull request? Or did you have a different reason why you thought that should go into the equation of state rather than in the material model?

**Comment by bobmyhill** [comment]
@jdannberg I did try to do it the way we discussed, but the include hierarchy seems to be structured in such a way as to make that difficult (the EoS interface knows about the material model utilities/classes, not the other way round). Do you think there's a robust workaround?

**Pull request merged**
