### PR TITLE
Output precision to statistics file for time and Time Step Size is now 12

### PR DESCRIPTION
**Pull request by egpuckett**
These changes are in response to issue #824 opened 3 days ago by @bangerth and subsequent email correspondence between @bangerth and @egpuckett

### CODE REVIEW

**Comment by bangerth** [comment]
These changes are almost certainly going to break every single one of our 310 tests. 

Let's find out! 
/run-tests

**Comment by egpuckett** [comment]
Oh pooh! I assume this is because the diff script is comparing digits and the changes produce and additional n digits, which causes the test to fail?

**Comment by bangerth** [comment]
Yes, that's the cause. (We do compare only up to a tolerance, but the relative difference here is larger than the tolerance we compare against :-( )

But you can download a patch file for the differences here: http://www.math.clemson.edu/~heister/aspect-logs/2b8e7463f9659ffea9e00c6b7807ca325be03beb/changes.diff . Just apply it and add the result as a second commit to your pull request.

**Comment by egpuckett** [comment]
I assume /run-tests will start automatically?

**Comment by egpuckett** [comment]
I guess so ...

**Comment by tjhei** [comment]
You also need to update the output from the PETSc tests (sorry there is no automated way to generate a patch file for that at the moment).

**Comment by egpuckett** [comment]
How do I do that?

**Comment by tjhei** [comment]
There is no way to get access to the diffs or a patch file right now. I made a patch for you though. Can you please do
```
git fetch https://github.com/tjhei/aspect pr830
git merge FETCH_HEAD
```

**Comment by egpuckett** [comment]
Done!

**Comment by tjhei** [comment]
You broke nearly every test by changing the name of the RK2 in source/particle/integrator/rk_2.cc (from "rk2" to "RK2").

**Comment by egpuckett** [comment]
That was foolish of me. Rene warned me about this, but I failed to notice that the change was committed when I committed the change to 12 digit precision.  My sincere apologies. Mea culpa ...

**Comment by bangerth** [comment]
On 04/25/2016 01:30 PM, Elbridge Gerry Puckett wrote:
> That was foolish of me. Rene warned me about this, but I failed to notice that
> the change was committed when I committed the change to 12 digit precision. My
> sincere apologies. Mea culpa ...

Rule #1: Only one functional change per pull request or commit! :-)

**Comment by egpuckett** [comment]
Got it!

**Pull request merged**
