### PR TITLE
Fix the units for the darcy velocity postprocessor

### PR DESCRIPTION
**Pull request by danieldouglas92**
Within the darcy velocity postprocessor, the multiplier which converts the units of the darcy velocity to years instead of seconds was not being multiplied by the solid velocity, this PR fixes this unit discrepancy.

### CODE REVIEW

**Comment by danieldouglas92** [comment]
I'm not sure why the dealii-master tests suite is failing, but this seems like something outside of the scope of this PR?

**Review by gassmoeller — APPROVED** [review]
Nice find. The failing test for deal.II master was unrelated and should be fixed, I restarted the tester to double check.

However, since none of our own tests are failing that means we currently have no test for this postprocessor. Would it be hard to add one either in this PR or as a follow-up?

**Comment by danieldouglas92** [comment]
This is actually a test for this postprocessor in `darcy_convection_step.prm`, but the reason this bug wasn't found in that test is that the solid velocity was 0 anyway! I could modify another test which uses the `darcy field` advection method with a non zero solid velocity though?

**Comment by tjhei** [comment]
> I could modify another test

that would be great!

**Comment by danieldouglas92** [comment]
I decided it would be best to just update the existing test and make the solid velocity non-zero, there wasn't an existing test where it would be clear to see that the solid velocity was properly being taken into account in the post-processing.

**Review by gassmoeller — APPROVED** [review]
Most often it is best to add new tests instead of modifying existing ones, because we want tests to be specific to one feature. That being said, in this case the existing test was to test exactly this and just wasnt working as expected. So we can go ahead with this PR. One of the tester machines had trouble (likely unrelated to your PR). I restarted the testers, if they pass this is ready to merge. :+1:

**Pull request merged**
