### PR TITLE
add 2.2 announcement

### PR DESCRIPTION
**Pull request by tjhei**
This is a draft. Suggestions welcome.

### CODE REVIEW

**Comment by gassmoeller** [comment]
I am working on suggestions. We wanted to add author names.

**Comment by tjhei** [comment]
This is good to go from my end.

**Comment by gassmoeller** [comment]
Looks good. No real need to wait for the tester, but I will merge once its done. Does this need to be cherry-picked to the release branch?

**Comment by tjhei** [comment]
> Does this need to be cherry-picked to the release branch?

I don't think that matters.

**Pull request merged**
