### PR TITLE
Use MappingQ1 when appropriate.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Addresses #999

### CODE REVIEW

**Comment by gassmoeller** [comment]
Looks good. Ready to merge when the tester is finished.

**Comment by bangerth** [comment]
Ah, excellent that this actually works! Thanks, @ian-r-rose , for trying my little experiment!

**Comment by ian-r-rose** [comment]
Sure thing! I learned a thing about heterogeneous types in ternary statements today.

**Comment by bangerth** [comment]
Yep, from the C++ standard, section 5.16.3:
```
3
 Otherwise, if the second and third operand have different types and either has (possibly cv-qualified) class
type, or if both are glvalues of the same value category and the same type except for cv-qualification, an
attempt is made to convert each of those operands to the type of the other. The process for determining
whether an operand expression E1 of type T1 can be converted to match an operand expression E2 of type
T2 is defined as follows:
(3.1)
— If E2 is an lvalue: E1 can be converted to match E2 if E1 can be implicitly converted (Clause 4) to the
type “lvalue reference to T2”, subject to the constraint that in the conversion the reference must bind
directly (8.5.3) to an lvalue.
(3.2)
(3.3)
3.3.1)
3.3.2)
— If E2 is an xvalue: E1 can be converted to match E2 if E1 can be implicitly converted to the type
“rvalue reference to T2”, subject to the constraint that the reference must bind directly.
— If E2 is a prvalue or if neither of the conversions above can be done and at least one of the operands
has (possibly cv-qualified) class type:
— if E1 and E2 have class type, and the underlying class types are the same or one is a base class
of the other: E1 can be converted to match E2 if the class of T2 is the same type as, or a base
class of, the class of T1, and the cv-qualification of T2 is the same cv-qualification as, or a greater
cv-qualification than, the cv-qualification of T1. If the conversion is applied, E1 is changed to a
prvalue of type T2 by copy-initializing a temporary of type T2 from E1 and using that temporary
as the converted operand.
— Otherwise (if E1 or E2 has a non-class type, or if they both have class types but the underlying
classes are not the same and neither is a base class of the other): E1 can be converted to match

E2 if E1 can be implicitly converted to the type that E2 would have after applying the lvalue-to-
rvalue (4.1), array-to-pointer (4.2), and function-to-pointer (4.3) standard conversions.
Using this process, it is determined whether the second operand can be converted to match the third operand,
and whether the third operand can be converted to match the second operand. If both can be converted,
or one can be converted but the conversion is ambiguous, the program is ill-formed. If neither can be
converted, the operands are left unchanged and further checking is performed as described below. If exactly
one conversion is possible, that conversion is applied to the chosen operand and the converted operand is
used in place of the original operand for the remainder of this section.

```

I thought you might be curious ;-)

**Comment by ian-r-rose** [comment]
A model of clarity, that.

**Comment by bangerth** [comment]
I thought it was quite obvious what they were saying! Are you saying that you did not read the full 1368 pages of the C++14 draft end to end so far? It's a good night time read!

**Pull request merged**
