### PR TITLE
Add release announcement

### PR DESCRIPTION
**Pull request by gassmoeller**
This is a tentative release announcement. I filtered the changelog for changes important to users, and shortened some entries. Let me know if you think anything important is missing.

### CODE REVIEW

**Comment by gassmoeller** [comment]
Related to #2867.

**Comment by MFraters** [comment]
Isn't this also the first release which includes the geodynamic world builder?

**Comment by gassmoeller** [comment]
Hah, very good point. But you never added a changelog entry, that is why it did not appear in the list of changes. Can you write a changelog entry? We need to figure out how to best add this, as I just merged #2875, which deleted all of the old changelog entries. Maybe add it directly to `doc/modules/to-2.1.0.h` and `doc/release-tasklist` and do not create a file in `doc/modules/changes`.

**Comment by jdannberg** [comment]
Seems like we also forget the changelog entry for something else:
a new plugin system that allows it to prescribe a fixed heat flux (as an alternative to prescribing the temperature) at the model boundaries

**Comment by gassmoeller** [comment]
Ok, heat flux boundary conditions are included. Let me know in case you find anything else. Otherwise this is good to go.

**Comment by tjhei** [comment]
Looks good, thanks! I will merge so I can cherry-pick the change to the 2.1 branch. We can edit the changelog in a followup if needed.

**Pull request merged**
