### PR TITLE
fix uninitialized variables

### LINKED ISSUE #5763: Warning in rheology/composite_visco_plastic.cc
```
/ssd/aspect-git5/source/material_model/rheology/drucker_prager.cc:80:45: warning: ‘drucker_prager_parameters.aspect::MaterialModel::Rheology::DruckerPragerParameters::cohesion’ may be used uninitialized [-Wmaybe-uninitialized]
/ssd/aspect-git5/source/material_model/rheology/composite_visco_plastic.cc: In member function ‘double aspect::MaterialModel::Rheology::CompositeViscoPlastic<dim>::compute_composition_viscosity(double, double, unsigned int, const dealii::SymmetricTensor<2, dim>&, std::vector<double>&, const std::vector<double>&, const std::vector<unsigned int>&) const [with int dim = 3]’:
/ssd/aspect-git5/source/material_model/rheology/composite_visco_plastic.cc:139:43: note: ‘drucker_prager_parameters.aspect::MaterialModel::Rheology::DruckerPragerParameters::cohesion’ was declared here
```

### PR DESCRIPTION
**Pull request by tjhei**
fixes #5763

### CODE REVIEW

**Comment by tjhei** [comment]
I am not sure this is the right thing to do or if we need to initialize with invalid values, but this makes the warnings go away...

**Review by bangerth — CHANGES_REQUESTED** [review]
This should not be necessary. The default constructor of that structure should do that. If it doesn't have one, it needs to be added.

**Comment by tjhei** [comment]
> If it doesn't have one, it needs to be added.

It is a struct without any constructor or functions:
```
https://github.com/geodynamics/aspect/blob/d87c3c8df59ec5c479b94bfad8a3ff3d702c0eb2/include/aspect/material_model/rheology/diffusion_creep.h#L40-L51
```

By your logic, wouldn't this become a class if you add constructors to it?

**Comment by bangerth** [comment]
The difference in initialization of structures with
```
  MyStruct s;
```
and
```
  MyStruct s{};
```
and
```
  MyStruct s = {};
```
is so convoluted and ununderstandable that I'm opposed to it. Let's add a constructor to the class that avoids the issue.

**Comment by tjhei** [comment]
> Let's add a constructor to the class that avoids the issue.

NaNs or 0.0 for doubles?

**Comment by gassmoeller** [comment]
NaN's
If anyone uses this without initialization it is wrong.

**Comment by tjhei** [comment]
updated.

**Review by bangerth — APPROVED** [review]
Yes, I like it. Curious to see how much breakage you get!

**Comment by bangerth** [comment]
Might as well squash/fixup, though.

**Pull request merged**
