### PR TITLE
Compute elastic force term at t0 as well

### PR DESCRIPTION
**Pull request by anne-glerum**
When the stored stresses at start-up are not zero (i.e. the compositional fields have some initial non-zero value), I believe the force term should be taken into account. The behavior for t0 with zero elastic stress should not change, as the force term is then a multiple of zero.

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/master/CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:

* [x] I have tested my new feature locally to ensure it is correct.
* [x] I have [created a testcase](http://www.math.clemson.edu/~heister/manual.pdf#sec%3Awriting_tests) for the new feature/benchmark in the [tests/](../blob/master/tests/) directory.
* [x] I have added a changelog entry in the [doc/modules/changes](../blob/master/doc/modules/changes) directory that will inform other users of my change.

### CODE REVIEW

**Review by bobmyhill — APPROVED** [review]
Yes!

**Comment by bobmyhill** [comment]
(I assume that either there are some tests that will need fixing or a new test should be made)

**Comment by naliboff** [comment]
Yep, good catch! 

I agree with @bobmyhill that we should add a test where the initial elastic stress is non-zero. Maybe the viscoelastic stress build-up example could be modified to have the initial stress correspond to the analytical solution at a given point in time? The value at the next step time step should then also match the analytical solution.

**Comment by anne-glerum** [comment]
I'll add a test here as well. The stress build up one is a good idea.

**Comment by anne-glerum** [comment]
Shall I update the new test's results?

**Review by naliboff — APPROVED** [review]
@anne-glerum - Thanks for adding the additional test!

**Comment by naliboff** [comment]
@anne-glerum @bobmyhill  - Do you think it would be worth adding a change log entry for this PR? It is a minor change, but it will have a large effect on anyone who plans to run "pre-stressed" VE/VEP models. Otherwise, ready to merge.

**Comment by bobmyhill** [comment]
A change log entry would be a good idea. I hope that the change will not affect many people, but if it affects anyone, then it would be good to highlight that change.

**Comment by anne-glerum** [comment]
Done :)

**Review by naliboff — APPROVED** [review]
👍 Thanks @anne-glerum!

**Pull request merged**
