### PR TITLE
Some changes in compute_current_constraints().

### PR DESCRIPTION
**Pull request by bangerth**
While working on the failing tests in #5398; see also #5405.

### CODE REVIEW

**Comment by bangerth** [comment]
Related also to #5412.

**Review by tjhei — APPROVED** [review]

**Comment by tjhei** [comment]
Not quite sure why, but the following tests fail:
```
	480 - matrix_nonzeros_4 (Failed)
	481 - matrix_nonzeros_5 (Failed)
	482 - matrix_nonzeros_6 (Failed)
	483 - matrix_nonzeros_7 (Failed)
	845 - spherical_nsinker (Failed)
```
I was not expecting the changes here to make any difference. Is the move constructor in 9.4 broken, by any chance?

**Comment by bangerth** [comment]
Hm, these tests seem to fail on `main` as well for me, at least locally. Not sure what to make of this. How does this look like for you? I'm going back to the `copy_from()` for pre-9.6, let's see whether that changes anything...

**Review by tjhei — APPROVED** [review]
This was indeed the issue. Weird.

**Comment by bangerth** [comment]
Huh, what do you know. Either way, nor worth investigating old versions of deal.II. This way works, and the workaround is going to go away eventually once we require post-9.5.

So then I think this is ready to merge.

**Comment by tjhei** [comment]
We are now down to 2 failing tests on master:
```
	657 - particle_periodic_boundaries_dc (Failed)
	675 - periodic_box2 (Failed)
```

It looks like periodic_box2 has an incorrect set:
```
An error occurred in line <682> of file </opt/tmp/unpack/deal.II-master/source/lac/trilinos_vector.cc> in function
    dealii::TrilinosScalar dealii::TrilinosWrappers::MPI::Vector::operator()(dealii::TrilinosWrappers::MPI::Vector::size_type) const
The violated condition was: 
    false
Additional information: 
    You are trying to access element 1182 of a distributed vector, but
    this element is not stored on the current processor. Note: There are
    2258 elements stored on the current processor from within the range
    [2310,4567] but Trilinos vectors need not store contiguous ranges on
    each processor, and not every element in this range may in fact be
    stored locally.
    
    A common source for this kind of problem is that you are passing a
    'fully distributed' vector into a function that needs read access to
    vector elements that correspond to degrees of freedom on ghost cells
    (or at least to 'locally active' degrees of freedom that are not also
    'locally owned'). You need to pass a vector that has these elements as
    ghost entries.

Stacktrace:
-----------
#0  /opt/deal.II-master/lib/libdeal_II.g.so.9.6.0-pre: dealii::TrilinosWrappers::MPI::Vector::operator()(unsigned int) const
#1  /opt/deal.II-master/lib/libdeal_II.g.so.9.6.0-pre: void dealii::AffineConstraints<double>::distribute<dealii::TrilinosWrappers::MPI::Vector>(dealii::TrilinosWrappers::MPI::Vector&) const
#2  /__w/aspect/aspect/build/aspect: aspect::Simulator<2>::interpolate_onto_velocity_system(dealii::TensorFunction<1, 2, double> const&, dealii::TrilinosWrappers::MPI::Vector&)
#3  /__w/aspect/aspect/build/aspect: aspect::Simulator<2>::remove_net_linear_momentum(bool, dealii::TrilinosWrappers::MPI::BlockVector&, dealii::TrilinosWrappers::MPI::BlockVector&)
#4  /__w/aspect/aspect/build/aspect: aspect::Simulator<2>::solve_stokes()
#5  /__w/aspect/aspect/build/aspect: aspect::Simulator<2>::assemble_and_solve_stokes(double const&, double*)
#6  /__w/aspect/aspect/build/aspect: aspect::Simulator<2>::solve_single_advection_single_stokes()
#7  /__w/aspect/aspect/build/aspect: aspect::Simulator<2>::solve_timestep()
#8  /__w/aspect/aspect/build/aspect: aspect::Simulator<2>::run()
```

**Pull request merged**
