### PR TITLE
make sure harmonic average particle interpolator does not average neg…

### PR DESCRIPTION
**Pull request by jdannberg**
…ative values

This is based on a discussion with @anne-glerum this morning. 

### For all pull requests:

* [x] I have followed the [instructions for indenting my code](../blob/main/CONTRIBUTING.md#making-aspect-better).

### CODE REVIEW

**Comment by jdannberg** [comment]
Looks like the one test that is failing (particle_interpolator_harmonic_average_solkz) triggers this exact problem: It averages a compositional field that is negative, in this case, it is the a field that is used to compute the density which is initialized as -1 * sin(2*z) * cos(3*pi*x) in a 1x1 box, so it varies between plus and minus 1. 

Any suggestions what to do with that? If this test is just for averaging, I could just add +1 to that whole function and it should be fine. Does that seem reasonable?

**Comment by gassmoeller** [comment]
> I could just add +1 to that whole function and it should be fine. Does that seem reasonable?

Seems reasonable to me since this test is not meant to test the accuracy of SolKz. Just add a comment to the parameter file that explains why you changed it.

**Comment by jdannberg** [comment]
Thank you! I have adapted the test (and while the pressure error is meaningless now, this actually improved the velocity error quite a bit).

**Review by gassmoeller — APPROVED** [review]
The improved velocity error probably comes from the fact we no longer compute wrong averages for the negative values.
Anyway, thanks for the fix.

**Pull request merged**
