### PR TITLE
Revert "Switched i and j in assembly"

### PR DESCRIPTION
**Pull request by tjhei**
Reverts geodynamics/aspect#372

This PR broke 3 tests (see [1]).

[1]: http://www.math.clemson.edu/~heister/aspect-logs/2de3196dd11af6dfba3948df996f2a16cbd3e22c/clang

### CODE REVIEW

**Comment by rrgrove6** [comment]
But isn't the "i" always supposed to be on the left?

**Comment by tjhei** [comment]
Well, it looks like the tests are roundoff errors. Maybe we should do
```scratch.phi_field[i] * (current_u * scratch.grad_phi_field[j])``` ?

**Comment by tjhei** [comment]
(or at least fix the test output)

**Comment by rrgrove6** [comment]
I think so.. my latest pull request also switches the order similarly for the RHS terms (just for aethetic reasons and to match what will eventually be in the manual).

**Pull request closed without merging**
