### PR TITLE
Fix representative point ellipsoidal chunk, and add documetation

### PR DESCRIPTION
**Pull request by MFraters**
Fix representative point ellipsoidal chunk, and add a bit of documentation on the phi_theta_d variable. #1202

### CODE REVIEW

**Comment by gassmoeller** [comment]
I am a bit confused that this passed all tests. Do we have no test for the ellipsoidal chunk? Or does it not test this particular function?

**Comment by MFraters** [comment]
The current tests on the ellipsoidal chunk are only designed to test if the grid points are at the correct location and if the depth is correct. Furthermore these tests have no lateral variations, so the small change of the horizontal location of the representative point should not matter I think.

**Comment by gassmoeller** [comment]
Ok. Would it be easy to design a simple test for this function (one that fails before and passes now)? If so it would be great if you could add one. If not, let me know, and I will put it on my todo list :smile:.

**Comment by bangerth** [comment]
I found this because @trajaona used the adiabatic conditions initial temperature, which takes a trajectory from the surface down to the bottom of the domain to compute adiabatic conditions, and realized that the points so computed are not actually inside the domain. So using this initial temperature plugin would exercise the current function, though possibly in a way that is not sensitive to where these points actually are (unless one had a material model that returns different values for different positions).

**Comment by bangerth** [comment]
@MFraters -- thanks, btw, for fixing this. I didn't mean to imply that you should fix this when I mentioned you in #1211, I was just asking for your opinion.

**Comment by MFraters** [comment]
@gassmoeller, I could make a test, but I only testing this function seems a bit limited for a whole test. So that is why I didn't add a test in here. If you know what things you want to test exactly, I guess it would be better that you add the test.

@bangerth No worries, it was only a few lines to change

**Comment by gassmoeller** [comment]
I had no specific thing that I wanted tested. I think it is just best practice to have tests cover as much of the code as possible (in particular if that code was broken without us noticing, because we had no test).
Thanks for the fix.

**Pull request merged**
