### PR TITLE
Fix error avmaterial

### PR DESCRIPTION
**Pull request by KiralyAgi**
There was a problem which didn't show up on a mac but resulted in SIGFPE error on Linux machines. Fixed by moving lines using timestep under the section where timestep is secured to be non-zero

### CODE REVIEW

**Comment by gassmoeller** [comment]
Thanks for the fix! You will need to run `make indent` or apply the changes of this file: https://jenkins.geodynamics.org/job/aspect/job/PR-3165/2/artifact/changes-astyle.diff

@tjhei: Could you take a look at the error message of your tester? I do not quite understand what failed there.

**Comment by KiralyAgi** [comment]
Fixed the indentation

**Comment by gassmoeller** [comment]
Looks good, thanks! The failure on Timo's tester seems unrelated, so this is ready to merge.

**Pull request merged**
