### PR TITLE
Fix FPE check with newer deal.II version

### PR DESCRIPTION
**Pull request by tjhei**
We forgot to set compiler flags (like c++11) when testing the floating
point exception stuff. You would get errors like:

/ssd/deal-build/installed/include/deal.II/base/exceptions.h:58:27:
error: expected ‘;’ at end of member declaration
/ssd/deal-build/installed/include/deal.II/base/exceptions.h:58:29:
error: ‘noexcept’ does not name a type

### CODE REVIEW

**Comment by bangerth** [comment]
OK to merge.

**Comment by bangerth** [comment]
Hm, this got 7 failing tests on clang. Unfortunately, the file with details appears to already have left your server, so I can't tell you what's going wrong....

**Comment by bangerth** [comment]
The test failures are all timeouts. I'm going to merge.

**Comment by tjhei** [comment]
> Hm, this got 7 failing tests on clang.
> The test failures are all timeouts. I'm going to merge.

Yes, I am not quite sure what is going on here with the tester. I didn't have timeouts before but they happen pretty much every time. I already reduced the -j X number...

**Pull request merged**
