### PR TITLE
fix damper stress calculation

### PR DESCRIPTION
**Pull request by bobmyhill**
The PR fixes the problem identified by @gassmoeller in #6001. The viscosity limiters for the CompositeViscoPlastic rheology now work as intended.

### CODE REVIEW

**Review by gassmoeller — COMMENTED** [review]
Oh, awesome this is the fix I was looking for. Can you add a test to the unittests that shows that the generated viscosities now fall within the limits prescribed?

**Comment by bobmyhill** [comment]
@gassmoeller I can do, although your test in #6001 does this already. Do you want me to rebase onto that and modify the test output?

**Comment by gassmoeller** [comment]
Oh right, can you just steal the test and everything that is useful from that branch and put it in here? It would be nice to merge everything together.

**Comment by bobmyhill** [comment]
Stolen :)

**Review by gassmoeller — APPROVED** [review]
Very cool. Ready to merge when the testers are done. The documentation tester is failing, but it is not caused by this PR (it looks like some sort of deprecation warning of the packages we use on readthedocs).

**Comment by bobmyhill** [comment]
@gassmoeller ok, this PR should be good now. I preserved your commits and made a few tweaks on top.

**Comment by bobmyhill** [comment]
Hah, you beat me to it! Thanks :)

**Pull request merged**
