### PR TITLE
Create a manifold for the spherical shell that can accommodate an initial topography.

### PR DESCRIPTION
**Pull request by bangerth**
WIP for now, just wanting to see whether this step will pass the CI checks.

### CODE REVIEW

**Comment by bangerth** [comment]
I cannot figure out what is going wrong here. We get the following error:
```
/home/runner/work/aspect/aspect/source/geometry_model/spherical_shell.cc: In instantiation of ‘class aspect::GeometryModel::{anonymous}::SphericalManifoldWithTopography<2>’:
/home/runner/work/aspect/aspect/source/geometry_model/spherical_shell.cc:359:37:   required from ‘void aspect::GeometryModel::SphericalShell<dim>::create_coarse_mesh(dealii::parallel::distributed::Triangulation<dim>&) const [with int dim = 2]’
/home/runner/work/aspect/aspect/source/geometry_model/spherical_shell.cc:871:5:   required from here
/home/runner/work/aspect/aspect/source/geometry_model/spherical_shell.cc:147:11: error:   by ‘void aspect::GeometryModel::{anonymous}::SphericalManifoldWithTopography<dim>::get_new_points(const dealii::ArrayView<const dealii::Point<dim> >&, const dealii::Table<2, double>&, dealii::ArrayView<dealii::Point<dim> >) const [with int dim = 2]’ [-Werror=overloaded-virtual]
  147 |           get_new_points(const ArrayView<const Point<dim>> &surrounding_points,
      |           ^~~~~~~~~~~~~~
```
There is clearly something missing where it says "error:  by 'void ...get_new_point...'", but I cannot figure out what that is. I *suspect* that it is something of the form "SphericalGeometry::get_new_points(...) is hidden by '...'", but I don't understand why anything would be hidden -- I copied the right signature from the `SphericalGeometry` class, and it compiles on my laptop locally, as well as my workstation. 

Does anyone see what I'm doing wrong?

**Comment by gassmoeller** [comment]
There is a private virtual function of the same name in SphericalManifold, is that the one that is causing the problem?

**Comment by bangerth** [comment]
@gassmoeller Oh, that's insiduous. Let's see if I can work around this.

**Comment by bangerth** [comment]
OK, so this is a total disaster :-( This isn't going to work without copying the class out of deal.II at least for now. Here's what's going on:

The base class, at least before https://github.com/dealii/dealii/pull/16242 basically looked like this:
```
class X {   // really SphericalManifold
  public:
    virtual void f();
  private:
    virtual void f(int);
};
```
If you derive from it, you don't care about the `private` member function of the same name as the `public` one. It's none of our business. But if we overload only the `public` one, like in
```
class Y : public X {
  public:
    virtual void f() override;
};
```
then the compiler says that this *hides* the other member function, and the warning is converted to an error. So one tries this:
```
class Y : public X {
  public:
    virtual void f() override;
  private:
    virtual void f(int) override;
};
```
This silences the warning about hiding the other function, but now we don't know how to *implement* the overload: It should really just call the function in the base class, but that function is `private` and so we can't do
```
void Y::f(int i) { return X::f(i); }
```

It just isn't possible to derive correctly from a base class that has a `virtual` `private` member function of the same name `virtual` `public` member function. We just shot ourselves in the foot by declaring that internal function as `virtual` by accident :-(

So what it's going to boil down to is that I need to copy the `SphericalManifold` class out of deal.II (after fixing the issue with the `virtual` `private` member function), and use that at least until we can rely on a fixed version of the class in a future deal.II release :-(

**Comment by bangerth** [comment]
OK, this work and if nobody objects, I'd like to move forward with this -- read: get it merged.

What the patch does at the moment is (i) duplicate the `SphericalManifold` class in its modified form so that we can derive from it, (ii) creates a derived class that currently does nothing, but will in a second step learn how to deal with initial topography.

The patch does, for the moment, not wrap the copied class in `#if !DEAL_II_VERSION_GTE(...) #endif`. This is because for this to work, we need to wait for the deal.II container to be up to date with deal.II, which last time took a couple of days. I'll make this kind of patch in a few days as a follow-up.

**Pull request merged**
