### PR TITLE
Clarifying variable name in Bilinear Least Squares

### PR DESCRIPTION
**Pull request by sac-bsa**
Pull Request Checklist. Please read and check each box with an X. Delete any part not applicable. Ask on the [forum](https://community.geodynamics.org/c/aspect) if you need help with any step.

*Describe what you did in this PR and why you did it.*
I changed the name of variable position to particle_position so that it would not be confused with positions. I did this change to the suggestion of @egpuckett after we both had to double check that a variable called position was not part of positions.

### Before your first pull request:
[X] I have read the guidelines in our [CONTRIBUTING.md](../CONTRIBUTING.md) document.

### For all pull requests:
[X] I have followed the [instructions for indenting my code](../CONTRIBUTING.md#making-aspect-better).

### For new features/models or changes of existing features:
[X] I have tested my new feature locally to ensure it is correct.

### CODE REVIEW

**Comment by egpuckett** [comment]
@bangerth, @tjhei

Some background ... Mack is working with me on a summer REU project. Mack is exploring new interpolation algorithms for particles and has some stunning results. This is collaborative work with Rene in the sense that Rene has been thinking along the same lines and done some initial coding of the same ideas or perhaps more accurately, along similar lines. We met with Rene last week and he encouraged Mack to make pull requests to the ASPECT master.

We met with Rene last week and h

**Comment by tjhei** [comment]
@sac-bsa thanks for submitting this PR. It seems like your email address set in git is not registered with your github account. This is why the commit above is not linked to your avatar. Can you please fix this? You can add your email address to your github account or change the git email address using https://help.github.com/en/articles/setting-your-commit-email-address#setting-your-commit-email-address-in-git

**Comment by sac-bsa** [comment]
@tjhei Thank you for pointing out that I hadn't setup my email in GitHub properly. I have now fixed that and see my avatar associated with my commit. I see that "All checks have failed" is that just from my email not being set up correctly or is there something else that I missed?

**Comment by tjhei** [comment]
Thanks. This should make the testers rerun and fix the checks:
/rebuild

**Comment by gassmoeller** [comment]
Thanks for the change Mack! Ready to go. :+1:

**Pull request merged**
