### PR TITLE
Added if/else checking for geometry model type

### PR DESCRIPTION
**Pull request by bobmyhill**

### CODE REVIEW

**Comment by bangerth** [comment]
/run-tests

Do I understand correctly that all you're doing is making sure we get different error messages for different ways of getting to a place where we shouldn't be?

**Comment by bobmyhill** [comment]
Hi @bangerth ... yes, this covers Issue #959.

**Comment by bangerth** [comment]
Ah, ok. Thanks for the link. Let's merge this already. If there are other places where we do similar things, want to fix those in follow-up patches?

**Comment by bobmyhill** [comment]
Sure, will do whenever I have spare minutes!

**Pull request merged**
